# INPUTS
# pathOutputDose
# id
# seed 
# primaries
# peakzlength_um
# peakztrans_mm
# peakzlength2_um
# peakztrans2_mm
# peakzlength3_um
# peakztrans3_mm
# peakzlength4_um
# peakztrans4_mm
# peak_material

# Gate /home/as17540/linac/mac/Main_PhS2_Elec_Sensor_0.9xSeaLevel_0.mac -a '[id,$PBS_ARRAY_INDEX] [peakzlength2_um,30] [peakztrans2_mm,-5.485] [peakzlength3_um,50] [peakztrans3_mm,-5.475] [peakzlength4_um,70] [peakztrans4_mm,-5.465] [peak_material,Copper] [seed,$RANDOM$RANDOM$RANDOM] [primaries,11273900] [pathOutputDose,/work/as17540/PhaseSpaces/PhS3_Sensor_10x10_Elec/]'

#=====================================================
# VISUALISATION
#=====================================================

#/control/execute mac/visu.mac

# =====================================================
# GEOMETRY
# =====================================================

/gate/geometry/setMaterialDatabase /home/as17540/linac/data/GateMaterials_0.908xSeaLevel.db

# WORLD
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    0.3 m
/gate/world/geometry/setYLength    0.3 m
/gate/world/geometry/setZLength    1 m
/gate/world/vis/setVisible 1

/gate/world/daughters/name                   PhS_Plane_Two
/gate/world/daughters/insert                 box
/gate/PhS_Plane_Two/setMaterial              Vacuum
/gate/PhS_Plane_Two/geometry/setXLength      22 cm
/gate/PhS_Plane_Two/geometry/setYLength      22 cm
/gate/PhS_Plane_Two/geometry/setZLength      1 nm
/gate/PhS_Plane_Two/placement/setTranslation 0.0 0.0 471 mm #(-529)
/gate/PhS_Plane_Two/vis/setColor             cyan
/gate/PhS_Plane_Two/vis/setVisible           1

/gate/world/daughters/name                   Kill_BackPlane
/gate/world/daughters/insert                 box
/gate/Kill_BackPlane/setMaterial                   Air	
/gate/Kill_BackPlane/geometry/setXLength           30 cm
/gate/Kill_BackPlane/geometry/setYLength           30 cm
/gate/Kill_BackPlane/geometry/setZLength           1 nm
/gate/Kill_BackPlane/placement/setTranslation      0.0 0.0 480 mm
/gate/Kill_BackPlane/vis/setColor                  red
/gate/Kill_BackPlane/vis/setVisible                1

/gate/world/daughters/name                   Kill_FrontPlane
/gate/world/daughters/insert                 box
/gate/Kill_FrontPlane/setMaterial                   Air	
/gate/Kill_FrontPlane/geometry/setXLength           30 cm
/gate/Kill_FrontPlane/geometry/setYLength           30 cm
/gate/Kill_FrontPlane/geometry/setZLength           1 nm
/gate/Kill_FrontPlane/placement/setTranslation      0.0 0.0 445 mm
/gate/Kill_FrontPlane/vis/setColor                  red
/gate/Kill_FrontPlane/vis/setVisible                1

/gate/world/daughters/name         epi
/gate/world/daughters/insert       box
/gate/epi/setMaterial                  Silicon
/gate/epi/geometry/setXLength          180.0 mm
/gate/epi/geometry/setYLength          180.0 mm
/gate/epi/geometry/setZLength          0.01 mm
/gate/epi/placement/setTranslation     0 0 449.995 mm
/gate/epi/vis/setVisible               1
/gate/epi/vis/setColor                 yellow
/gate/epi/vis/forceSolid

/gate/world/daughters/name         bulk
/gate/world/daughters/insert       box
/gate/bulk/setMaterial                  Silicon
/gate/bulk/geometry/setXLength          180.0 mm
/gate/bulk/geometry/setYLength          180.0 mm
/gate/bulk/geometry/setZLength          0.6 mm
/gate/bulk/placement/setTranslation     0 0 449.69 mm
/gate/bulk/vis/setVisible               1
/gate/bulk/vis/setColor                 red

/gate/world/daughters/name         peak_air_box 
/gate/world/daughters/insert       box 
/gate/peak_air_box/setMaterial                  Air 
/gate/peak_air_box/geometry/setXLength          200.0 mm 
/gate/peak_air_box/geometry/setYLength          200.0 mm 
/gate/peak_air_box/geometry/setZLength          11 mm 
/gate/peak_air_box/placement/setTranslation     0 0 455.5 mm
/gate/peak_air_box/vis/setVisible               1 
/gate/peak_air_box/vis/setColor                 green
/gate/peak_air_box/vis/forceWireframe

#/gate/peak_air_box/daughters/name         peakLayer1 
#/gate/peak_air_box/daughters/insert       box 
#/gate/peakLayer1/setMaterial                  {peak_material} 
#/gate/peakLayer1/geometry/setXLength          10.0 mm 
#/gate/peakLayer1/geometry/setYLength          10.0 mm 
#/gate/peakLayer1/geometry/setZLength          {peakzlength_um} um 
#/gate/peakLayer1/placement/setTranslation     -5 5 {peakztrans_mm} mm
#/gate/peakLayer1/vis/setVisible               1 
#/gate/peakLayer1/vis/setColor                 grey
#/gate/peakLayer1/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer2 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer2/setMaterial                  {peak_material} 
/gate/peakLayer2/geometry/setXLength          10.0 mm 
/gate/peakLayer2/geometry/setYLength          10.0 mm 
/gate/peakLayer2/geometry/setZLength          {peakzlength2_um} um 
/gate/peakLayer2/placement/setTranslation     5 5 {peakztrans2_mm} mm
/gate/peakLayer2/vis/setVisible               1 
/gate/peakLayer2/vis/setColor                 red
/gate/peakLayer2/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer3 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer3/setMaterial                  {peak_material} 
/gate/peakLayer3/geometry/setXLength          10.0 mm 
/gate/peakLayer3/geometry/setYLength          10.0 mm 
/gate/peakLayer3/geometry/setZLength          {peakzlength3_um} um 
/gate/peakLayer3/placement/setTranslation     -5 -5 {peakztrans3_mm} mm
/gate/peakLayer3/vis/setVisible               1 
/gate/peakLayer3/vis/setColor                 red
/gate/peakLayer3/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer4 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer4/setMaterial                  {peak_material} 
/gate/peakLayer4/geometry/setXLength          10.0 mm 
/gate/peakLayer4/geometry/setYLength          10.0 mm 
/gate/peakLayer4/geometry/setZLength          {peakzlength4_um} um 
/gate/peakLayer4/placement/setTranslation     5 -5 {peakztrans4_mm} mm
/gate/peakLayer4/vis/setVisible               1 
/gate/peakLayer4/vis/setColor                 red
/gate/peakLayer4/vis/forceSolid

# =====================================================
# PHYSICS
# =====================================================

/gate/physics/addPhysicsList emstandard_opt4

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      epi 0.0001 mm 
/gate/physics/Electron/SetCutInRegion   epi 0.0001 mm
/gate/physics/Positron/SetCutInRegion   epi 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      bulk 0.0001 mm
/gate/physics/Electron/SetCutInRegion   bulk 0.0001 mm
/gate/physics/Positron/SetCutInRegion   bulk 0.0001 mm

#/gate/physics/Gamma/SetCutInRegion      peakLayer1 0.0001 mm #0.0001
#/gate/physics/Electron/SetCutInRegion   peakLayer1 0.0001 mm
#/gate/physics/Positron/SetCutInRegion   peakLayer1 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer2 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer2 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer2 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer3 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer3 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer3 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer4 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer4 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer4 0.0001 mm

#=====================================================
# DETECTORS
#=====================================================

## 
## Dose output electron
## 
/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  {pathOutputDose}/Epi-00-{peakzlength2_um}-{peakzlength3_um}-{peakzlength4_um}_peakum-{peak_material}-0.908xSeaLevel-{id}.root
/gate/actor/doseDistribution/attachTo              epi
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setSize               50 50 0.010 mm
/gate/actor/doseDistribution/setResolution         1000 1000 1	 #for 60 micron pixel x4
/gate/actor/doseDistribution/enableNumberOfHits    true
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep false
/gate/actor/doseDistribution/enableSquaredEdep     true
/gate/actor/doseDistribution/enableDose            false
/gate/actor/doseDistribution/enableUncertaintyDose false


/gate/actor/addActor   KillActor                         Kill_BP 
/gate/actor/Kill_BP/attachTo                             Kill_BackPlane 

/gate/actor/addActor   KillActor                         Kill_FP 
/gate/actor/Kill_FP/attachTo                             Kill_FrontPlane 

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize
# /process/em/setBiasingFactor compt 100 True

# /process/em/setSecBiasing compt peakLayer1 100 1000 MeV
# /particle/process/dump

#=====================================================
# BEAMS
#=====================================================

# Read from Phase Space files. Here we indicate the type of particle
# (gamma) because this information is not stored in the PhS to gain
# space. Moreover, we set 'useRandomSymmetry' to generate more
# particle than the number of particle in the PhS, using a Z axis
# symmetry.

#/gate/source/addSource                         beam_g phaseSpace
#/gate/source/beam_g/addPhaseSpaceFile          {inputPhaseSpaceFile}
#{inputParticleType}
#/gate/source/beam_g/attachTo                   PhS_Plane_Two
#/gate/source/beam_g/useRandomSymmetry          true

/gate/source/addSource mybeam gps 
/gate/source/mybeam/gps/particle e- 
/gate/source/mybeam/gps/pos/centre 0 0 471 mm 
/gate/source/mybeam/gps/direction 0 0 -1 
/gate/source/mybeam/gps/type Plane 
/gate/source/mybeam/gps/shape Square 
/gate/source/mybeam/gps/halfx 2 cm 
/gate/source/mybeam/gps/halfy 2 cm 
/gate/source/mybeam/gps/ene/type Arb 
/gate/source/mybeam/gps/hist/type arb 
/gate/source/mybeam/gps/hist/point 0.021810742814680754 16101.0
/gate/source/mybeam/gps/hist/point 0.06522577589705178 21445.0
/gate/source/mybeam/gps/hist/point 0.10864080897942281 25799.0
/gate/source/mybeam/gps/hist/point 0.15205584206179384 27492.0
/gate/source/mybeam/gps/hist/point 0.1954708751441649 28348.0
/gate/source/mybeam/gps/hist/point 0.2388859082265359 27645.0
/gate/source/mybeam/gps/hist/point 0.2823009413089069 26884.0
/gate/source/mybeam/gps/hist/point 0.325715974391278 25933.0
/gate/source/mybeam/gps/hist/point 0.369131007473649 24769.0
/gate/source/mybeam/gps/hist/point 0.41254604055602007 24064.0
/gate/source/mybeam/gps/hist/point 0.4559610736383911 22118.0
/gate/source/mybeam/gps/hist/point 0.49937610672076205 20986.0
/gate/source/mybeam/gps/hist/point 0.5427911398031331 20252.0
/gate/source/mybeam/gps/hist/point 0.5862061728855041 19796.0
/gate/source/mybeam/gps/hist/point 0.6296212059678752 18866.0
/gate/source/mybeam/gps/hist/point 0.6730362390502462 18079.0
/gate/source/mybeam/gps/hist/point 0.7164512721326173 17298.0
/gate/source/mybeam/gps/hist/point 0.7598663052149883 16383.0
/gate/source/mybeam/gps/hist/point 0.8032813382973594 15963.0
/gate/source/mybeam/gps/hist/point 0.8466963713797304 15313.0
/gate/source/mybeam/gps/hist/point 0.8901114044621015 14859.0
/gate/source/mybeam/gps/hist/point 0.9335264375444724 14302.0
/gate/source/mybeam/gps/hist/point 0.9769414706268434 13771.0
/gate/source/mybeam/gps/hist/point 1.0203565037092144 13177.0
/gate/source/mybeam/gps/hist/point 1.0637715367915854 12849.0
/gate/source/mybeam/gps/hist/point 1.1071865698739565 12423.0
/gate/source/mybeam/gps/hist/point 1.1506016029563275 11932.0
/gate/source/mybeam/gps/hist/point 1.1940166360386986 11808.0
/gate/source/mybeam/gps/hist/point 1.2374316691210696 11256.0
/gate/source/mybeam/gps/hist/point 1.2808467022034407 10727.0
/gate/source/mybeam/gps/hist/point 1.3242617352858117 10423.0
/gate/source/mybeam/gps/hist/point 1.3676767683681827 10108.0
/gate/source/mybeam/gps/hist/point 1.4110918014505538 9735.0
/gate/source/mybeam/gps/hist/point 1.4545068345329248 9620.0
/gate/source/mybeam/gps/hist/point 1.4979218676152959 9218.0
/gate/source/mybeam/gps/hist/point 1.541336900697667 8850.0
/gate/source/mybeam/gps/hist/point 1.584751933780038 8692.0
/gate/source/mybeam/gps/hist/point 1.628166966862409 8288.0
/gate/source/mybeam/gps/hist/point 1.67158199994478 7977.0
/gate/source/mybeam/gps/hist/point 1.7149970330271511 7766.0
/gate/source/mybeam/gps/hist/point 1.7584120661095222 7594.0
/gate/source/mybeam/gps/hist/point 1.801827099191893 7399.0
/gate/source/mybeam/gps/hist/point 1.845242132274264 7173.0
/gate/source/mybeam/gps/hist/point 1.888657165356635 6991.0
/gate/source/mybeam/gps/hist/point 1.9320721984390061 6755.0
/gate/source/mybeam/gps/hist/point 1.9754872315213772 6308.0
/gate/source/mybeam/gps/hist/point 2.0189022646037484 6184.0
/gate/source/mybeam/gps/hist/point 2.0623172976861195 5965.0
/gate/source/mybeam/gps/hist/point 2.10573233076849 5779.0
/gate/source/mybeam/gps/hist/point 2.149147363850861 5653.0
/gate/source/mybeam/gps/hist/point 2.192562396933232 5522.0
/gate/source/mybeam/gps/hist/point 2.2359774300156032 5415.0
/gate/source/mybeam/gps/hist/point 2.2793924630979743 5090.0
/gate/source/mybeam/gps/hist/point 2.3228074961803453 5100.0
/gate/source/mybeam/gps/hist/point 2.3662225292627164 4918.0
/gate/source/mybeam/gps/hist/point 2.4096375623450874 4740.0
/gate/source/mybeam/gps/hist/point 2.4530525954274585 4542.0
/gate/source/mybeam/gps/hist/point 2.4964676285098295 4500.0
/gate/source/mybeam/gps/hist/point 2.5398826615922006 4240.0
/gate/source/mybeam/gps/hist/point 2.5832976946745716 4033.0
/gate/source/mybeam/gps/hist/point 2.6267127277569426 3941.0
/gate/source/mybeam/gps/hist/point 2.6701277608393137 3865.0
/gate/source/mybeam/gps/hist/point 2.7135427939216847 3713.0
/gate/source/mybeam/gps/hist/point 2.756957827004056 3641.0
/gate/source/mybeam/gps/hist/point 2.800372860086427 3529.0
/gate/source/mybeam/gps/hist/point 2.843787893168798 3371.0
/gate/source/mybeam/gps/hist/point 2.887202926251169 3338.0
/gate/source/mybeam/gps/hist/point 2.93061795933354 3114.0
/gate/source/mybeam/gps/hist/point 2.974032992415911 3001.0
/gate/source/mybeam/gps/hist/point 3.017448025498282 2892.0
/gate/source/mybeam/gps/hist/point 3.060863058580653 2768.0
/gate/source/mybeam/gps/hist/point 3.104278091663024 2770.0
/gate/source/mybeam/gps/hist/point 3.147693124745395 2637.0
/gate/source/mybeam/gps/hist/point 3.1911081578277662 2677.0
/gate/source/mybeam/gps/hist/point 3.2345231909101373 2452.0
/gate/source/mybeam/gps/hist/point 3.2779382239925083 2372.0
/gate/source/mybeam/gps/hist/point 3.3213532570748794 2268.0
/gate/source/mybeam/gps/hist/point 3.3647682901572504 2228.0
/gate/source/mybeam/gps/hist/point 3.4081833232396215 2182.0
/gate/source/mybeam/gps/hist/point 3.4515983563219925 2155.0
/gate/source/mybeam/gps/hist/point 3.495013389404363 1958.0
/gate/source/mybeam/gps/hist/point 3.538428422486734 1893.0
/gate/source/mybeam/gps/hist/point 3.581843455569105 1836.0
/gate/source/mybeam/gps/hist/point 3.6252584886514763 1739.0
/gate/source/mybeam/gps/hist/point 3.6686735217338473 1610.0
/gate/source/mybeam/gps/hist/point 3.7120885548162184 1565.0
/gate/source/mybeam/gps/hist/point 3.7555035878985894 1566.0
/gate/source/mybeam/gps/hist/point 3.7989186209809604 1498.0
/gate/source/mybeam/gps/hist/point 3.8423336540633315 1413.0
/gate/source/mybeam/gps/hist/point 3.8857486871457025 1400.0
/gate/source/mybeam/gps/hist/point 3.9291637202280736 1325.0
/gate/source/mybeam/gps/hist/point 3.9725787533104446 1267.0
/gate/source/mybeam/gps/hist/point 4.015993786392816 1197.0
/gate/source/mybeam/gps/hist/point 4.059408819475188 1190.0
/gate/source/mybeam/gps/hist/point 4.102823852557558 1070.0
/gate/source/mybeam/gps/hist/point 4.146238885639929 1026.0
/gate/source/mybeam/gps/hist/point 4.1896539187223 1013.0
/gate/source/mybeam/gps/hist/point 4.23306895180467 951.0
/gate/source/mybeam/gps/hist/point 4.276483984887042 875.0
/gate/source/mybeam/gps/hist/point 4.319899017969412 875.0
/gate/source/mybeam/gps/hist/point 4.363314051051784 810.0
/gate/source/mybeam/gps/hist/point 4.406729084134154 809.0
/gate/source/mybeam/gps/hist/point 4.450144117216526 743.0
/gate/source/mybeam/gps/hist/point 4.493559150298896 715.0
/gate/source/mybeam/gps/hist/point 4.536974183381268 661.0
/gate/source/mybeam/gps/hist/point 4.580389216463638 641.0
/gate/source/mybeam/gps/hist/point 4.62380424954601 595.0
/gate/source/mybeam/gps/hist/point 4.6672192826283805 560.0
/gate/source/mybeam/gps/hist/point 4.710634315710752 561.0
/gate/source/mybeam/gps/hist/point 4.754049348793123 537.0
/gate/source/mybeam/gps/hist/point 4.7974643818754945 508.0
/gate/source/mybeam/gps/hist/point 4.840879414957865 461.0
/gate/source/mybeam/gps/hist/point 4.884294448040237 391.0
/gate/source/mybeam/gps/hist/point 4.927709481122607 439.0
/gate/source/mybeam/gps/hist/point 4.971124514204979 399.0
/gate/source/mybeam/gps/hist/point 5.014539547287349 337.0
/gate/source/mybeam/gps/hist/point 5.057954580369721 342.0
/gate/source/mybeam/gps/hist/point 5.101369613452091 317.0
/gate/source/mybeam/gps/hist/point 5.144784646534463 295.0
/gate/source/mybeam/gps/hist/point 5.188199679616833 274.0
/gate/source/mybeam/gps/hist/point 5.231614712699205 251.0
/gate/source/mybeam/gps/hist/point 5.275029745781575 211.0
/gate/source/mybeam/gps/hist/point 5.318444778863947 217.0
/gate/source/mybeam/gps/hist/point 5.361859811946317 224.0
/gate/source/mybeam/gps/hist/point 5.405274845028689 177.0
/gate/source/mybeam/gps/hist/point 5.448689878111059 192.0
/gate/source/mybeam/gps/hist/point 5.492104911193431 146.0
/gate/source/mybeam/gps/hist/point 5.535519944275801 134.0
/gate/source/mybeam/gps/hist/point 5.578934977358173 139.0
/gate/source/mybeam/gps/hist/point 5.6223500104405435 112.0
/gate/source/mybeam/gps/hist/point 5.665765043522915 131.0
/gate/source/mybeam/gps/hist/point 5.709180076605286 107.0
/gate/source/mybeam/gps/hist/point 5.7525951096876575 88.0
/gate/source/mybeam/gps/hist/point 5.796010142770028 84.0
/gate/source/mybeam/gps/hist/point 5.8394251758524 66.0
/gate/source/mybeam/gps/hist/point 5.88284020893477 63.0
/gate/source/mybeam/gps/hist/point 5.926255242017142 56.0
/gate/source/mybeam/gps/hist/point 5.969670275099512 61.0
/gate/source/mybeam/gps/hist/point 6.013085308181884 40.0
/gate/source/mybeam/gps/hist/point 6.056500341264254 25.0
/gate/source/mybeam/gps/hist/point 6.099915374346626 21.0
/gate/source/mybeam/gps/hist/point 6.143330407428996 22.0
/gate/source/mybeam/gps/hist/point 6.186745440511368 17.0
/gate/source/mybeam/gps/hist/point 6.230160473593738 10.0
/gate/source/mybeam/gps/hist/point 6.27357550667611 4.0
/gate/source/mybeam/gps/hist/point 6.31699053975848 9.0
/gate/source/mybeam/gps/hist/point 6.360405572840852 4.0
/gate/source/mybeam/gps/hist/point 6.403820605923222 2.0
/gate/source/mybeam/gps/hist/point 6.447235639005594 4.0
/gate/source/mybeam/gps/hist/point 6.490650672087964 2.0
/gate/source/mybeam/gps/hist/inter Log

#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed {seed}
#1234567890
/gate/application/noGlobalOutput

#/tracking/verbose 2

/gate/application/setTotalNumberOfPrimaries {primaries}
#1000
/gate/application/start
