# INPUTS
# pathOutputDose
# id
# seed 
# primaries
# peakzlength_um
# peakztrans_mm
# peakzlength2_um
# peakztrans2_mm
# peakzlength3_um
# peakztrans3_mm
# peakzlength4_um
# peakztrans4_mm
# peak_material

# Gate /home/as17540/linac/mac/Main_PhS2_Elec_Sensor_0.9xSeaLevel.mac -a '[id,$PBS_ARRAY_INDEX] [peakzlength_um,10] [peakztrans_mm,-5.495] [peakzlength2_um,30] [peakztrans2_mm,-5.485] [peakzlength3_um,50] [peakztrans3_mm,-5.475] [peakzlength4_um,70] [peakztrans4_mm,-5.465] [peak_material,Copper] [seed,$RANDOM$RANDOM$RANDOM] [primaries,11273900] [pathOutputDose,/work/as17540/PhaseSpaces/PhS3_Sensor_10x10_Elec/]'

#=====================================================
# VISUALISATION
#=====================================================

#/control/execute mac/visu.mac

# =====================================================
# GEOMETRY
# =====================================================

/gate/geometry/setMaterialDatabase /home/as17540/linac/data/GateMaterials_0.908xSeaLevel.db

# WORLD
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    0.3 m
/gate/world/geometry/setYLength    0.3 m
/gate/world/geometry/setZLength    1 m
/gate/world/vis/setVisible 1

/gate/world/daughters/name                   PhS_Plane_Two
/gate/world/daughters/insert                 box
/gate/PhS_Plane_Two/setMaterial              Vacuum
/gate/PhS_Plane_Two/geometry/setXLength      22 cm
/gate/PhS_Plane_Two/geometry/setYLength      22 cm
/gate/PhS_Plane_Two/geometry/setZLength      1 nm
/gate/PhS_Plane_Two/placement/setTranslation 0.0 0.0 471 mm #(-529)
/gate/PhS_Plane_Two/vis/setColor             cyan
/gate/PhS_Plane_Two/vis/setVisible           1

/gate/world/daughters/name                   Kill_BackPlane
/gate/world/daughters/insert                 box
/gate/Kill_BackPlane/setMaterial                   Air	
/gate/Kill_BackPlane/geometry/setXLength           30 cm
/gate/Kill_BackPlane/geometry/setYLength           30 cm
/gate/Kill_BackPlane/geometry/setZLength           1 nm
/gate/Kill_BackPlane/placement/setTranslation      0.0 0.0 480 mm
/gate/Kill_BackPlane/vis/setColor                  red
/gate/Kill_BackPlane/vis/setVisible                1

/gate/world/daughters/name                   Kill_FrontPlane
/gate/world/daughters/insert                 box
/gate/Kill_FrontPlane/setMaterial                   Air	
/gate/Kill_FrontPlane/geometry/setXLength           30 cm
/gate/Kill_FrontPlane/geometry/setYLength           30 cm
/gate/Kill_FrontPlane/geometry/setZLength           1 nm
/gate/Kill_FrontPlane/placement/setTranslation      0.0 0.0 445 mm
/gate/Kill_FrontPlane/vis/setColor                  red
/gate/Kill_FrontPlane/vis/setVisible                1

/gate/world/daughters/name         epi
/gate/world/daughters/insert       box
/gate/epi/setMaterial                  Silicon
/gate/epi/geometry/setXLength          180.0 mm
/gate/epi/geometry/setYLength          180.0 mm
/gate/epi/geometry/setZLength          0.01 mm
/gate/epi/placement/setTranslation     0 0 449.995 mm
/gate/epi/vis/setVisible               1
/gate/epi/vis/setColor                 yellow
/gate/epi/vis/forceSolid

/gate/world/daughters/name         bulk
/gate/world/daughters/insert       box
/gate/bulk/setMaterial                  Silicon
/gate/bulk/geometry/setXLength          180.0 mm
/gate/bulk/geometry/setYLength          180.0 mm
/gate/bulk/geometry/setZLength          0.6 mm
/gate/bulk/placement/setTranslation     0 0 449.69 mm
/gate/bulk/vis/setVisible               1
/gate/bulk/vis/setColor                 red

/gate/world/daughters/name         peak_air_box 
/gate/world/daughters/insert       box 
/gate/peak_air_box/setMaterial                  Air 
/gate/peak_air_box/geometry/setXLength          200.0 mm 
/gate/peak_air_box/geometry/setYLength          200.0 mm 
/gate/peak_air_box/geometry/setZLength          11 mm 
/gate/peak_air_box/placement/setTranslation     0 0 455.5 mm
/gate/peak_air_box/vis/setVisible               1 
/gate/peak_air_box/vis/setColor                 green
/gate/peak_air_box/vis/forceWireframe

/gate/peak_air_box/daughters/name         peakLayer1 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer1/setMaterial                  {peak_material} 
/gate/peakLayer1/geometry/setXLength          10.0 mm 
/gate/peakLayer1/geometry/setYLength          10.0 mm 
/gate/peakLayer1/geometry/setZLength          {peakzlength_um} um 
/gate/peakLayer1/placement/setTranslation     -5 5 {peakztrans_mm} mm
/gate/peakLayer1/vis/setVisible               1 
/gate/peakLayer1/vis/setColor                 grey
/gate/peakLayer1/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer2 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer2/setMaterial                  {peak_material} 
/gate/peakLayer2/geometry/setXLength          10.0 mm 
/gate/peakLayer2/geometry/setYLength          10.0 mm 
/gate/peakLayer2/geometry/setZLength          {peakzlength2_um} um 
/gate/peakLayer2/placement/setTranslation     5 5 {peakztrans2_mm} mm
/gate/peakLayer2/vis/setVisible               1 
/gate/peakLayer2/vis/setColor                 red
/gate/peakLayer2/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer3 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer3/setMaterial                  {peak_material} 
/gate/peakLayer3/geometry/setXLength          10.0 mm 
/gate/peakLayer3/geometry/setYLength          10.0 mm 
/gate/peakLayer3/geometry/setZLength          {peakzlength3_um} um 
/gate/peakLayer3/placement/setTranslation     -5 -5 {peakztrans3_mm} mm
/gate/peakLayer3/vis/setVisible               1 
/gate/peakLayer3/vis/setColor                 red
/gate/peakLayer3/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer4 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer4/setMaterial                  {peak_material} 
/gate/peakLayer4/geometry/setXLength          10.0 mm 
/gate/peakLayer4/geometry/setYLength          10.0 mm 
/gate/peakLayer4/geometry/setZLength          {peakzlength4_um} um 
/gate/peakLayer4/placement/setTranslation     5 -5 {peakztrans4_mm} mm
/gate/peakLayer4/vis/setVisible               1 
/gate/peakLayer4/vis/setColor                 red
/gate/peakLayer4/vis/forceSolid

# =====================================================
# PHYSICS
# =====================================================

/gate/physics/addPhysicsList emstandard_opt4

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      epi 0.0001 mm 
/gate/physics/Electron/SetCutInRegion   epi 0.0001 mm
/gate/physics/Positron/SetCutInRegion   epi 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      bulk 0.0001 mm
/gate/physics/Electron/SetCutInRegion   bulk 0.0001 mm
/gate/physics/Positron/SetCutInRegion   bulk 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer1 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer1 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer1 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer2 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer2 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer2 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer3 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer3 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer3 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer4 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer4 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer4 0.0001 mm

#=====================================================
# DETECTORS
#=====================================================

## 
## Dose output electron
## 
/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  {pathOutputDose}/Epi-{peakzlength_um}-{peakzlength2_um}-{peakzlength3_um}-{peakzlength4_um}_peakum-{peak_material}-0.908xSeaLevel-{id}.root
/gate/actor/doseDistribution/attachTo              epi
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setSize               50 50 0.010 mm
/gate/actor/doseDistribution/setResolution         1000 1000 1	 #for 60 micron pixel x4
/gate/actor/doseDistribution/enableNumberOfHits    true
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep false
/gate/actor/doseDistribution/enableSquaredEdep     true
/gate/actor/doseDistribution/enableDose            false
/gate/actor/doseDistribution/enableUncertaintyDose false


/gate/actor/addActor   KillActor                         Kill_BP 
/gate/actor/Kill_BP/attachTo                             Kill_BackPlane 

/gate/actor/addActor   KillActor                         Kill_FP 
/gate/actor/Kill_FP/attachTo                             Kill_FrontPlane 

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize
# /process/em/setBiasingFactor compt 100 True

# /process/em/setSecBiasing compt peakLayer1 100 1000 MeV
# /particle/process/dump

#=====================================================
# BEAMS
#=====================================================

# Read from Phase Space files. Here we indicate the type of particle
# (gamma) because this information is not stored in the PhS to gain
# space. Moreover, we set 'useRandomSymmetry' to generate more
# particle than the number of particle in the PhS, using a Z axis
# symmetry.

#/gate/source/addSource                         beam_g phaseSpace
#/gate/source/beam_g/addPhaseSpaceFile          {inputPhaseSpaceFile}
#{inputParticleType}
#/gate/source/beam_g/attachTo                   PhS_Plane_Two
#/gate/source/beam_g/useRandomSymmetry          true

/gate/source/addSource mybeam gps 
/gate/source/mybeam/gps/particle e- 
/gate/source/mybeam/gps/pos/centre 0 0 471 mm 
/gate/source/mybeam/gps/direction 0 0 -1 
/gate/source/mybeam/gps/type Plane 
/gate/source/mybeam/gps/shape Square 
/gate/source/mybeam/gps/halfx 2 cm 
/gate/source/mybeam/gps/halfy 2 cm 
/gate/source/mybeam/gps/ene/type Arb 
/gate/source/mybeam/gps/hist/type arb 
/gate/source/mybeam/gps/hist/point 0.022178555758922205 16260.0
/gate/source/mybeam/gps/hist/point 0.06633507744903909 21726.0
/gate/source/mybeam/gps/hist/point 0.11049159913915597 26320.0
/gate/source/mybeam/gps/hist/point 0.15464812082927287 27967.0
/gate/source/mybeam/gps/hist/point 0.19880464251938973 28464.0
/gate/source/mybeam/gps/hist/point 0.24296116420950664 28011.0
/gate/source/mybeam/gps/hist/point 0.2871176858996235 27158.0
/gate/source/mybeam/gps/hist/point 0.3312742075897404 25928.0
/gate/source/mybeam/gps/hist/point 0.37543072927985727 24878.0
/gate/source/mybeam/gps/hist/point 0.4195872509699742 23660.0
/gate/source/mybeam/gps/hist/point 0.46374377266009104 22549.0
/gate/source/mybeam/gps/hist/point 0.507900294350208 21631.0
/gate/source/mybeam/gps/hist/point 0.5520568160403247 20488.0
/gate/source/mybeam/gps/hist/point 0.5962133377304417 19599.0
/gate/source/mybeam/gps/hist/point 0.6403698594205587 18819.0
/gate/source/mybeam/gps/hist/point 0.6845263811106754 18202.0
/gate/source/mybeam/gps/hist/point 0.7286829028007924 17391.0
/gate/source/mybeam/gps/hist/point 0.7728394244909091 16917.0
/gate/source/mybeam/gps/hist/point 0.8169959461810261 16123.0
/gate/source/mybeam/gps/hist/point 0.8611524678711431 15426.0
/gate/source/mybeam/gps/hist/point 0.9053089895612598 14844.0
/gate/source/mybeam/gps/hist/point 0.9494655112513768 14366.0
/gate/source/mybeam/gps/hist/point 0.9936220329414936 13772.0
/gate/source/mybeam/gps/hist/point 1.0377785546316105 13320.0
/gate/source/mybeam/gps/hist/point 1.0819350763217275 12831.0
/gate/source/mybeam/gps/hist/point 1.1260915980118442 12259.0
/gate/source/mybeam/gps/hist/point 1.1702481197019612 12073.0
/gate/source/mybeam/gps/hist/point 1.2144046413920782 11561.0
/gate/source/mybeam/gps/hist/point 1.2585611630821951 11147.0
/gate/source/mybeam/gps/hist/point 1.3027176847723119 10693.0
/gate/source/mybeam/gps/hist/point 1.3468742064624286 10484.0
/gate/source/mybeam/gps/hist/point 1.3910307281525456 10270.0
/gate/source/mybeam/gps/hist/point 1.4351872498426625 9748.0
/gate/source/mybeam/gps/hist/point 1.4793437715327795 9380.0
/gate/source/mybeam/gps/hist/point 1.5235002932228963 9099.0
/gate/source/mybeam/gps/hist/point 1.567656814913013 8866.0
/gate/source/mybeam/gps/hist/point 1.61181333660313 8550.0
/gate/source/mybeam/gps/hist/point 1.655969858293247 8236.0
/gate/source/mybeam/gps/hist/point 1.700126379983364 8192.0
/gate/source/mybeam/gps/hist/point 1.7442829016734807 7765.0
/gate/source/mybeam/gps/hist/point 1.7884394233635976 7363.0
/gate/source/mybeam/gps/hist/point 1.8325959450537144 7368.0
/gate/source/mybeam/gps/hist/point 1.8767524667438313 7008.0
/gate/source/mybeam/gps/hist/point 1.9209089884339483 6770.0
/gate/source/mybeam/gps/hist/point 1.9650655101240653 6647.0
/gate/source/mybeam/gps/hist/point 2.009222031814182 6369.0
/gate/source/mybeam/gps/hist/point 2.0533785535042988 6234.0
/gate/source/mybeam/gps/hist/point 2.0975350751944157 6060.0
/gate/source/mybeam/gps/hist/point 2.1416915968845327 5949.0
/gate/source/mybeam/gps/hist/point 2.1858481185746497 5701.0
/gate/source/mybeam/gps/hist/point 2.2300046402647666 5491.0
/gate/source/mybeam/gps/hist/point 2.274161161954883 5327.0
/gate/source/mybeam/gps/hist/point 2.318317683645 5166.0
/gate/source/mybeam/gps/hist/point 2.362474205335117 4878.0
/gate/source/mybeam/gps/hist/point 2.406630727025234 4674.0
/gate/source/mybeam/gps/hist/point 2.450787248715351 4626.0
/gate/source/mybeam/gps/hist/point 2.4949437704054676 4424.0
/gate/source/mybeam/gps/hist/point 2.5391002920955845 4308.0
/gate/source/mybeam/gps/hist/point 2.5832568137857015 4225.0
/gate/source/mybeam/gps/hist/point 2.6274133354758185 3985.0
/gate/source/mybeam/gps/hist/point 2.6715698571659354 3993.0
/gate/source/mybeam/gps/hist/point 2.7157263788560524 3655.0
/gate/source/mybeam/gps/hist/point 2.759882900546169 3607.0
/gate/source/mybeam/gps/hist/point 2.804039422236286 3570.0
/gate/source/mybeam/gps/hist/point 2.848195943926403 3385.0
/gate/source/mybeam/gps/hist/point 2.89235246561652 3236.0
/gate/source/mybeam/gps/hist/point 2.9365089873066363 3076.0
/gate/source/mybeam/gps/hist/point 2.9806655089967533 3104.0
/gate/source/mybeam/gps/hist/point 3.0248220306868703 2981.0
/gate/source/mybeam/gps/hist/point 3.0689785523769872 2926.0
/gate/source/mybeam/gps/hist/point 3.113135074067104 2701.0
/gate/source/mybeam/gps/hist/point 3.157291595757221 2675.0
/gate/source/mybeam/gps/hist/point 3.2014481174473377 2577.0
/gate/source/mybeam/gps/hist/point 3.2456046391374547 2397.0
/gate/source/mybeam/gps/hist/point 3.2897611608275716 2367.0
/gate/source/mybeam/gps/hist/point 3.3339176825176886 2331.0
/gate/source/mybeam/gps/hist/point 3.3780742042078056 2153.0
/gate/source/mybeam/gps/hist/point 3.422230725897922 2037.0
/gate/source/mybeam/gps/hist/point 3.466387247588039 2095.0
/gate/source/mybeam/gps/hist/point 3.510543769278156 1927.0
/gate/source/mybeam/gps/hist/point 3.554700290968273 1901.0
/gate/source/mybeam/gps/hist/point 3.59885681265839 1901.0
/gate/source/mybeam/gps/hist/point 3.643013334348507 1732.0
/gate/source/mybeam/gps/hist/point 3.6871698560386235 1679.0
/gate/source/mybeam/gps/hist/point 3.7313263777287404 1645.0
/gate/source/mybeam/gps/hist/point 3.7754828994188574 1545.0
/gate/source/mybeam/gps/hist/point 3.8196394211089744 1462.0
/gate/source/mybeam/gps/hist/point 3.8637959427990913 1372.0
/gate/source/mybeam/gps/hist/point 3.907952464489208 1378.0
/gate/source/mybeam/gps/hist/point 3.952108986179325 1309.0
/gate/source/mybeam/gps/hist/point 3.996265507869442 1198.0
/gate/source/mybeam/gps/hist/point 4.040422029559558 1202.0
/gate/source/mybeam/gps/hist/point 4.084578551249676 1171.0
/gate/source/mybeam/gps/hist/point 4.128735072939792 1115.0
/gate/source/mybeam/gps/hist/point 4.17289159462991 1043.0
/gate/source/mybeam/gps/hist/point 4.217048116320026 1017.0
/gate/source/mybeam/gps/hist/point 4.261204638010144 938.0
/gate/source/mybeam/gps/hist/point 4.30536115970026 903.0
/gate/source/mybeam/gps/hist/point 4.3495176813903775 898.0
/gate/source/mybeam/gps/hist/point 4.393674203080494 794.0
/gate/source/mybeam/gps/hist/point 4.4378307247706115 756.0
/gate/source/mybeam/gps/hist/point 4.4819872464607275 729.0
/gate/source/mybeam/gps/hist/point 4.526143768150844 727.0
/gate/source/mybeam/gps/hist/point 4.5703002898409615 640.0
/gate/source/mybeam/gps/hist/point 4.614456811531078 642.0
/gate/source/mybeam/gps/hist/point 4.658613333221195 576.0
/gate/source/mybeam/gps/hist/point 4.7027698549113115 588.0
/gate/source/mybeam/gps/hist/point 4.746926376601429 519.0
/gate/source/mybeam/gps/hist/point 4.791082898291545 510.0
/gate/source/mybeam/gps/hist/point 4.835239419981663 461.0
/gate/source/mybeam/gps/hist/point 4.879395941671779 405.0
/gate/source/mybeam/gps/hist/point 4.923552463361897 397.0
/gate/source/mybeam/gps/hist/point 4.967708985052013 377.0
/gate/source/mybeam/gps/hist/point 5.011865506742129 358.0
/gate/source/mybeam/gps/hist/point 5.056022028432247 318.0
/gate/source/mybeam/gps/hist/point 5.100178550122363 308.0
/gate/source/mybeam/gps/hist/point 5.144335071812481 291.0
/gate/source/mybeam/gps/hist/point 5.188491593502597 272.0
/gate/source/mybeam/gps/hist/point 5.232648115192715 257.0
/gate/source/mybeam/gps/hist/point 5.276804636882831 245.0
/gate/source/mybeam/gps/hist/point 5.320961158572949 231.0
/gate/source/mybeam/gps/hist/point 5.365117680263065 208.0
/gate/source/mybeam/gps/hist/point 5.409274201953182 208.0
/gate/source/mybeam/gps/hist/point 5.453430723643299 181.0
/gate/source/mybeam/gps/hist/point 5.497587245333415 194.0
/gate/source/mybeam/gps/hist/point 5.541743767023533 155.0
/gate/source/mybeam/gps/hist/point 5.585900288713649 150.0
/gate/source/mybeam/gps/hist/point 5.630056810403767 134.0
/gate/source/mybeam/gps/hist/point 5.674213332093883 106.0
/gate/source/mybeam/gps/hist/point 5.718369853784001 94.0
/gate/source/mybeam/gps/hist/point 5.762526375474117 83.0
/gate/source/mybeam/gps/hist/point 5.806682897164235 65.0
/gate/source/mybeam/gps/hist/point 5.850839418854351 69.0
/gate/source/mybeam/gps/hist/point 5.894995940544468 77.0
/gate/source/mybeam/gps/hist/point 5.939152462234585 54.0
/gate/source/mybeam/gps/hist/point 5.983308983924701 47.0
/gate/source/mybeam/gps/hist/point 6.027465505614819 44.0
/gate/source/mybeam/gps/hist/point 6.071622027304935 35.0
/gate/source/mybeam/gps/hist/point 6.115778548995053 26.0
/gate/source/mybeam/gps/hist/point 6.159935070685169 22.0
/gate/source/mybeam/gps/hist/point 6.204091592375287 18.0
/gate/source/mybeam/gps/hist/point 6.248248114065403 15.0
/gate/source/mybeam/gps/hist/point 6.292404635755521 7.0
/gate/source/mybeam/gps/hist/point 6.336561157445637 6.0
/gate/source/mybeam/gps/hist/point 6.380717679135753 3.0
/gate/source/mybeam/gps/hist/point 6.424874200825871 5.0
/gate/source/mybeam/gps/hist/point 6.469030722515987 1.0
/gate/source/mybeam/gps/hist/point 6.5131872442061045 2.0
/gate/source/mybeam/gps/hist/point 6.557343765896221 0.0
/gate/source/mybeam/gps/hist/point 6.6015002875863384 2.0
/gate/source/mybeam/gps/hist/inter Log

#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed {seed}
#1234567890
/gate/application/noGlobalOutput

#/tracking/verbose 2

/gate/application/setTotalNumberOfPrimaries {primaries}
#1000
/gate/application/start
