# INPUTS
# pathOutputDose
# id
# seed 
# primaries
# peakzlength2_um
# peakztrans2_mm
# peakzlength3_um
# peakztrans3_mm
# peakzlength4_um
# peakztrans4_mm
# peak_material

# Gate /home/as17540/linac/mac/Main_PhS2_Elec_Sensor_0.85xSeaLevel_0.mac -a '[id,$PBS_ARRAY_INDEX] [peakzlength2_um,30] [peakztrans2_mm,-5.485] [peakzlength3_um,50] [peakztrans3_mm,-5.475] [peakzlength4_um,70] [peakztrans4_mm,-5.465] [peak_material,Copper] [seed,$RANDOM$RANDOM$RANDOM] [primaries,10783000] [pathOutputDose,/work/as17540/PhaseSpaces/PhS3_Sensor_10x10_Elec/]'

#=====================================================
# VISUALISATION
#=====================================================

#/control/execute mac/visu.mac

# =====================================================
# GEOMETRY
# =====================================================

/gate/geometry/setMaterialDatabase /home/as17540/linac/data/GateMaterials_0.85xSeaLevel.db

# WORLD
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    0.3 m
/gate/world/geometry/setYLength    0.3 m
/gate/world/geometry/setZLength    1 m
/gate/world/vis/setVisible 1

/gate/world/daughters/name                   PhS_Plane_Two
/gate/world/daughters/insert                 box
/gate/PhS_Plane_Two/setMaterial              Vacuum
/gate/PhS_Plane_Two/geometry/setXLength      22 cm
/gate/PhS_Plane_Two/geometry/setYLength      22 cm
/gate/PhS_Plane_Two/geometry/setZLength      1 nm
/gate/PhS_Plane_Two/placement/setTranslation 0.0 0.0 471 mm #(-529)
/gate/PhS_Plane_Two/vis/setColor             cyan
/gate/PhS_Plane_Two/vis/setVisible           1

/gate/world/daughters/name                   Kill_BackPlane
/gate/world/daughters/insert                 box
/gate/Kill_BackPlane/setMaterial                   Air	
/gate/Kill_BackPlane/geometry/setXLength           30 cm
/gate/Kill_BackPlane/geometry/setYLength           30 cm
/gate/Kill_BackPlane/geometry/setZLength           1 nm
/gate/Kill_BackPlane/placement/setTranslation      0.0 0.0 480 mm
/gate/Kill_BackPlane/vis/setColor                  red
/gate/Kill_BackPlane/vis/setVisible                1

/gate/world/daughters/name                   Kill_FrontPlane
/gate/world/daughters/insert                 box
/gate/Kill_FrontPlane/setMaterial                   Air	
/gate/Kill_FrontPlane/geometry/setXLength           30 cm
/gate/Kill_FrontPlane/geometry/setYLength           30 cm
/gate/Kill_FrontPlane/geometry/setZLength           1 nm
/gate/Kill_FrontPlane/placement/setTranslation      0.0 0.0 445 mm
/gate/Kill_FrontPlane/vis/setColor                  red
/gate/Kill_FrontPlane/vis/setVisible                1

/gate/world/daughters/name         epi
/gate/world/daughters/insert       box
/gate/epi/setMaterial                  Silicon
/gate/epi/geometry/setXLength          180.0 mm
/gate/epi/geometry/setYLength          180.0 mm
/gate/epi/geometry/setZLength          0.01 mm
/gate/epi/placement/setTranslation     0 0 449.995 mm
/gate/epi/vis/setVisible               1
/gate/epi/vis/setColor                 yellow
/gate/epi/vis/forceSolid

/gate/world/daughters/name         bulk
/gate/world/daughters/insert       box
/gate/bulk/setMaterial                  Silicon
/gate/bulk/geometry/setXLength          180.0 mm
/gate/bulk/geometry/setYLength          180.0 mm
/gate/bulk/geometry/setZLength          0.6 mm
/gate/bulk/placement/setTranslation     0 0 449.69 mm
/gate/bulk/vis/setVisible               1
/gate/bulk/vis/setColor                 red

/gate/world/daughters/name         peak_air_box 
/gate/world/daughters/insert       box 
/gate/peak_air_box/setMaterial                  Air 
/gate/peak_air_box/geometry/setXLength          200.0 mm 
/gate/peak_air_box/geometry/setYLength          200.0 mm 
/gate/peak_air_box/geometry/setZLength          11 mm 
/gate/peak_air_box/placement/setTranslation     0 0 455.5 mm
/gate/peak_air_box/vis/setVisible               1 
/gate/peak_air_box/vis/setColor                 green
/gate/peak_air_box/vis/forceWireframe

#/gate/peak_air_box/daughters/name         peakLayer1 
#/gate/peak_air_box/daughters/insert       box 
#/gate/peakLayer1/setMaterial                  {peak_material} 
#/gate/peakLayer1/geometry/setXLength          10.0 mm 
#/gate/peakLayer1/geometry/setYLength          10.0 mm 
#/gate/peakLayer1/geometry/setZLength          {peakzlength_um} um 
#/gate/peakLayer1/placement/setTranslation     -5 5 {peakztrans_mm} mm
#/gate/peakLayer1/vis/setVisible               1 
#/gate/peakLayer1/vis/setColor                 grey
#/gate/peakLayer1/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer2 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer2/setMaterial                  {peak_material} 
/gate/peakLayer2/geometry/setXLength          10.0 mm 
/gate/peakLayer2/geometry/setYLength          10.0 mm 
/gate/peakLayer2/geometry/setZLength          {peakzlength2_um} um 
/gate/peakLayer2/placement/setTranslation     5 5 {peakztrans2_mm} mm
/gate/peakLayer2/vis/setVisible               1 
/gate/peakLayer2/vis/setColor                 red
/gate/peakLayer2/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer3 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer3/setMaterial                  {peak_material} 
/gate/peakLayer3/geometry/setXLength          10.0 mm 
/gate/peakLayer3/geometry/setYLength          10.0 mm 
/gate/peakLayer3/geometry/setZLength          {peakzlength3_um} um 
/gate/peakLayer3/placement/setTranslation     -5 -5 {peakztrans3_mm} mm
/gate/peakLayer3/vis/setVisible               1 
/gate/peakLayer3/vis/setColor                 red
/gate/peakLayer3/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer4 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer4/setMaterial                  {peak_material} 
/gate/peakLayer4/geometry/setXLength          10.0 mm 
/gate/peakLayer4/geometry/setYLength          10.0 mm 
/gate/peakLayer4/geometry/setZLength          {peakzlength4_um} um 
/gate/peakLayer4/placement/setTranslation     5 -5 {peakztrans4_mm} mm
/gate/peakLayer4/vis/setVisible               1 
/gate/peakLayer4/vis/setColor                 red
/gate/peakLayer4/vis/forceSolid

# =====================================================
# PHYSICS
# =====================================================

/gate/physics/addPhysicsList emstandard_opt4

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      epi 0.0001 mm 
/gate/physics/Electron/SetCutInRegion   epi 0.0001 mm
/gate/physics/Positron/SetCutInRegion   epi 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      bulk 0.0001 mm
/gate/physics/Electron/SetCutInRegion   bulk 0.0001 mm
/gate/physics/Positron/SetCutInRegion   bulk 0.0001 mm

#/gate/physics/Gamma/SetCutInRegion      peakLayer1 0.0001 mm #0.0001
#/gate/physics/Electron/SetCutInRegion   peakLayer1 0.0001 mm
#/gate/physics/Positron/SetCutInRegion   peakLayer1 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer2 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer2 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer2 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer3 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer3 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer3 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer4 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer4 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer4 0.0001 mm

#=====================================================
# DETECTORS
#=====================================================

## 
## Dose output electron
## 
/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  {pathOutputDose}/Epi-00-{peakzlength2_um}-{peakzlength3_um}-{peakzlength4_um}_peakum-{peak_material}-0.85xSeaLevel-{id}.root
/gate/actor/doseDistribution/attachTo              epi
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setSize               50 50 0.010 mm
/gate/actor/doseDistribution/setResolution         1000 1000 1	 #for 60 micron pixel x4
/gate/actor/doseDistribution/enableNumberOfHits    true
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep false
/gate/actor/doseDistribution/enableSquaredEdep     true
/gate/actor/doseDistribution/enableDose            false
/gate/actor/doseDistribution/enableUncertaintyDose false


/gate/actor/addActor   KillActor                         Kill_BP 
/gate/actor/Kill_BP/attachTo                             Kill_BackPlane 

/gate/actor/addActor   KillActor                         Kill_FP 
/gate/actor/Kill_FP/attachTo                             Kill_FrontPlane 

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize
# /process/em/setBiasingFactor compt 100 True

# /process/em/setSecBiasing compt peakLayer1 100 1000 MeV
# /particle/process/dump

#=====================================================
# BEAMS
#=====================================================

# Read from Phase Space files. Here we indicate the type of particle
# (gamma) because this information is not stored in the PhS to gain
# space. Moreover, we set 'useRandomSymmetry' to generate more
# particle than the number of particle in the PhS, using a Z axis
# symmetry.

#/gate/source/addSource                         beam_g phaseSpace
#/gate/source/beam_g/addPhaseSpaceFile          {inputPhaseSpaceFile}
#{inputParticleType}
#/gate/source/beam_g/attachTo                   PhS_Plane_Two
#/gate/source/beam_g/useRandomSymmetry          true

/gate/source/addSource mybeam gps 
/gate/source/mybeam/gps/particle e- 
/gate/source/mybeam/gps/pos/centre 0 0 471 mm 
/gate/source/mybeam/gps/direction 0 0 -1 
/gate/source/mybeam/gps/type Plane 
/gate/source/mybeam/gps/shape Square 
/gate/source/mybeam/gps/halfx 2 cm 
/gate/source/mybeam/gps/halfy 2 cm 
/gate/source/mybeam/gps/ene/type Arb 
/gate/source/mybeam/gps/hist/type arb 
/gate/source/mybeam/gps/hist/point 0.022342317102108305 16146.0
/gate/source/mybeam/gps/hist/point 0.06682260824862168 21838.0
/gate/source/mybeam/gps/hist/point 0.11130289939513507 26380.0
/gate/source/mybeam/gps/hist/point 0.15578319054164846 28169.0
/gate/source/mybeam/gps/hist/point 0.20026348168816183 28614.0
/gate/source/mybeam/gps/hist/point 0.24474377283467522 28060.0
/gate/source/mybeam/gps/hist/point 0.2892240639811886 27020.0
/gate/source/mybeam/gps/hist/point 0.333704355127702 25379.0
/gate/source/mybeam/gps/hist/point 0.37818464627421533 24601.0
/gate/source/mybeam/gps/hist/point 0.42266493742072875 23337.0
/gate/source/mybeam/gps/hist/point 0.46714522856724217 22009.0
/gate/source/mybeam/gps/hist/point 0.5116255197137555 21366.0
/gate/source/mybeam/gps/hist/point 0.5561058108602689 20042.0
/gate/source/mybeam/gps/hist/point 0.6005861020067823 19513.0
/gate/source/mybeam/gps/hist/point 0.6450663931532956 18434.0
/gate/source/mybeam/gps/hist/point 0.689546684299809 17626.0
/gate/source/mybeam/gps/hist/point 0.7340269754463224 17409.0
/gate/source/mybeam/gps/hist/point 0.7785072665928359 16749.0
/gate/source/mybeam/gps/hist/point 0.8229875577393492 15755.0
/gate/source/mybeam/gps/hist/point 0.8674678488858626 15307.0
/gate/source/mybeam/gps/hist/point 0.9119481400323759 14883.0
/gate/source/mybeam/gps/hist/point 0.9564284311788893 14324.0
/gate/source/mybeam/gps/hist/point 1.0009087223254027 13658.0
/gate/source/mybeam/gps/hist/point 1.0453890134719162 12977.0
/gate/source/mybeam/gps/hist/point 1.0898693046184293 12911.0
/gate/source/mybeam/gps/hist/point 1.134349595764943 12183.0
/gate/source/mybeam/gps/hist/point 1.1788298869114562 11991.0
/gate/source/mybeam/gps/hist/point 1.2233101780579698 11451.0
/gate/source/mybeam/gps/hist/point 1.267790469204483 11073.0
/gate/source/mybeam/gps/hist/point 1.3122707603509962 10744.0
/gate/source/mybeam/gps/hist/point 1.3567510514975099 10163.0
/gate/source/mybeam/gps/hist/point 1.401231342644023 9886.0
/gate/source/mybeam/gps/hist/point 1.4457116337905367 9669.0
/gate/source/mybeam/gps/hist/point 1.4901919249370499 9274.0
/gate/source/mybeam/gps/hist/point 1.5346722160835635 8871.0
/gate/source/mybeam/gps/hist/point 1.5791525072300767 8865.0
/gate/source/mybeam/gps/hist/point 1.62363279837659 8444.0
/gate/source/mybeam/gps/hist/point 1.6681130895231036 8055.0
/gate/source/mybeam/gps/hist/point 1.7125933806696167 7963.0
/gate/source/mybeam/gps/hist/point 1.7570736718161304 7732.0
/gate/source/mybeam/gps/hist/point 1.8015539629626436 7494.0
/gate/source/mybeam/gps/hist/point 1.846034254109157 7098.0
/gate/source/mybeam/gps/hist/point 1.8905145452556704 7016.0
/gate/source/mybeam/gps/hist/point 1.9349948364021836 6584.0
/gate/source/mybeam/gps/hist/point 1.9794751275486973 6546.0
/gate/source/mybeam/gps/hist/point 2.0239554186952105 6239.0
/gate/source/mybeam/gps/hist/point 2.068435709841724 6161.0
/gate/source/mybeam/gps/hist/point 2.1129160009882373 5884.0
/gate/source/mybeam/gps/hist/point 2.1573962921347505 5708.0
/gate/source/mybeam/gps/hist/point 2.201876583281264 5752.0
/gate/source/mybeam/gps/hist/point 2.2463568744277778 5322.0
/gate/source/mybeam/gps/hist/point 2.290837165574291 5162.0
/gate/source/mybeam/gps/hist/point 2.335317456720804 5160.0
/gate/source/mybeam/gps/hist/point 2.3797977478673173 4892.0
/gate/source/mybeam/gps/hist/point 2.424278039013831 4737.0
/gate/source/mybeam/gps/hist/point 2.4687583301603446 4605.0
/gate/source/mybeam/gps/hist/point 2.513238621306858 4364.0
/gate/source/mybeam/gps/hist/point 2.557718912453371 4291.0
/gate/source/mybeam/gps/hist/point 2.602199203599884 4153.0
/gate/source/mybeam/gps/hist/point 2.646679494746398 3920.0
/gate/source/mybeam/gps/hist/point 2.6911597858929115 3723.0
/gate/source/mybeam/gps/hist/point 2.7356400770394247 3704.0
/gate/source/mybeam/gps/hist/point 2.780120368185938 3498.0
/gate/source/mybeam/gps/hist/point 2.8246006593324515 3477.0
/gate/source/mybeam/gps/hist/point 2.8690809504789647 3342.0
/gate/source/mybeam/gps/hist/point 2.9135612416254784 3229.0
/gate/source/mybeam/gps/hist/point 2.9580415327719916 3150.0
/gate/source/mybeam/gps/hist/point 3.0025218239185048 3024.0
/gate/source/mybeam/gps/hist/point 3.0470021150650184 2930.0
/gate/source/mybeam/gps/hist/point 3.091482406211532 2780.0
/gate/source/mybeam/gps/hist/point 3.1359626973580452 2680.0
/gate/source/mybeam/gps/hist/point 3.1804429885045584 2602.0
/gate/source/mybeam/gps/hist/point 3.2249232796510716 2439.0
/gate/source/mybeam/gps/hist/point 3.2694035707975853 2347.0
/gate/source/mybeam/gps/hist/point 3.313883861944099 2393.0
/gate/source/mybeam/gps/hist/point 3.358364153090612 2302.0
/gate/source/mybeam/gps/hist/point 3.4028444442371253 2060.0
/gate/source/mybeam/gps/hist/point 3.4473247353836385 2093.0
/gate/source/mybeam/gps/hist/point 3.491805026530152 1981.0
/gate/source/mybeam/gps/hist/point 3.5362853176766658 1913.0
/gate/source/mybeam/gps/hist/point 3.580765608823179 1857.0
/gate/source/mybeam/gps/hist/point 3.625245899969692 1770.0
/gate/source/mybeam/gps/hist/point 3.669726191116206 1703.0
/gate/source/mybeam/gps/hist/point 3.714206482262719 1560.0
/gate/source/mybeam/gps/hist/point 3.7586867734092326 1571.0
/gate/source/mybeam/gps/hist/point 3.803167064555746 1492.0
/gate/source/mybeam/gps/hist/point 3.847647355702259 1413.0
/gate/source/mybeam/gps/hist/point 3.8921276468487727 1425.0
/gate/source/mybeam/gps/hist/point 3.9366079379952863 1296.0
/gate/source/mybeam/gps/hist/point 3.9810882291417995 1238.0
/gate/source/mybeam/gps/hist/point 4.025568520288313 1184.0
/gate/source/mybeam/gps/hist/point 4.070048811434826 1166.0
/gate/source/mybeam/gps/hist/point 4.11452910258134 1148.0
/gate/source/mybeam/gps/hist/point 4.159009393727853 1099.0
/gate/source/mybeam/gps/hist/point 4.203489684874366 984.0
/gate/source/mybeam/gps/hist/point 4.24796997602088 954.0
/gate/source/mybeam/gps/hist/point 4.292450267167393 937.0
/gate/source/mybeam/gps/hist/point 4.336930558313906 874.0
/gate/source/mybeam/gps/hist/point 4.38141084946042 819.0
/gate/source/mybeam/gps/hist/point 4.425891140606933 723.0
/gate/source/mybeam/gps/hist/point 4.470371431753446 734.0
/gate/source/mybeam/gps/hist/point 4.5148517228999605 675.0
/gate/source/mybeam/gps/hist/point 4.559332014046474 645.0
/gate/source/mybeam/gps/hist/point 4.603812305192987 661.0
/gate/source/mybeam/gps/hist/point 4.6482925963395 551.0
/gate/source/mybeam/gps/hist/point 4.692772887486013 553.0
/gate/source/mybeam/gps/hist/point 4.7372531786325265 527.0
/gate/source/mybeam/gps/hist/point 4.781733469779041 467.0
/gate/source/mybeam/gps/hist/point 4.826213760925554 463.0
/gate/source/mybeam/gps/hist/point 4.870694052072067 465.0
/gate/source/mybeam/gps/hist/point 4.91517434321858 428.0
/gate/source/mybeam/gps/hist/point 4.959654634365094 387.0
/gate/source/mybeam/gps/hist/point 5.004134925511607 384.0
/gate/source/mybeam/gps/hist/point 5.048615216658121 331.0
/gate/source/mybeam/gps/hist/point 5.093095507804634 334.0
/gate/source/mybeam/gps/hist/point 5.137575798951147 301.0
/gate/source/mybeam/gps/hist/point 5.18205609009766 282.0
/gate/source/mybeam/gps/hist/point 5.226536381244174 241.0
/gate/source/mybeam/gps/hist/point 5.2710166723906875 214.0
/gate/source/mybeam/gps/hist/point 5.315496963537201 244.0
/gate/source/mybeam/gps/hist/point 5.359977254683715 189.0
/gate/source/mybeam/gps/hist/point 5.404457545830228 195.0
/gate/source/mybeam/gps/hist/point 5.448937836976741 167.0
/gate/source/mybeam/gps/hist/point 5.493418128123254 154.0
/gate/source/mybeam/gps/hist/point 5.537898419269768 147.0
/gate/source/mybeam/gps/hist/point 5.582378710416281 144.0
/gate/source/mybeam/gps/hist/point 5.626859001562795 127.0
/gate/source/mybeam/gps/hist/point 5.671339292709308 105.0
/gate/source/mybeam/gps/hist/point 5.715819583855821 105.0
/gate/source/mybeam/gps/hist/point 5.760299875002334 84.0
/gate/source/mybeam/gps/hist/point 5.8047801661488485 72.0
/gate/source/mybeam/gps/hist/point 5.849260457295362 72.0
/gate/source/mybeam/gps/hist/point 5.893740748441875 58.0
/gate/source/mybeam/gps/hist/point 5.938221039588388 44.0
/gate/source/mybeam/gps/hist/point 5.982701330734901 37.0
/gate/source/mybeam/gps/hist/point 6.0271816218814145 35.0
/gate/source/mybeam/gps/hist/point 6.071661913027929 20.0
/gate/source/mybeam/gps/hist/point 6.116142204174442 26.0
/gate/source/mybeam/gps/hist/point 6.160622495320955 17.0
/gate/source/mybeam/gps/hist/point 6.205102786467469 16.0
/gate/source/mybeam/gps/hist/point 6.249583077613982 11.0
/gate/source/mybeam/gps/hist/point 6.294063368760495 7.0
/gate/source/mybeam/gps/hist/point 6.338543659907009 6.0
/gate/source/mybeam/gps/hist/point 6.383023951053522 4.0
/gate/source/mybeam/gps/hist/point 6.427504242200035 2.0
/gate/source/mybeam/gps/hist/point 6.471984533346549 1.0
/gate/source/mybeam/gps/hist/point 6.516464824493062 0.0
/gate/source/mybeam/gps/hist/point 6.5609451156395755 0.0
/gate/source/mybeam/gps/hist/point 6.605425406786089 0.0
/gate/source/mybeam/gps/hist/point 6.649905697932603 1.0
/gate/source/mybeam/gps/hist/inter Log

#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed {seed}
#1234567890
/gate/application/noGlobalOutput

#/tracking/verbose 2

/gate/application/setTotalNumberOfPrimaries {primaries}
#1000
/gate/application/start
