# INPUTS
# pathOutputDose
# id
# seed 
# primaries
# peakzlength_um
# peakztrans_mm
# peakzlength2_um
# peakztrans2_mm
# peakzlength3_um
# peakztrans3_mm
# peakzlength4_um
# peakztrans4_mm
# peak_material

# Gate /home/as17540/linac/mac/Main_PhS2_Elec_Sensor_0.76xSeaLevel.mac -a '[id,$PBS_ARRAY_INDEX] [peakzlength_um,10] [peakztrans_mm,-5.495] [peakzlength2_um,30] [peakztrans2_mm,-5.485] [peakzlength3_um,50] [peakztrans3_mm,-5.475] [peakzlength4_um,70] [peakztrans4_mm,-5.465] [peak_material,Copper] [seed,$RANDOM$RANDOM$RANDOM] [primaries,10783000] [pathOutputDose,/work/as17540/PhaseSpaces/PhS3_Sensor_10x10_Elec/]'

#=====================================================
# VISUALISATION
#=====================================================

#/control/execute mac/visu.mac

# =====================================================
# GEOMETRY
# =====================================================

/gate/geometry/setMaterialDatabase /home/as17540/linac/data/GateMaterials_0.76xSeaLevel.db

# WORLD
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    0.3 m
/gate/world/geometry/setYLength    0.3 m
/gate/world/geometry/setZLength    1 m
/gate/world/vis/setVisible 1

/gate/world/daughters/name                   PhS_Plane_Two
/gate/world/daughters/insert                 box
/gate/PhS_Plane_Two/setMaterial              Vacuum
/gate/PhS_Plane_Two/geometry/setXLength      22 cm
/gate/PhS_Plane_Two/geometry/setYLength      22 cm
/gate/PhS_Plane_Two/geometry/setZLength      1 nm
/gate/PhS_Plane_Two/placement/setTranslation 0.0 0.0 471 mm #(-529)
/gate/PhS_Plane_Two/vis/setColor             cyan
/gate/PhS_Plane_Two/vis/setVisible           1

/gate/world/daughters/name                   Kill_BackPlane
/gate/world/daughters/insert                 box
/gate/Kill_BackPlane/setMaterial                   Air	
/gate/Kill_BackPlane/geometry/setXLength           30 cm
/gate/Kill_BackPlane/geometry/setYLength           30 cm
/gate/Kill_BackPlane/geometry/setZLength           1 nm
/gate/Kill_BackPlane/placement/setTranslation      0.0 0.0 480 mm
/gate/Kill_BackPlane/vis/setColor                  red
/gate/Kill_BackPlane/vis/setVisible                1

/gate/world/daughters/name                   Kill_FrontPlane
/gate/world/daughters/insert                 box
/gate/Kill_FrontPlane/setMaterial                   Air	
/gate/Kill_FrontPlane/geometry/setXLength           30 cm
/gate/Kill_FrontPlane/geometry/setYLength           30 cm
/gate/Kill_FrontPlane/geometry/setZLength           1 nm
/gate/Kill_FrontPlane/placement/setTranslation      0.0 0.0 445 mm
/gate/Kill_FrontPlane/vis/setColor                  red
/gate/Kill_FrontPlane/vis/setVisible                1

/gate/world/daughters/name         epi
/gate/world/daughters/insert       box
/gate/epi/setMaterial                  Silicon
/gate/epi/geometry/setXLength          180.0 mm
/gate/epi/geometry/setYLength          180.0 mm
/gate/epi/geometry/setZLength          0.01 mm
/gate/epi/placement/setTranslation     0 0 449.995 mm
/gate/epi/vis/setVisible               1
/gate/epi/vis/setColor                 yellow
/gate/epi/vis/forceSolid

/gate/world/daughters/name         bulk
/gate/world/daughters/insert       box
/gate/bulk/setMaterial                  Silicon
/gate/bulk/geometry/setXLength          180.0 mm
/gate/bulk/geometry/setYLength          180.0 mm
/gate/bulk/geometry/setZLength          0.6 mm
/gate/bulk/placement/setTranslation     0 0 449.69 mm
/gate/bulk/vis/setVisible               1
/gate/bulk/vis/setColor                 red

/gate/world/daughters/name         peak_air_box 
/gate/world/daughters/insert       box 
/gate/peak_air_box/setMaterial                  Air 
/gate/peak_air_box/geometry/setXLength          200.0 mm 
/gate/peak_air_box/geometry/setYLength          200.0 mm 
/gate/peak_air_box/geometry/setZLength          11 mm 
/gate/peak_air_box/placement/setTranslation     0 0 455.5 mm
/gate/peak_air_box/vis/setVisible               1 
/gate/peak_air_box/vis/setColor                 green
/gate/peak_air_box/vis/forceWireframe

/gate/peak_air_box/daughters/name         peakLayer1 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer1/setMaterial                  {peak_material} 
/gate/peakLayer1/geometry/setXLength          10.0 mm 
/gate/peakLayer1/geometry/setYLength          10.0 mm 
/gate/peakLayer1/geometry/setZLength          {peakzlength_um} um 
/gate/peakLayer1/placement/setTranslation     -5 5 {peakztrans_mm} mm
/gate/peakLayer1/vis/setVisible               1 
/gate/peakLayer1/vis/setColor                 grey
/gate/peakLayer1/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer2 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer2/setMaterial                  {peak_material} 
/gate/peakLayer2/geometry/setXLength          10.0 mm 
/gate/peakLayer2/geometry/setYLength          10.0 mm 
/gate/peakLayer2/geometry/setZLength          {peakzlength2_um} um 
/gate/peakLayer2/placement/setTranslation     5 5 {peakztrans2_mm} mm
/gate/peakLayer2/vis/setVisible               1 
/gate/peakLayer2/vis/setColor                 red
/gate/peakLayer2/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer3 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer3/setMaterial                  {peak_material} 
/gate/peakLayer3/geometry/setXLength          10.0 mm 
/gate/peakLayer3/geometry/setYLength          10.0 mm 
/gate/peakLayer3/geometry/setZLength          {peakzlength3_um} um 
/gate/peakLayer3/placement/setTranslation     -5 -5 {peakztrans3_mm} mm
/gate/peakLayer3/vis/setVisible               1 
/gate/peakLayer3/vis/setColor                 red
/gate/peakLayer3/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer4 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer4/setMaterial                  {peak_material} 
/gate/peakLayer4/geometry/setXLength          10.0 mm 
/gate/peakLayer4/geometry/setYLength          10.0 mm 
/gate/peakLayer4/geometry/setZLength          {peakzlength4_um} um 
/gate/peakLayer4/placement/setTranslation     5 -5 {peakztrans4_mm} mm
/gate/peakLayer4/vis/setVisible               1 
/gate/peakLayer4/vis/setColor                 red
/gate/peakLayer4/vis/forceSolid

# =====================================================
# PHYSICS
# =====================================================

/gate/physics/addPhysicsList emstandard_opt4

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      epi 0.0001 mm 
/gate/physics/Electron/SetCutInRegion   epi 0.0001 mm
/gate/physics/Positron/SetCutInRegion   epi 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      bulk 0.0001 mm
/gate/physics/Electron/SetCutInRegion   bulk 0.0001 mm
/gate/physics/Positron/SetCutInRegion   bulk 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer1 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer1 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer1 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer2 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer2 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer2 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer3 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer3 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer3 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer4 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer4 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer4 0.0001 mm

#=====================================================
# DETECTORS
#=====================================================

## 
## Dose output electron
## 
/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  {pathOutputDose}/Epi-{peakzlength_um}-{peakzlength2_um}-{peakzlength3_um}-{peakzlength4_um}_peakum-{peak_material}-0.76xSeaLevel-{id}.root
/gate/actor/doseDistribution/attachTo              epi
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setSize               50 50 0.010 mm
/gate/actor/doseDistribution/setResolution         1000 1000 1	 #for 60 micron pixel x4
/gate/actor/doseDistribution/enableNumberOfHits    true
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep false
/gate/actor/doseDistribution/enableSquaredEdep     true
/gate/actor/doseDistribution/enableDose            false
/gate/actor/doseDistribution/enableUncertaintyDose false


/gate/actor/addActor   KillActor                         Kill_BP 
/gate/actor/Kill_BP/attachTo                             Kill_BackPlane 

/gate/actor/addActor   KillActor                         Kill_FP 
/gate/actor/Kill_FP/attachTo                             Kill_FrontPlane 

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize
# /process/em/setBiasingFactor compt 100 True

# /process/em/setSecBiasing compt peakLayer1 100 1000 MeV
# /particle/process/dump

#=====================================================
# BEAMS
#=====================================================

# Read from Phase Space files. Here we indicate the type of particle
# (gamma) because this information is not stored in the PhS to gain
# space. Moreover, we set 'useRandomSymmetry' to generate more
# particle than the number of particle in the PhS, using a Z axis
# symmetry.

#/gate/source/addSource                         beam_g phaseSpace
#/gate/source/beam_g/addPhaseSpaceFile          {inputPhaseSpaceFile}
#{inputParticleType}
#/gate/source/beam_g/attachTo                   PhS_Plane_Two
#/gate/source/beam_g/useRandomSymmetry          true

/gate/source/addSource mybeam gps 
/gate/source/mybeam/gps/particle e- 
/gate/source/mybeam/gps/pos/centre 0 0 471 mm 
/gate/source/mybeam/gps/direction 0 0 -1 
/gate/source/mybeam/gps/type Plane 
/gate/source/mybeam/gps/shape Square 
/gate/source/mybeam/gps/halfx 2 cm 
/gate/source/mybeam/gps/halfy 2 cm 
/gate/source/mybeam/gps/ene/type Arb 
/gate/source/mybeam/gps/hist/type arb 
/gate/source/mybeam/gps/hist/point 0.02163116782704795 15536.0
/gate/source/mybeam/gps/hist/point 0.0646922333513794 20425.0
/gate/source/mybeam/gps/hist/point 0.10775329887571085 25014.0
/gate/source/mybeam/gps/hist/point 0.1508143644000423 26794.0
/gate/source/mybeam/gps/hist/point 0.19387542992437373 26828.0
/gate/source/mybeam/gps/hist/point 0.2369364954487052 26578.0
/gate/source/mybeam/gps/hist/point 0.27999756097303663 25935.0
/gate/source/mybeam/gps/hist/point 0.3230586264973681 24579.0
/gate/source/mybeam/gps/hist/point 0.3661196920216995 23477.0
/gate/source/mybeam/gps/hist/point 0.409180757546031 22906.0
/gate/source/mybeam/gps/hist/point 0.4522418230703624 21144.0
/gate/source/mybeam/gps/hist/point 0.4953028885946939 20199.0
/gate/source/mybeam/gps/hist/point 0.5383639541190253 19413.0
/gate/source/mybeam/gps/hist/point 0.5814250196433568 18647.0
/gate/source/mybeam/gps/hist/point 0.6244860851676883 18078.0
/gate/source/mybeam/gps/hist/point 0.6675471506920196 17425.0
/gate/source/mybeam/gps/hist/point 0.7106082162163512 16662.0
/gate/source/mybeam/gps/hist/point 0.7536692817406825 15875.0
/gate/source/mybeam/gps/hist/point 0.796730347265014 15426.0
/gate/source/mybeam/gps/hist/point 0.8397914127893455 14752.0
/gate/source/mybeam/gps/hist/point 0.8828524783136769 14125.0
/gate/source/mybeam/gps/hist/point 0.9259135438380084 13564.0
/gate/source/mybeam/gps/hist/point 0.9689746093623399 13301.0
/gate/source/mybeam/gps/hist/point 1.0120356748866712 13008.0
/gate/source/mybeam/gps/hist/point 1.0550967404110028 12522.0
/gate/source/mybeam/gps/hist/point 1.098157805935334 11951.0
/gate/source/mybeam/gps/hist/point 1.1412188714596656 11560.0
/gate/source/mybeam/gps/hist/point 1.1842799369839971 11187.0
/gate/source/mybeam/gps/hist/point 1.2273410025083287 10911.0
/gate/source/mybeam/gps/hist/point 1.27040206803266 10508.0
/gate/source/mybeam/gps/hist/point 1.3134631335569913 10046.0
/gate/source/mybeam/gps/hist/point 1.3565241990813228 9864.0
/gate/source/mybeam/gps/hist/point 1.3995852646056544 9424.0
/gate/source/mybeam/gps/hist/point 1.4426463301299859 9055.0
/gate/source/mybeam/gps/hist/point 1.4857073956543172 8846.0
/gate/source/mybeam/gps/hist/point 1.5287684611786485 8572.0
/gate/source/mybeam/gps/hist/point 1.57182952670298 8209.0
/gate/source/mybeam/gps/hist/point 1.6148905922273116 8025.0
/gate/source/mybeam/gps/hist/point 1.657951657751643 7941.0
/gate/source/mybeam/gps/hist/point 1.7010127232759744 7675.0
/gate/source/mybeam/gps/hist/point 1.744073788800306 7386.0
/gate/source/mybeam/gps/hist/point 1.7871348543246373 7055.0
/gate/source/mybeam/gps/hist/point 1.8301959198489688 6930.0
/gate/source/mybeam/gps/hist/point 1.8732569853733003 6613.0
/gate/source/mybeam/gps/hist/point 1.9163180508976319 6446.0
/gate/source/mybeam/gps/hist/point 1.9593791164219632 6245.0
/gate/source/mybeam/gps/hist/point 2.0024401819462945 6048.0
/gate/source/mybeam/gps/hist/point 2.045501247470626 5863.0
/gate/source/mybeam/gps/hist/point 2.0885623129949575 5827.0
/gate/source/mybeam/gps/hist/point 2.131623378519289 5514.0
/gate/source/mybeam/gps/hist/point 2.1746844440436206 5333.0
/gate/source/mybeam/gps/hist/point 2.2177455095679517 5276.0
/gate/source/mybeam/gps/hist/point 2.260806575092283 4914.0
/gate/source/mybeam/gps/hist/point 2.3038676406166148 4894.0
/gate/source/mybeam/gps/hist/point 2.3469287061409463 4745.0
/gate/source/mybeam/gps/hist/point 2.389989771665278 4550.0
/gate/source/mybeam/gps/hist/point 2.433050837189609 4462.0
/gate/source/mybeam/gps/hist/point 2.4761119027139404 4277.0
/gate/source/mybeam/gps/hist/point 2.519172968238272 4144.0
/gate/source/mybeam/gps/hist/point 2.5622340337626035 4079.0
/gate/source/mybeam/gps/hist/point 2.605295099286935 3762.0
/gate/source/mybeam/gps/hist/point 2.6483561648112666 3783.0
/gate/source/mybeam/gps/hist/point 2.6914172303355977 3730.0
/gate/source/mybeam/gps/hist/point 2.734478295859929 3438.0
/gate/source/mybeam/gps/hist/point 2.7775393613842607 3454.0
/gate/source/mybeam/gps/hist/point 2.8206004269085923 3292.0
/gate/source/mybeam/gps/hist/point 2.8636614924329233 3178.0
/gate/source/mybeam/gps/hist/point 2.906722557957255 3072.0
/gate/source/mybeam/gps/hist/point 2.9497836234815864 3046.0
/gate/source/mybeam/gps/hist/point 2.992844689005918 2865.0
/gate/source/mybeam/gps/hist/point 3.0359057545302495 2774.0
/gate/source/mybeam/gps/hist/point 3.078966820054581 2654.0
/gate/source/mybeam/gps/hist/point 3.122027885578912 2548.0
/gate/source/mybeam/gps/hist/point 3.1650889511032436 2415.0
/gate/source/mybeam/gps/hist/point 3.208150016627575 2507.0
/gate/source/mybeam/gps/hist/point 3.2512110821519067 2259.0
/gate/source/mybeam/gps/hist/point 3.294272147676238 2208.0
/gate/source/mybeam/gps/hist/point 3.3373332132005693 2230.0
/gate/source/mybeam/gps/hist/point 3.380394278724901 2058.0
/gate/source/mybeam/gps/hist/point 3.4234553442492324 1981.0
/gate/source/mybeam/gps/hist/point 3.466516409773564 1948.0
/gate/source/mybeam/gps/hist/point 3.5095774752978954 1823.0
/gate/source/mybeam/gps/hist/point 3.552638540822227 1745.0
/gate/source/mybeam/gps/hist/point 3.595699606346558 1689.0
/gate/source/mybeam/gps/hist/point 3.6387606718708896 1595.0
/gate/source/mybeam/gps/hist/point 3.681821737395221 1636.0
/gate/source/mybeam/gps/hist/point 3.7248828029195526 1531.0
/gate/source/mybeam/gps/hist/point 3.767943868443884 1490.0
/gate/source/mybeam/gps/hist/point 3.8110049339682153 1315.0
/gate/source/mybeam/gps/hist/point 3.854065999492547 1311.0
/gate/source/mybeam/gps/hist/point 3.8971270650168783 1265.0
/gate/source/mybeam/gps/hist/point 3.94018813054121 1227.0
/gate/source/mybeam/gps/hist/point 3.9832491960655414 1161.0
/gate/source/mybeam/gps/hist/point 4.026310261589872 1140.0
/gate/source/mybeam/gps/hist/point 4.0693713271142045 1093.0
/gate/source/mybeam/gps/hist/point 4.112432392638535 1024.0
/gate/source/mybeam/gps/hist/point 4.1554934581628675 978.0
/gate/source/mybeam/gps/hist/point 4.198554523687198 938.0
/gate/source/mybeam/gps/hist/point 4.241615589211531 884.0
/gate/source/mybeam/gps/hist/point 4.284676654735861 868.0
/gate/source/mybeam/gps/hist/point 4.327737720260194 772.0
/gate/source/mybeam/gps/hist/point 4.370798785784524 802.0
/gate/source/mybeam/gps/hist/point 4.413859851308855 721.0
/gate/source/mybeam/gps/hist/point 4.456920916833187 700.0
/gate/source/mybeam/gps/hist/point 4.499981982357518 660.0
/gate/source/mybeam/gps/hist/point 4.54304304788185 604.0
/gate/source/mybeam/gps/hist/point 4.586104113406181 594.0
/gate/source/mybeam/gps/hist/point 4.6291651789305135 545.0
/gate/source/mybeam/gps/hist/point 4.672226244454844 541.0
/gate/source/mybeam/gps/hist/point 4.7152873099791766 487.0
/gate/source/mybeam/gps/hist/point 4.758348375503507 463.0
/gate/source/mybeam/gps/hist/point 4.80140944102784 476.0
/gate/source/mybeam/gps/hist/point 4.84447050655217 417.0
/gate/source/mybeam/gps/hist/point 4.887531572076501 409.0
/gate/source/mybeam/gps/hist/point 4.930592637600833 365.0
/gate/source/mybeam/gps/hist/point 4.973653703125164 359.0
/gate/source/mybeam/gps/hist/point 5.016714768649496 324.0
/gate/source/mybeam/gps/hist/point 5.059775834173827 320.0
/gate/source/mybeam/gps/hist/point 5.1028368996981595 277.0
/gate/source/mybeam/gps/hist/point 5.14589796522249 297.0
/gate/source/mybeam/gps/hist/point 5.1889590307468225 239.0
/gate/source/mybeam/gps/hist/point 5.232020096271153 235.0
/gate/source/mybeam/gps/hist/point 5.275081161795485 218.0
/gate/source/mybeam/gps/hist/point 5.318142227319816 223.0
/gate/source/mybeam/gps/hist/point 5.361203292844147 180.0
/gate/source/mybeam/gps/hist/point 5.404264358368479 152.0
/gate/source/mybeam/gps/hist/point 5.44732542389281 151.0
/gate/source/mybeam/gps/hist/point 5.490386489417142 135.0
/gate/source/mybeam/gps/hist/point 5.533447554941473 137.0
/gate/source/mybeam/gps/hist/point 5.576508620465805 105.0
/gate/source/mybeam/gps/hist/point 5.619569685990136 119.0
/gate/source/mybeam/gps/hist/point 5.6626307515144685 97.0
/gate/source/mybeam/gps/hist/point 5.705691817038799 93.0
/gate/source/mybeam/gps/hist/point 5.748752882563131 80.0
/gate/source/mybeam/gps/hist/point 5.791813948087462 67.0
/gate/source/mybeam/gps/hist/point 5.834875013611793 66.0
/gate/source/mybeam/gps/hist/point 5.877936079136125 58.0
/gate/source/mybeam/gps/hist/point 5.920997144660456 48.0
/gate/source/mybeam/gps/hist/point 5.964058210184788 40.0
/gate/source/mybeam/gps/hist/point 6.007119275709119 40.0
/gate/source/mybeam/gps/hist/point 6.050180341233451 20.0
/gate/source/mybeam/gps/hist/point 6.093241406757782 23.0
/gate/source/mybeam/gps/hist/point 6.1363024722821145 16.0
/gate/source/mybeam/gps/hist/point 6.179363537806445 12.0
/gate/source/mybeam/gps/hist/point 6.222424603330776 13.0
/gate/source/mybeam/gps/hist/point 6.265485668855108 14.0
/gate/source/mybeam/gps/hist/point 6.308546734379439 6.0
/gate/source/mybeam/gps/hist/point 6.351607799903771 5.0
/gate/source/mybeam/gps/hist/point 6.394668865428102 4.0
/gate/source/mybeam/gps/hist/point 6.437729930952434 3.0
/gate/source/mybeam/gps/hist/inter Log

#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed {seed}
#1234567890
/gate/application/noGlobalOutput

#/tracking/verbose 2

/gate/application/setTotalNumberOfPrimaries {primaries}
#1000
/gate/application/start
