# INPUTS
# pathOutputDose
# id
# seed 
# primaries
# peakzlength_um
# peakztrans_mm
# peakzlength2_um
# peakztrans2_mm
# peakzlength3_um
# peakztrans3_mm
# peakzlength4_um
# peakztrans4_mm
# peak_material

# Gate /home/as17540/linac/mac/Main_PhS2_Elec_Sensor_0.95xSeaLevel.mac -a '[id,$PBS_ARRAY_INDEX] [peakzlength_um,10] [peakztrans_mm,-5.495] [peakzlength2_um,30] [peakztrans2_mm,-5.485] [peakzlength3_um,50] [peakztrans3_mm,-5.475] [peakzlength4_um,70] [peakztrans4_mm,-5.465] [peak_material,Copper] [seed,$RANDOM$RANDOM$RANDOM] [primaries,10783000] [pathOutputDose,/work/as17540/PhaseSpaces/PhS3_Sensor_10x10_Elec/]'

#=====================================================
# VISUALISATION
#=====================================================

#/control/execute mac/visu.mac

# =====================================================
# GEOMETRY
# =====================================================

/gate/geometry/setMaterialDatabase /home/as17540/linac/data/GateMaterials_0.95xSeaLevel.db

# WORLD
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    0.3 m
/gate/world/geometry/setYLength    0.3 m
/gate/world/geometry/setZLength    1 m
/gate/world/vis/setVisible 1

/gate/world/daughters/name                   PhS_Plane_Two
/gate/world/daughters/insert                 box
/gate/PhS_Plane_Two/setMaterial              Vacuum
/gate/PhS_Plane_Two/geometry/setXLength      22 cm
/gate/PhS_Plane_Two/geometry/setYLength      22 cm
/gate/PhS_Plane_Two/geometry/setZLength      1 nm
/gate/PhS_Plane_Two/placement/setTranslation 0.0 0.0 471 mm #(-529)
/gate/PhS_Plane_Two/vis/setColor             cyan
/gate/PhS_Plane_Two/vis/setVisible           1

/gate/world/daughters/name                   Kill_BackPlane
/gate/world/daughters/insert                 box
/gate/Kill_BackPlane/setMaterial                   Air	
/gate/Kill_BackPlane/geometry/setXLength           30 cm
/gate/Kill_BackPlane/geometry/setYLength           30 cm
/gate/Kill_BackPlane/geometry/setZLength           1 nm
/gate/Kill_BackPlane/placement/setTranslation      0.0 0.0 480 mm
/gate/Kill_BackPlane/vis/setColor                  red
/gate/Kill_BackPlane/vis/setVisible                1

/gate/world/daughters/name                   Kill_FrontPlane
/gate/world/daughters/insert                 box
/gate/Kill_FrontPlane/setMaterial                   Air	
/gate/Kill_FrontPlane/geometry/setXLength           30 cm
/gate/Kill_FrontPlane/geometry/setYLength           30 cm
/gate/Kill_FrontPlane/geometry/setZLength           1 nm
/gate/Kill_FrontPlane/placement/setTranslation      0.0 0.0 445 mm
/gate/Kill_FrontPlane/vis/setColor                  red
/gate/Kill_FrontPlane/vis/setVisible                1

/gate/world/daughters/name         epi
/gate/world/daughters/insert       box
/gate/epi/setMaterial                  Silicon
/gate/epi/geometry/setXLength          180.0 mm
/gate/epi/geometry/setYLength          180.0 mm
/gate/epi/geometry/setZLength          0.01 mm
/gate/epi/placement/setTranslation     0 0 449.995 mm
/gate/epi/vis/setVisible               1
/gate/epi/vis/setColor                 yellow
/gate/epi/vis/forceSolid

/gate/world/daughters/name         bulk
/gate/world/daughters/insert       box
/gate/bulk/setMaterial                  Silicon
/gate/bulk/geometry/setXLength          180.0 mm
/gate/bulk/geometry/setYLength          180.0 mm
/gate/bulk/geometry/setZLength          0.6 mm
/gate/bulk/placement/setTranslation     0 0 449.69 mm
/gate/bulk/vis/setVisible               1
/gate/bulk/vis/setColor                 red

/gate/world/daughters/name         peak_air_box 
/gate/world/daughters/insert       box 
/gate/peak_air_box/setMaterial                  Air 
/gate/peak_air_box/geometry/setXLength          200.0 mm 
/gate/peak_air_box/geometry/setYLength          200.0 mm 
/gate/peak_air_box/geometry/setZLength          11 mm 
/gate/peak_air_box/placement/setTranslation     0 0 455.5 mm
/gate/peak_air_box/vis/setVisible               1 
/gate/peak_air_box/vis/setColor                 green
/gate/peak_air_box/vis/forceWireframe

/gate/peak_air_box/daughters/name         peakLayer1 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer1/setMaterial                  {peak_material} 
/gate/peakLayer1/geometry/setXLength          10.0 mm 
/gate/peakLayer1/geometry/setYLength          10.0 mm 
/gate/peakLayer1/geometry/setZLength          {peakzlength_um} um 
/gate/peakLayer1/placement/setTranslation     -5 5 {peakztrans_mm} mm
/gate/peakLayer1/vis/setVisible               1 
/gate/peakLayer1/vis/setColor                 grey
/gate/peakLayer1/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer2 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer2/setMaterial                  {peak_material} 
/gate/peakLayer2/geometry/setXLength          10.0 mm 
/gate/peakLayer2/geometry/setYLength          10.0 mm 
/gate/peakLayer2/geometry/setZLength          {peakzlength2_um} um 
/gate/peakLayer2/placement/setTranslation     5 5 {peakztrans2_mm} mm
/gate/peakLayer2/vis/setVisible               1 
/gate/peakLayer2/vis/setColor                 red
/gate/peakLayer2/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer3 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer3/setMaterial                  {peak_material} 
/gate/peakLayer3/geometry/setXLength          10.0 mm 
/gate/peakLayer3/geometry/setYLength          10.0 mm 
/gate/peakLayer3/geometry/setZLength          {peakzlength3_um} um 
/gate/peakLayer3/placement/setTranslation     -5 -5 {peakztrans3_mm} mm
/gate/peakLayer3/vis/setVisible               1 
/gate/peakLayer3/vis/setColor                 red
/gate/peakLayer3/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer4 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer4/setMaterial                  {peak_material} 
/gate/peakLayer4/geometry/setXLength          10.0 mm 
/gate/peakLayer4/geometry/setYLength          10.0 mm 
/gate/peakLayer4/geometry/setZLength          {peakzlength4_um} um 
/gate/peakLayer4/placement/setTranslation     5 -5 {peakztrans4_mm} mm
/gate/peakLayer4/vis/setVisible               1 
/gate/peakLayer4/vis/setColor                 red
/gate/peakLayer4/vis/forceSolid

# =====================================================
# PHYSICS
# =====================================================

/gate/physics/addPhysicsList emstandard_opt4

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      epi 0.0001 mm 
/gate/physics/Electron/SetCutInRegion   epi 0.0001 mm
/gate/physics/Positron/SetCutInRegion   epi 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      bulk 0.0001 mm
/gate/physics/Electron/SetCutInRegion   bulk 0.0001 mm
/gate/physics/Positron/SetCutInRegion   bulk 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer1 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer1 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer1 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer2 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer2 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer2 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer3 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer3 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer3 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer4 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer4 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer4 0.0001 mm

#=====================================================
# DETECTORS
#=====================================================

## 
## Dose output electron
## 
/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  {pathOutputDose}/Epi-{peakzlength_um}-{peakzlength2_um}-{peakzlength3_um}-{peakzlength4_um}_peakum-{peak_material}-0.95xSeaLevel-{id}.root
/gate/actor/doseDistribution/attachTo              epi
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setSize               50 50 0.010 mm
/gate/actor/doseDistribution/setResolution         1000 1000 1	 #for 60 micron pixel x4
/gate/actor/doseDistribution/enableNumberOfHits    true
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep false
/gate/actor/doseDistribution/enableSquaredEdep     true
/gate/actor/doseDistribution/enableDose            false
/gate/actor/doseDistribution/enableUncertaintyDose false


/gate/actor/addActor   KillActor                         Kill_BP 
/gate/actor/Kill_BP/attachTo                             Kill_BackPlane 

/gate/actor/addActor   KillActor                         Kill_FP 
/gate/actor/Kill_FP/attachTo                             Kill_FrontPlane 

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize
# /process/em/setBiasingFactor compt 100 True

# /process/em/setSecBiasing compt peakLayer1 100 1000 MeV
# /particle/process/dump

#=====================================================
# BEAMS
#=====================================================

# Read from Phase Space files. Here we indicate the type of particle
# (gamma) because this information is not stored in the PhS to gain
# space. Moreover, we set 'useRandomSymmetry' to generate more
# particle than the number of particle in the PhS, using a Z axis
# symmetry.

#/gate/source/addSource                         beam_g phaseSpace
#/gate/source/beam_g/addPhaseSpaceFile          {inputPhaseSpaceFile}
#{inputParticleType}
#/gate/source/beam_g/attachTo                   PhS_Plane_Two
#/gate/source/beam_g/useRandomSymmetry          true

/gate/source/addSource mybeam gps 
/gate/source/mybeam/gps/particle e- 
/gate/source/mybeam/gps/pos/centre 0 0 471 mm 
/gate/source/mybeam/gps/direction 0 0 -1 
/gate/source/mybeam/gps/type Plane 
/gate/source/mybeam/gps/shape Square 
/gate/source/mybeam/gps/halfx 2 cm 
/gate/source/mybeam/gps/halfy 2 cm 
/gate/source/mybeam/gps/ene/type Arb 
/gate/source/mybeam/gps/hist/type arb 
/gate/source/mybeam/gps/hist/point 0.021950507093715713 15843.0
/gate/source/mybeam/gps/hist/point 0.06565007606273866 21569.0
/gate/source/mybeam/gps/hist/point 0.10934964503176162 26237.0
/gate/source/mybeam/gps/hist/point 0.15304921400078456 28357.0
/gate/source/mybeam/gps/hist/point 0.1967487829698075 28547.0
/gate/source/mybeam/gps/hist/point 0.24044835193883046 28147.0
/gate/source/mybeam/gps/hist/point 0.2841479209078534 27505.0
/gate/source/mybeam/gps/hist/point 0.32784748987687634 25964.0
/gate/source/mybeam/gps/hist/point 0.3715470588458993 25174.0
/gate/source/mybeam/gps/hist/point 0.4152466278149222 23740.0
/gate/source/mybeam/gps/hist/point 0.45894619678394516 22599.0
/gate/source/mybeam/gps/hist/point 0.5026457657529682 21852.0
/gate/source/mybeam/gps/hist/point 0.5463453347219911 20696.0
/gate/source/mybeam/gps/hist/point 0.590044903691014 19733.0
/gate/source/mybeam/gps/hist/point 0.633744472660037 19201.0
/gate/source/mybeam/gps/hist/point 0.6774440416290599 18353.0
/gate/source/mybeam/gps/hist/point 0.7211436105980829 17628.0
/gate/source/mybeam/gps/hist/point 0.7648431795671058 16946.0
/gate/source/mybeam/gps/hist/point 0.8085427485361287 16218.0
/gate/source/mybeam/gps/hist/point 0.8522423175051517 15567.0
/gate/source/mybeam/gps/hist/point 0.8959418864741746 15009.0
/gate/source/mybeam/gps/hist/point 0.9396414554431975 14451.0
/gate/source/mybeam/gps/hist/point 0.9833410244122205 13972.0
/gate/source/mybeam/gps/hist/point 1.0270405933812436 13355.0
/gate/source/mybeam/gps/hist/point 1.0707401623502664 13061.0
/gate/source/mybeam/gps/hist/point 1.1144397313192895 12534.0
/gate/source/mybeam/gps/hist/point 1.1581393002883122 12291.0
/gate/source/mybeam/gps/hist/point 1.2018388692573354 11619.0
/gate/source/mybeam/gps/hist/point 1.2455384382263581 11268.0
/gate/source/mybeam/gps/hist/point 1.2892380071953813 10871.0
/gate/source/mybeam/gps/hist/point 1.332937576164404 10622.0
/gate/source/mybeam/gps/hist/point 1.3766371451334272 10284.0
/gate/source/mybeam/gps/hist/point 1.4203367141024499 9978.0
/gate/source/mybeam/gps/hist/point 1.464036283071473 9661.0
/gate/source/mybeam/gps/hist/point 1.5077358520404958 9347.0
/gate/source/mybeam/gps/hist/point 1.551435421009519 9107.0
/gate/source/mybeam/gps/hist/point 1.5951349899785416 8631.0
/gate/source/mybeam/gps/hist/point 1.6388345589475648 8429.0
/gate/source/mybeam/gps/hist/point 1.6825341279165875 8201.0
/gate/source/mybeam/gps/hist/point 1.7262336968856107 7692.0
/gate/source/mybeam/gps/hist/point 1.7699332658546334 7547.0
/gate/source/mybeam/gps/hist/point 1.8136328348236566 7396.0
/gate/source/mybeam/gps/hist/point 1.8573324037926793 7058.0
/gate/source/mybeam/gps/hist/point 1.9010319727617024 6906.0
/gate/source/mybeam/gps/hist/point 1.9447315417307252 6753.0
/gate/source/mybeam/gps/hist/point 1.9884311106997483 6554.0
/gate/source/mybeam/gps/hist/point 2.0321306796687715 6254.0
/gate/source/mybeam/gps/hist/point 2.075830248637794 6213.0
/gate/source/mybeam/gps/hist/point 2.119529817606817 5856.0
/gate/source/mybeam/gps/hist/point 2.16322938657584 5667.0
/gate/source/mybeam/gps/hist/point 2.2069289555448632 5628.0
/gate/source/mybeam/gps/hist/point 2.250628524513886 5332.0
/gate/source/mybeam/gps/hist/point 2.2943280934829087 5121.0
/gate/source/mybeam/gps/hist/point 2.338027662451932 4974.0
/gate/source/mybeam/gps/hist/point 2.381727231420955 4815.0
/gate/source/mybeam/gps/hist/point 2.4254268003899777 4741.0
/gate/source/mybeam/gps/hist/point 2.4691263693590004 4565.0
/gate/source/mybeam/gps/hist/point 2.5128259383280236 4340.0
/gate/source/mybeam/gps/hist/point 2.5565255072970468 4042.0
/gate/source/mybeam/gps/hist/point 2.6002250762660695 4153.0
/gate/source/mybeam/gps/hist/point 2.643924645235092 4153.0
/gate/source/mybeam/gps/hist/point 2.6876242142041153 3873.0
/gate/source/mybeam/gps/hist/point 2.7313237831731385 3671.0
/gate/source/mybeam/gps/hist/point 2.7750233521421612 3649.0
/gate/source/mybeam/gps/hist/point 2.8187229211111844 3505.0
/gate/source/mybeam/gps/hist/point 2.862422490080207 3383.0
/gate/source/mybeam/gps/hist/point 2.9061220590492303 3365.0
/gate/source/mybeam/gps/hist/point 2.9498216280182534 3158.0
/gate/source/mybeam/gps/hist/point 2.993521196987276 3010.0
/gate/source/mybeam/gps/hist/point 3.037220765956299 2982.0
/gate/source/mybeam/gps/hist/point 3.080920334925322 2847.0
/gate/source/mybeam/gps/hist/point 3.124619903894345 2683.0
/gate/source/mybeam/gps/hist/point 3.168319472863368 2756.0
/gate/source/mybeam/gps/hist/point 3.2120190418323906 2503.0
/gate/source/mybeam/gps/hist/point 3.255718610801414 2445.0
/gate/source/mybeam/gps/hist/point 3.299418179770437 2372.0
/gate/source/mybeam/gps/hist/point 3.3431177487394597 2250.0
/gate/source/mybeam/gps/hist/point 3.3868173177084824 2224.0
/gate/source/mybeam/gps/hist/point 3.4305168866775055 2077.0
/gate/source/mybeam/gps/hist/point 3.4742164556465287 2015.0
/gate/source/mybeam/gps/hist/point 3.5179160246155514 1936.0
/gate/source/mybeam/gps/hist/point 3.561615593584574 1766.0
/gate/source/mybeam/gps/hist/point 3.6053151625535973 1787.0
/gate/source/mybeam/gps/hist/point 3.6490147315226205 1748.0
/gate/source/mybeam/gps/hist/point 3.692714300491643 1658.0
/gate/source/mybeam/gps/hist/point 3.736413869460666 1605.0
/gate/source/mybeam/gps/hist/point 3.780113438429689 1461.0
/gate/source/mybeam/gps/hist/point 3.823813007398712 1507.0
/gate/source/mybeam/gps/hist/point 3.867512576367735 1473.0
/gate/source/mybeam/gps/hist/point 3.9112121453367577 1368.0
/gate/source/mybeam/gps/hist/point 3.954911714305781 1276.0
/gate/source/mybeam/gps/hist/point 3.998611283274804 1224.0
/gate/source/mybeam/gps/hist/point 4.042310852243826 1167.0
/gate/source/mybeam/gps/hist/point 4.086010421212849 1160.0
/gate/source/mybeam/gps/hist/point 4.129709990181873 1074.0
/gate/source/mybeam/gps/hist/point 4.173409559150896 1006.0
/gate/source/mybeam/gps/hist/point 4.217109128119919 982.0
/gate/source/mybeam/gps/hist/point 4.260808697088942 922.0
/gate/source/mybeam/gps/hist/point 4.304508266057964 896.0
/gate/source/mybeam/gps/hist/point 4.3482078350269875 871.0
/gate/source/mybeam/gps/hist/point 4.391907403996011 780.0
/gate/source/mybeam/gps/hist/point 4.435606972965033 761.0
/gate/source/mybeam/gps/hist/point 4.479306541934056 778.0
/gate/source/mybeam/gps/hist/point 4.523006110903079 752.0
/gate/source/mybeam/gps/hist/point 4.566705679872102 642.0
/gate/source/mybeam/gps/hist/point 4.610405248841126 631.0
/gate/source/mybeam/gps/hist/point 4.654104817810148 607.0
/gate/source/mybeam/gps/hist/point 4.697804386779171 554.0
/gate/source/mybeam/gps/hist/point 4.741503955748194 515.0
/gate/source/mybeam/gps/hist/point 4.785203524717216 493.0
/gate/source/mybeam/gps/hist/point 4.82890309368624 465.0
/gate/source/mybeam/gps/hist/point 4.872602662655263 433.0
/gate/source/mybeam/gps/hist/point 4.916302231624286 385.0
/gate/source/mybeam/gps/hist/point 4.960001800593309 401.0
/gate/source/mybeam/gps/hist/point 5.003701369562331 308.0
/gate/source/mybeam/gps/hist/point 5.0474009385313545 359.0
/gate/source/mybeam/gps/hist/point 5.091100507500378 353.0
/gate/source/mybeam/gps/hist/point 5.1348000764694 309.0
/gate/source/mybeam/gps/hist/point 5.178499645438423 323.0
/gate/source/mybeam/gps/hist/point 5.222199214407446 288.0
/gate/source/mybeam/gps/hist/point 5.265898783376469 254.0
/gate/source/mybeam/gps/hist/point 5.309598352345493 216.0
/gate/source/mybeam/gps/hist/point 5.353297921314515 222.0
/gate/source/mybeam/gps/hist/point 5.396997490283538 201.0
/gate/source/mybeam/gps/hist/point 5.440697059252561 212.0
/gate/source/mybeam/gps/hist/point 5.4843966282215835 174.0
/gate/source/mybeam/gps/hist/point 5.528096197190607 153.0
/gate/source/mybeam/gps/hist/point 5.57179576615963 125.0
/gate/source/mybeam/gps/hist/point 5.615495335128653 147.0
/gate/source/mybeam/gps/hist/point 5.659194904097676 115.0
/gate/source/mybeam/gps/hist/point 5.702894473066699 96.0
/gate/source/mybeam/gps/hist/point 5.7465940420357216 86.0
/gate/source/mybeam/gps/hist/point 5.790293611004745 82.0
/gate/source/mybeam/gps/hist/point 5.833993179973768 77.0
/gate/source/mybeam/gps/hist/point 5.87769274894279 69.0
/gate/source/mybeam/gps/hist/point 5.921392317911813 65.0
/gate/source/mybeam/gps/hist/point 5.9650918868808365 48.0
/gate/source/mybeam/gps/hist/point 6.00879145584986 50.0
/gate/source/mybeam/gps/hist/point 6.052491024818883 38.0
/gate/source/mybeam/gps/hist/point 6.096190593787905 19.0
/gate/source/mybeam/gps/hist/point 6.139890162756928 21.0
/gate/source/mybeam/gps/hist/point 6.183589731725951 8.0
/gate/source/mybeam/gps/hist/point 6.227289300694974 13.0
/gate/source/mybeam/gps/hist/point 6.270988869663997 6.0
/gate/source/mybeam/gps/hist/point 6.31468843863302 4.0
/gate/source/mybeam/gps/hist/point 6.358388007602043 6.0
/gate/source/mybeam/gps/hist/point 6.402087576571066 1.0
/gate/source/mybeam/gps/hist/point 6.445787145540089 3.0
/gate/source/mybeam/gps/hist/point 6.489486714509112 1.0
/gate/source/mybeam/gps/hist/point 6.533186283478135 2.0
/gate/source/mybeam/gps/hist/inter Log

#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed {seed}
#1234567890
/gate/application/noGlobalOutput

#/tracking/verbose 2

/gate/application/setTotalNumberOfPrimaries {primaries}
#1000
/gate/application/start
