# INPUTS
# pathOutputDose
# id
# seed 
# primaries
# peakzlength_um
# peakztrans_mm
# peakzlength2_um
# peakztrans2_mm
# peakzlength3_um
# peakztrans3_mm
# peakzlength4_um
# peakztrans4_mm
# peak_material

# Gate /home/as17540/linac/mac/Main_PhS2_Elec_Sensor_0.8xSeaLevel.mac -a '[id,$PBS_ARRAY_INDEX] [peakzlength_um,10] [peakztrans_mm,-5.495] [peakzlength2_um,30] [peakztrans2_mm,-5.485] [peakzlength3_um,50] [peakztrans3_mm,-5.475] [peakzlength4_um,70] [peakztrans4_mm,-5.465] [peak_material,Copper] [seed,$RANDOM$RANDOM$RANDOM] [primaries,11034700] [pathOutputDose,/work/as17540/PhaseSpaces/PhS3_Sensor_10x10_Elec/]'

#=====================================================
# VISUALISATION
#=====================================================

#/control/execute mac/visu.mac

# =====================================================
# GEOMETRY
# =====================================================

/gate/geometry/setMaterialDatabase /home/as17540/linac/data/GateMaterials_0.816xSeaLevel.db

# WORLD
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    0.3 m
/gate/world/geometry/setYLength    0.3 m
/gate/world/geometry/setZLength    1 m
/gate/world/vis/setVisible 1

/gate/world/daughters/name                   PhS_Plane_Two
/gate/world/daughters/insert                 box
/gate/PhS_Plane_Two/setMaterial              Vacuum
/gate/PhS_Plane_Two/geometry/setXLength      22 cm
/gate/PhS_Plane_Two/geometry/setYLength      22 cm
/gate/PhS_Plane_Two/geometry/setZLength      1 nm
/gate/PhS_Plane_Two/placement/setTranslation 0.0 0.0 471 mm #(-529)
/gate/PhS_Plane_Two/vis/setColor             cyan
/gate/PhS_Plane_Two/vis/setVisible           1

/gate/world/daughters/name                   Kill_BackPlane
/gate/world/daughters/insert                 box
/gate/Kill_BackPlane/setMaterial                   Air	
/gate/Kill_BackPlane/geometry/setXLength           30 cm
/gate/Kill_BackPlane/geometry/setYLength           30 cm
/gate/Kill_BackPlane/geometry/setZLength           1 nm
/gate/Kill_BackPlane/placement/setTranslation      0.0 0.0 480 mm
/gate/Kill_BackPlane/vis/setColor                  red
/gate/Kill_BackPlane/vis/setVisible                1

/gate/world/daughters/name                   Kill_FrontPlane
/gate/world/daughters/insert                 box
/gate/Kill_FrontPlane/setMaterial                   Air	
/gate/Kill_FrontPlane/geometry/setXLength           30 cm
/gate/Kill_FrontPlane/geometry/setYLength           30 cm
/gate/Kill_FrontPlane/geometry/setZLength           1 nm
/gate/Kill_FrontPlane/placement/setTranslation      0.0 0.0 445 mm
/gate/Kill_FrontPlane/vis/setColor                  red
/gate/Kill_FrontPlane/vis/setVisible                1

/gate/world/daughters/name         epi
/gate/world/daughters/insert       box
/gate/epi/setMaterial                  Silicon
/gate/epi/geometry/setXLength          180.0 mm
/gate/epi/geometry/setYLength          180.0 mm
/gate/epi/geometry/setZLength          0.01 mm
/gate/epi/placement/setTranslation     0 0 449.995 mm
/gate/epi/vis/setVisible               1
/gate/epi/vis/setColor                 yellow
/gate/epi/vis/forceSolid

/gate/world/daughters/name         bulk
/gate/world/daughters/insert       box
/gate/bulk/setMaterial                  Silicon
/gate/bulk/geometry/setXLength          180.0 mm
/gate/bulk/geometry/setYLength          180.0 mm
/gate/bulk/geometry/setZLength          0.6 mm
/gate/bulk/placement/setTranslation     0 0 449.69 mm
/gate/bulk/vis/setVisible               1
/gate/bulk/vis/setColor                 red

/gate/world/daughters/name         peak_air_box 
/gate/world/daughters/insert       box 
/gate/peak_air_box/setMaterial                  Air 
/gate/peak_air_box/geometry/setXLength          200.0 mm 
/gate/peak_air_box/geometry/setYLength          200.0 mm 
/gate/peak_air_box/geometry/setZLength          11 mm 
/gate/peak_air_box/placement/setTranslation     0 0 455.5 mm
/gate/peak_air_box/vis/setVisible               1 
/gate/peak_air_box/vis/setColor                 green
/gate/peak_air_box/vis/forceWireframe

/gate/peak_air_box/daughters/name         peakLayer1 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer1/setMaterial                  {peak_material} 
/gate/peakLayer1/geometry/setXLength          10.0 mm 
/gate/peakLayer1/geometry/setYLength          10.0 mm 
/gate/peakLayer1/geometry/setZLength          {peakzlength_um} um 
/gate/peakLayer1/placement/setTranslation     -5 5 {peakztrans_mm} mm
/gate/peakLayer1/vis/setVisible               1 
/gate/peakLayer1/vis/setColor                 grey
/gate/peakLayer1/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer2 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer2/setMaterial                  {peak_material} 
/gate/peakLayer2/geometry/setXLength          10.0 mm 
/gate/peakLayer2/geometry/setYLength          10.0 mm 
/gate/peakLayer2/geometry/setZLength          {peakzlength2_um} um 
/gate/peakLayer2/placement/setTranslation     5 5 {peakztrans2_mm} mm
/gate/peakLayer2/vis/setVisible               1 
/gate/peakLayer2/vis/setColor                 red
/gate/peakLayer2/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer3 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer3/setMaterial                  {peak_material} 
/gate/peakLayer3/geometry/setXLength          10.0 mm 
/gate/peakLayer3/geometry/setYLength          10.0 mm 
/gate/peakLayer3/geometry/setZLength          {peakzlength3_um} um 
/gate/peakLayer3/placement/setTranslation     -5 -5 {peakztrans3_mm} mm
/gate/peakLayer3/vis/setVisible               1 
/gate/peakLayer3/vis/setColor                 red
/gate/peakLayer3/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer4 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer4/setMaterial                  {peak_material} 
/gate/peakLayer4/geometry/setXLength          10.0 mm 
/gate/peakLayer4/geometry/setYLength          10.0 mm 
/gate/peakLayer4/geometry/setZLength          {peakzlength4_um} um 
/gate/peakLayer4/placement/setTranslation     5 -5 {peakztrans4_mm} mm
/gate/peakLayer4/vis/setVisible               1 
/gate/peakLayer4/vis/setColor                 red
/gate/peakLayer4/vis/forceSolid

# =====================================================
# PHYSICS
# =====================================================

/gate/physics/addPhysicsList emstandard_opt4

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      epi 0.0001 mm 
/gate/physics/Electron/SetCutInRegion   epi 0.0001 mm
/gate/physics/Positron/SetCutInRegion   epi 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      bulk 0.0001 mm
/gate/physics/Electron/SetCutInRegion   bulk 0.0001 mm
/gate/physics/Positron/SetCutInRegion   bulk 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer1 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer1 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer1 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer2 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer2 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer2 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer3 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer3 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer3 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer4 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer4 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer4 0.0001 mm

#=====================================================
# DETECTORS
#=====================================================

## 
## Dose output electron
## 
/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  {pathOutputDose}/Epi-{peakzlength_um}-{peakzlength2_um}-{peakzlength3_um}-{peakzlength4_um}_peakum-{peak_material}-0.816xSeaLevel-{id}.root
/gate/actor/doseDistribution/attachTo              epi
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setSize               50 50 0.010 mm
/gate/actor/doseDistribution/setResolution         1000 1000 1	 #for 60 micron pixel x4
/gate/actor/doseDistribution/enableNumberOfHits    true
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep false
/gate/actor/doseDistribution/enableSquaredEdep     true
/gate/actor/doseDistribution/enableDose            false
/gate/actor/doseDistribution/enableUncertaintyDose false


/gate/actor/addActor   KillActor                         Kill_BP 
/gate/actor/Kill_BP/attachTo                             Kill_BackPlane 

/gate/actor/addActor   KillActor                         Kill_FP 
/gate/actor/Kill_FP/attachTo                             Kill_FrontPlane 

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize
# /process/em/setBiasingFactor compt 100 True

# /process/em/setSecBiasing compt peakLayer1 100 1000 MeV
# /particle/process/dump

#=====================================================
# BEAMS
#=====================================================

# Read from Phase Space files. Here we indicate the type of particle
# (gamma) because this information is not stored in the PhS to gain
# space. Moreover, we set 'useRandomSymmetry' to generate more
# particle than the number of particle in the PhS, using a Z axis
# symmetry.

#/gate/source/addSource                         beam_g phaseSpace
#/gate/source/beam_g/addPhaseSpaceFile          {inputPhaseSpaceFile}
#{inputParticleType}
#/gate/source/beam_g/attachTo                   PhS_Plane_Two
#/gate/source/beam_g/useRandomSymmetry          true

/gate/source/addSource mybeam gps 
/gate/source/mybeam/gps/particle e- 
/gate/source/mybeam/gps/pos/centre 0 0 471 mm 
/gate/source/mybeam/gps/direction 0 0 -1 
/gate/source/mybeam/gps/type Plane 
/gate/source/mybeam/gps/shape Square 
/gate/source/mybeam/gps/halfx 2 cm 
/gate/source/mybeam/gps/halfy 2 cm 
/gate/source/mybeam/gps/ene/type Arb 
/gate/source/mybeam/gps/hist/type arb 
/gate/source/mybeam/gps/hist/point 0.021668983828931232 15580.0
/gate/source/mybeam/gps/hist/point 0.06480654645383765 20724.0
/gate/source/mybeam/gps/hist/point 0.10794410907874408 25525.0
/gate/source/mybeam/gps/hist/point 0.1510816717036505 27111.0
/gate/source/mybeam/gps/hist/point 0.19421923432855692 27533.0
/gate/source/mybeam/gps/hist/point 0.23735679695346334 27068.0
/gate/source/mybeam/gps/hist/point 0.28049435957836977 26122.0
/gate/source/mybeam/gps/hist/point 0.3236319222032762 25319.0
/gate/source/mybeam/gps/hist/point 0.3667694848281826 24009.0
/gate/source/mybeam/gps/hist/point 0.40990704745308904 22714.0
/gate/source/mybeam/gps/hist/point 0.45304461007799546 21617.0
/gate/source/mybeam/gps/hist/point 0.4961821727029019 20553.0
/gate/source/mybeam/gps/hist/point 0.5393197353278083 19502.0
/gate/source/mybeam/gps/hist/point 0.5824572979527147 18707.0
/gate/source/mybeam/gps/hist/point 0.6255948605776211 18108.0
/gate/source/mybeam/gps/hist/point 0.6687324232025276 17745.0
/gate/source/mybeam/gps/hist/point 0.711869985827434 16847.0
/gate/source/mybeam/gps/hist/point 0.7550075484523404 16303.0
/gate/source/mybeam/gps/hist/point 0.7981451110772468 15490.0
/gate/source/mybeam/gps/hist/point 0.8412826737021533 15143.0
/gate/source/mybeam/gps/hist/point 0.8844202363270597 14668.0
/gate/source/mybeam/gps/hist/point 0.9275577989519661 13859.0
/gate/source/mybeam/gps/hist/point 0.9706953615768725 13310.0
/gate/source/mybeam/gps/hist/point 1.013832924201779 12982.0
/gate/source/mybeam/gps/hist/point 1.0569704868266854 12265.0
/gate/source/mybeam/gps/hist/point 1.1001080494515918 12159.0
/gate/source/mybeam/gps/hist/point 1.1432456120764982 11688.0
/gate/source/mybeam/gps/hist/point 1.1863831747014046 11268.0
/gate/source/mybeam/gps/hist/point 1.229520737326311 10974.0
/gate/source/mybeam/gps/hist/point 1.2726582999512175 10663.0
/gate/source/mybeam/gps/hist/point 1.315795862576124 10130.0
/gate/source/mybeam/gps/hist/point 1.3589334252010303 9930.0
/gate/source/mybeam/gps/hist/point 1.4020709878259368 9455.0
/gate/source/mybeam/gps/hist/point 1.4452085504508432 9208.0
/gate/source/mybeam/gps/hist/point 1.4883461130757496 8819.0
/gate/source/mybeam/gps/hist/point 1.531483675700656 8807.0
/gate/source/mybeam/gps/hist/point 1.5746212383255624 8375.0
/gate/source/mybeam/gps/hist/point 1.6177588009504689 8182.0
/gate/source/mybeam/gps/hist/point 1.6608963635753753 7767.0
/gate/source/mybeam/gps/hist/point 1.7040339262002817 7683.0
/gate/source/mybeam/gps/hist/point 1.7471714888251881 7392.0
/gate/source/mybeam/gps/hist/point 1.7903090514500946 7146.0
/gate/source/mybeam/gps/hist/point 1.833446614075001 6871.0
/gate/source/mybeam/gps/hist/point 1.8765841766999074 6876.0
/gate/source/mybeam/gps/hist/point 1.9197217393248138 6539.0
/gate/source/mybeam/gps/hist/point 1.9628593019497202 6198.0
/gate/source/mybeam/gps/hist/point 2.0059968645746267 6099.0
/gate/source/mybeam/gps/hist/point 2.049134427199533 5878.0
/gate/source/mybeam/gps/hist/point 2.0922719898244395 5775.0
/gate/source/mybeam/gps/hist/point 2.135409552449346 5561.0
/gate/source/mybeam/gps/hist/point 2.1785471150742524 5456.0
/gate/source/mybeam/gps/hist/point 2.221684677699159 5076.0
/gate/source/mybeam/gps/hist/point 2.264822240324065 5017.0
/gate/source/mybeam/gps/hist/point 2.3079598029489716 4937.0
/gate/source/mybeam/gps/hist/point 2.351097365573878 4811.0
/gate/source/mybeam/gps/hist/point 2.3942349281987845 4671.0
/gate/source/mybeam/gps/hist/point 2.437372490823691 4341.0
/gate/source/mybeam/gps/hist/point 2.4805100534485973 4409.0
/gate/source/mybeam/gps/hist/point 2.5236476160735037 4284.0
/gate/source/mybeam/gps/hist/point 2.56678517869841 3969.0
/gate/source/mybeam/gps/hist/point 2.6099227413233166 3870.0
/gate/source/mybeam/gps/hist/point 2.653060303948223 3772.0
/gate/source/mybeam/gps/hist/point 2.6961978665731294 3768.0
/gate/source/mybeam/gps/hist/point 2.739335429198036 3727.0
/gate/source/mybeam/gps/hist/point 2.7824729918229423 3457.0
/gate/source/mybeam/gps/hist/point 2.8256105544478487 3210.0
/gate/source/mybeam/gps/hist/point 2.868748117072755 3283.0
/gate/source/mybeam/gps/hist/point 2.9118856796976615 3146.0
/gate/source/mybeam/gps/hist/point 2.955023242322568 2948.0
/gate/source/mybeam/gps/hist/point 2.9981608049474744 2956.0
/gate/source/mybeam/gps/hist/point 3.041298367572381 2803.0
/gate/source/mybeam/gps/hist/point 3.0844359301972872 2823.0
/gate/source/mybeam/gps/hist/point 3.1275734928221937 2599.0
/gate/source/mybeam/gps/hist/point 3.1707110554471 2489.0
/gate/source/mybeam/gps/hist/point 3.2138486180720065 2375.0
/gate/source/mybeam/gps/hist/point 3.256986180696913 2339.0
/gate/source/mybeam/gps/hist/point 3.3001237433218193 2287.0
/gate/source/mybeam/gps/hist/point 3.3432613059467258 2150.0
/gate/source/mybeam/gps/hist/point 3.386398868571632 2078.0
/gate/source/mybeam/gps/hist/point 3.4295364311965386 2024.0
/gate/source/mybeam/gps/hist/point 3.472673993821445 2037.0
/gate/source/mybeam/gps/hist/point 3.5158115564463515 1860.0
/gate/source/mybeam/gps/hist/point 3.558949119071258 1813.0
/gate/source/mybeam/gps/hist/point 3.6020866816961643 1794.0
/gate/source/mybeam/gps/hist/point 3.6452242443210707 1709.0
/gate/source/mybeam/gps/hist/point 3.688361806945977 1670.0
/gate/source/mybeam/gps/hist/point 3.7314993695708836 1542.0
/gate/source/mybeam/gps/hist/point 3.77463693219579 1463.0
/gate/source/mybeam/gps/hist/point 3.8177744948206964 1471.0
/gate/source/mybeam/gps/hist/point 3.860912057445603 1369.0
/gate/source/mybeam/gps/hist/point 3.9040496200705093 1272.0
/gate/source/mybeam/gps/hist/point 3.9471871826954157 1237.0
/gate/source/mybeam/gps/hist/point 3.990324745320322 1203.0
/gate/source/mybeam/gps/hist/point 4.0334623079452285 1139.0
/gate/source/mybeam/gps/hist/point 4.076599870570135 1085.0
/gate/source/mybeam/gps/hist/point 4.119737433195041 1049.0
/gate/source/mybeam/gps/hist/point 4.162874995819948 1023.0
/gate/source/mybeam/gps/hist/point 4.206012558444854 921.0
/gate/source/mybeam/gps/hist/point 4.249150121069761 937.0
/gate/source/mybeam/gps/hist/point 4.292287683694667 840.0
/gate/source/mybeam/gps/hist/point 4.3354252463195735 808.0
/gate/source/mybeam/gps/hist/point 4.37856280894448 827.0
/gate/source/mybeam/gps/hist/point 4.421700371569386 675.0
/gate/source/mybeam/gps/hist/point 4.464837934194293 685.0
/gate/source/mybeam/gps/hist/point 4.507975496819199 623.0
/gate/source/mybeam/gps/hist/point 4.551113059444106 718.0
/gate/source/mybeam/gps/hist/point 4.594250622069012 617.0
/gate/source/mybeam/gps/hist/point 4.6373881846939184 568.0
/gate/source/mybeam/gps/hist/point 4.680525747318825 568.0
/gate/source/mybeam/gps/hist/point 4.723663309943731 510.0
/gate/source/mybeam/gps/hist/point 4.766800872568638 483.0
/gate/source/mybeam/gps/hist/point 4.809938435193544 459.0
/gate/source/mybeam/gps/hist/point 4.853075997818451 468.0
/gate/source/mybeam/gps/hist/point 4.896213560443357 406.0
/gate/source/mybeam/gps/hist/point 4.939351123068263 387.0
/gate/source/mybeam/gps/hist/point 4.98248868569317 369.0
/gate/source/mybeam/gps/hist/point 5.025626248318076 343.0
/gate/source/mybeam/gps/hist/point 5.068763810942983 333.0
/gate/source/mybeam/gps/hist/point 5.111901373567889 284.0
/gate/source/mybeam/gps/hist/point 5.1550389361927955 260.0
/gate/source/mybeam/gps/hist/point 5.198176498817702 266.0
/gate/source/mybeam/gps/hist/point 5.241314061442608 222.0
/gate/source/mybeam/gps/hist/point 5.284451624067515 200.0
/gate/source/mybeam/gps/hist/point 5.327589186692421 213.0
/gate/source/mybeam/gps/hist/point 5.370726749317328 201.0
/gate/source/mybeam/gps/hist/point 5.413864311942234 168.0
/gate/source/mybeam/gps/hist/point 5.4570018745671405 174.0
/gate/source/mybeam/gps/hist/point 5.500139437192047 128.0
/gate/source/mybeam/gps/hist/point 5.543276999816953 147.0
/gate/source/mybeam/gps/hist/point 5.58641456244186 138.0
/gate/source/mybeam/gps/hist/point 5.629552125066766 116.0
/gate/source/mybeam/gps/hist/point 5.672689687691673 102.0
/gate/source/mybeam/gps/hist/point 5.715827250316579 86.0
/gate/source/mybeam/gps/hist/point 5.758964812941485 84.0
/gate/source/mybeam/gps/hist/point 5.802102375566392 70.0
/gate/source/mybeam/gps/hist/point 5.845239938191298 69.0
/gate/source/mybeam/gps/hist/point 5.888377500816205 53.0
/gate/source/mybeam/gps/hist/point 5.931515063441111 51.0
/gate/source/mybeam/gps/hist/point 5.9746526260660175 49.0
/gate/source/mybeam/gps/hist/point 6.017790188690924 30.0
/gate/source/mybeam/gps/hist/point 6.06092775131583 43.0
/gate/source/mybeam/gps/hist/point 6.104065313940737 26.0
/gate/source/mybeam/gps/hist/point 6.147202876565643 20.0
/gate/source/mybeam/gps/hist/point 6.19034043919055 17.0
/gate/source/mybeam/gps/hist/point 6.233478001815456 16.0
/gate/source/mybeam/gps/hist/point 6.2766155644403625 7.0
/gate/source/mybeam/gps/hist/point 6.319753127065269 4.0
/gate/source/mybeam/gps/hist/point 6.362890689690175 8.0
/gate/source/mybeam/gps/hist/point 6.406028252315082 5.0
/gate/source/mybeam/gps/hist/point 6.449165814939988 2.0
/gate/source/mybeam/gps/hist/inter Log

#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed {seed}
#1234567890
/gate/application/noGlobalOutput

#/tracking/verbose 2

/gate/application/setTotalNumberOfPrimaries {primaries}
#1000
/gate/application/start
