# INPUTS
# pathOutputDose
# id
# seed 
# primaries
# peakzlength2_um
# peakztrans2_mm
# peakzlength3_um
# peakztrans3_mm
# peakzlength4_um
# peakztrans4_mm
# peak_material

# Gate /home/as17540/linac/mac/Main_PhS2_Elec_Sensor_0.83xSeaLevel_0.mac -a '[id,$PBS_ARRAY_INDEX] [peakzlength2_um,30] [peakztrans2_mm,-5.485] [peakzlength3_um,50] [peakztrans3_mm,-5.475] [peakzlength4_um,70] [peakztrans4_mm,-5.465] [peak_material,Copper] [seed,$RANDOM$RANDOM$RANDOM] [primaries,10783000] [pathOutputDose,/work/as17540/PhaseSpaces/PhS3_Sensor_10x10_Elec/]'

#=====================================================
# VISUALISATION
#=====================================================

#/control/execute mac/visu.mac

# =====================================================
# GEOMETRY
# =====================================================

/gate/geometry/setMaterialDatabase /home/as17540/linac/data/GateMaterials_0.83xSeaLevel.db

# WORLD
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    0.3 m
/gate/world/geometry/setYLength    0.3 m
/gate/world/geometry/setZLength    1 m
/gate/world/vis/setVisible 1

/gate/world/daughters/name                   PhS_Plane_Two
/gate/world/daughters/insert                 box
/gate/PhS_Plane_Two/setMaterial              Vacuum
/gate/PhS_Plane_Two/geometry/setXLength      22 cm
/gate/PhS_Plane_Two/geometry/setYLength      22 cm
/gate/PhS_Plane_Two/geometry/setZLength      1 nm
/gate/PhS_Plane_Two/placement/setTranslation 0.0 0.0 471 mm #(-529)
/gate/PhS_Plane_Two/vis/setColor             cyan
/gate/PhS_Plane_Two/vis/setVisible           1

/gate/world/daughters/name                   Kill_BackPlane
/gate/world/daughters/insert                 box
/gate/Kill_BackPlane/setMaterial                   Air	
/gate/Kill_BackPlane/geometry/setXLength           30 cm
/gate/Kill_BackPlane/geometry/setYLength           30 cm
/gate/Kill_BackPlane/geometry/setZLength           1 nm
/gate/Kill_BackPlane/placement/setTranslation      0.0 0.0 480 mm
/gate/Kill_BackPlane/vis/setColor                  red
/gate/Kill_BackPlane/vis/setVisible                1

/gate/world/daughters/name                   Kill_FrontPlane
/gate/world/daughters/insert                 box
/gate/Kill_FrontPlane/setMaterial                   Air	
/gate/Kill_FrontPlane/geometry/setXLength           30 cm
/gate/Kill_FrontPlane/geometry/setYLength           30 cm
/gate/Kill_FrontPlane/geometry/setZLength           1 nm
/gate/Kill_FrontPlane/placement/setTranslation      0.0 0.0 445 mm
/gate/Kill_FrontPlane/vis/setColor                  red
/gate/Kill_FrontPlane/vis/setVisible                1

/gate/world/daughters/name         epi
/gate/world/daughters/insert       box
/gate/epi/setMaterial                  Silicon
/gate/epi/geometry/setXLength          180.0 mm
/gate/epi/geometry/setYLength          180.0 mm
/gate/epi/geometry/setZLength          0.01 mm
/gate/epi/placement/setTranslation     0 0 449.995 mm
/gate/epi/vis/setVisible               1
/gate/epi/vis/setColor                 yellow
/gate/epi/vis/forceSolid

/gate/world/daughters/name         bulk
/gate/world/daughters/insert       box
/gate/bulk/setMaterial                  Silicon
/gate/bulk/geometry/setXLength          180.0 mm
/gate/bulk/geometry/setYLength          180.0 mm
/gate/bulk/geometry/setZLength          0.6 mm
/gate/bulk/placement/setTranslation     0 0 449.69 mm
/gate/bulk/vis/setVisible               1
/gate/bulk/vis/setColor                 red

/gate/world/daughters/name         peak_air_box 
/gate/world/daughters/insert       box 
/gate/peak_air_box/setMaterial                  Air 
/gate/peak_air_box/geometry/setXLength          200.0 mm 
/gate/peak_air_box/geometry/setYLength          200.0 mm 
/gate/peak_air_box/geometry/setZLength          11 mm 
/gate/peak_air_box/placement/setTranslation     0 0 455.5 mm
/gate/peak_air_box/vis/setVisible               1 
/gate/peak_air_box/vis/setColor                 green
/gate/peak_air_box/vis/forceWireframe

#/gate/peak_air_box/daughters/name         peakLayer1 
#/gate/peak_air_box/daughters/insert       box 
#/gate/peakLayer1/setMaterial                  {peak_material} 
#/gate/peakLayer1/geometry/setXLength          10.0 mm 
#/gate/peakLayer1/geometry/setYLength          10.0 mm 
#/gate/peakLayer1/geometry/setZLength          {peakzlength_um} um 
#/gate/peakLayer1/placement/setTranslation     -5 5 {peakztrans_mm} mm
#/gate/peakLayer1/vis/setVisible               1 
#/gate/peakLayer1/vis/setColor                 grey
#/gate/peakLayer1/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer2 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer2/setMaterial                  {peak_material} 
/gate/peakLayer2/geometry/setXLength          10.0 mm 
/gate/peakLayer2/geometry/setYLength          10.0 mm 
/gate/peakLayer2/geometry/setZLength          {peakzlength2_um} um 
/gate/peakLayer2/placement/setTranslation     5 5 {peakztrans2_mm} mm
/gate/peakLayer2/vis/setVisible               1 
/gate/peakLayer2/vis/setColor                 red
/gate/peakLayer2/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer3 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer3/setMaterial                  {peak_material} 
/gate/peakLayer3/geometry/setXLength          10.0 mm 
/gate/peakLayer3/geometry/setYLength          10.0 mm 
/gate/peakLayer3/geometry/setZLength          {peakzlength3_um} um 
/gate/peakLayer3/placement/setTranslation     -5 -5 {peakztrans3_mm} mm
/gate/peakLayer3/vis/setVisible               1 
/gate/peakLayer3/vis/setColor                 red
/gate/peakLayer3/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer4 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer4/setMaterial                  {peak_material} 
/gate/peakLayer4/geometry/setXLength          10.0 mm 
/gate/peakLayer4/geometry/setYLength          10.0 mm 
/gate/peakLayer4/geometry/setZLength          {peakzlength4_um} um 
/gate/peakLayer4/placement/setTranslation     5 -5 {peakztrans4_mm} mm
/gate/peakLayer4/vis/setVisible               1 
/gate/peakLayer4/vis/setColor                 red
/gate/peakLayer4/vis/forceSolid

# =====================================================
# PHYSICS
# =====================================================

/gate/physics/addPhysicsList emstandard_opt4

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      epi 0.0001 mm 
/gate/physics/Electron/SetCutInRegion   epi 0.0001 mm
/gate/physics/Positron/SetCutInRegion   epi 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      bulk 0.0001 mm
/gate/physics/Electron/SetCutInRegion   bulk 0.0001 mm
/gate/physics/Positron/SetCutInRegion   bulk 0.0001 mm

#/gate/physics/Gamma/SetCutInRegion      peakLayer1 0.0001 mm #0.0001
#/gate/physics/Electron/SetCutInRegion   peakLayer1 0.0001 mm
#/gate/physics/Positron/SetCutInRegion   peakLayer1 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer2 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer2 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer2 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer3 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer3 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer3 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer4 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer4 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer4 0.0001 mm

#=====================================================
# DETECTORS
#=====================================================

## 
## Dose output electron
## 
/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  {pathOutputDose}/Epi-00-{peakzlength2_um}-{peakzlength3_um}-{peakzlength4_um}_peakum-{peak_material}-0.83xSeaLevel-{id}.root
/gate/actor/doseDistribution/attachTo              epi
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setSize               50 50 0.010 mm
/gate/actor/doseDistribution/setResolution         1000 1000 1	 #for 60 micron pixel x4
/gate/actor/doseDistribution/enableNumberOfHits    true
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep false
/gate/actor/doseDistribution/enableSquaredEdep     true
/gate/actor/doseDistribution/enableDose            false
/gate/actor/doseDistribution/enableUncertaintyDose false


/gate/actor/addActor   KillActor                         Kill_BP 
/gate/actor/Kill_BP/attachTo                             Kill_BackPlane 

/gate/actor/addActor   KillActor                         Kill_FP 
/gate/actor/Kill_FP/attachTo                             Kill_FrontPlane 

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize
# /process/em/setBiasingFactor compt 100 True

# /process/em/setSecBiasing compt peakLayer1 100 1000 MeV
# /particle/process/dump

#=====================================================
# BEAMS
#=====================================================

# Read from Phase Space files. Here we indicate the type of particle
# (gamma) because this information is not stored in the PhS to gain
# space. Moreover, we set 'useRandomSymmetry' to generate more
# particle than the number of particle in the PhS, using a Z axis
# symmetry.

#/gate/source/addSource                         beam_g phaseSpace
#/gate/source/beam_g/addPhaseSpaceFile          {inputPhaseSpaceFile}
#{inputParticleType}
#/gate/source/beam_g/attachTo                   PhS_Plane_Two
#/gate/source/beam_g/useRandomSymmetry          true

/gate/source/addSource mybeam gps 
/gate/source/mybeam/gps/particle e- 
/gate/source/mybeam/gps/pos/centre 0 0 471 mm 
/gate/source/mybeam/gps/direction 0 0 -1 
/gate/source/mybeam/gps/type Plane 
/gate/source/mybeam/gps/shape Square 
/gate/source/mybeam/gps/halfx 2 cm 
/gate/source/mybeam/gps/halfy 2 cm 
/gate/source/mybeam/gps/ene/type Arb 
/gate/source/mybeam/gps/hist/type arb 
/gate/source/mybeam/gps/hist/point 0.021850517567339314 15901.0
/gate/source/mybeam/gps/hist/point 0.06534942163729283 21031.0
/gate/source/mybeam/gps/hist/point 0.10884832570724635 25724.0
/gate/source/mybeam/gps/hist/point 0.1523472297771999 27360.0
/gate/source/mybeam/gps/hist/point 0.19584613384715338 27514.0
/gate/source/mybeam/gps/hist/point 0.23934503791710693 27501.0
/gate/source/mybeam/gps/hist/point 0.2828439419870604 26211.0
/gate/source/mybeam/gps/hist/point 0.32634284605701397 25025.0
/gate/source/mybeam/gps/hist/point 0.36984175012696746 24206.0
/gate/source/mybeam/gps/hist/point 0.413340654196921 23215.0
/gate/source/mybeam/gps/hist/point 0.4568395582668745 21740.0
/gate/source/mybeam/gps/hist/point 0.5003384623368281 21056.0
/gate/source/mybeam/gps/hist/point 0.5438373664067815 19849.0
/gate/source/mybeam/gps/hist/point 0.5873362704767351 19029.0
/gate/source/mybeam/gps/hist/point 0.6308351745466887 18255.0
/gate/source/mybeam/gps/hist/point 0.6743340786166421 17714.0
/gate/source/mybeam/gps/hist/point 0.7178329826865957 17018.0
/gate/source/mybeam/gps/hist/point 0.7613318867565491 16498.0
/gate/source/mybeam/gps/hist/point 0.8048307908265027 15628.0
/gate/source/mybeam/gps/hist/point 0.8483296948964563 15455.0
/gate/source/mybeam/gps/hist/point 0.8918285989664096 14617.0
/gate/source/mybeam/gps/hist/point 0.9353275030363633 13952.0
/gate/source/mybeam/gps/hist/point 0.9788264071063167 13470.0
/gate/source/mybeam/gps/hist/point 1.0223253111762702 13060.0
/gate/source/mybeam/gps/hist/point 1.0658242152462238 12770.0
/gate/source/mybeam/gps/hist/point 1.1093231193161772 12104.0
/gate/source/mybeam/gps/hist/point 1.1528220233861308 11559.0
/gate/source/mybeam/gps/hist/point 1.1963209274560844 11339.0
/gate/source/mybeam/gps/hist/point 1.239819831526038 11063.0
/gate/source/mybeam/gps/hist/point 1.2833187355959914 10572.0
/gate/source/mybeam/gps/hist/point 1.3268176396659448 10272.0
/gate/source/mybeam/gps/hist/point 1.3703165437358984 9966.0
/gate/source/mybeam/gps/hist/point 1.413815447805852 9628.0
/gate/source/mybeam/gps/hist/point 1.4573143518758056 9358.0
/gate/source/mybeam/gps/hist/point 1.500813255945759 9021.0
/gate/source/mybeam/gps/hist/point 1.5443121600157124 8782.0
/gate/source/mybeam/gps/hist/point 1.587811064085666 8530.0
/gate/source/mybeam/gps/hist/point 1.6313099681556196 8084.0
/gate/source/mybeam/gps/hist/point 1.6748088722255732 7930.0
/gate/source/mybeam/gps/hist/point 1.7183077762955266 7715.0
/gate/source/mybeam/gps/hist/point 1.7618066803654802 7535.0
/gate/source/mybeam/gps/hist/point 1.8053055844354335 7121.0
/gate/source/mybeam/gps/hist/point 1.8488044885053871 7043.0
/gate/source/mybeam/gps/hist/point 1.8923033925753407 6786.0
/gate/source/mybeam/gps/hist/point 1.9358022966452944 6460.0
/gate/source/mybeam/gps/hist/point 1.9793012007152475 6300.0
/gate/source/mybeam/gps/hist/point 2.022800104785201 6103.0
/gate/source/mybeam/gps/hist/point 2.0662990088551547 5910.0
/gate/source/mybeam/gps/hist/point 2.1097979129251083 5818.0
/gate/source/mybeam/gps/hist/point 2.153296816995062 5487.0
/gate/source/mybeam/gps/hist/point 2.1967957210650155 5450.0
/gate/source/mybeam/gps/hist/point 2.2402946251349687 5199.0
/gate/source/mybeam/gps/hist/point 2.2837935292049223 5129.0
/gate/source/mybeam/gps/hist/point 2.327292433274876 4894.0
/gate/source/mybeam/gps/hist/point 2.3707913373448295 4802.0
/gate/source/mybeam/gps/hist/point 2.414290241414783 4554.0
/gate/source/mybeam/gps/hist/point 2.4577891454847363 4563.0
/gate/source/mybeam/gps/hist/point 2.50128804955469 4275.0
/gate/source/mybeam/gps/hist/point 2.5447869536246435 4152.0
/gate/source/mybeam/gps/hist/point 2.588285857694597 4158.0
/gate/source/mybeam/gps/hist/point 2.6317847617645507 3881.0
/gate/source/mybeam/gps/hist/point 2.6752836658345043 3800.0
/gate/source/mybeam/gps/hist/point 2.7187825699044574 3709.0
/gate/source/mybeam/gps/hist/point 2.762281473974411 3617.0
/gate/source/mybeam/gps/hist/point 2.8057803780443646 3396.0
/gate/source/mybeam/gps/hist/point 2.8492792821143182 3312.0
/gate/source/mybeam/gps/hist/point 2.8927781861842714 3238.0
/gate/source/mybeam/gps/hist/point 2.936277090254225 3068.0
/gate/source/mybeam/gps/hist/point 2.9797759943241786 2987.0
/gate/source/mybeam/gps/hist/point 3.023274898394132 2912.0
/gate/source/mybeam/gps/hist/point 3.066773802464086 2792.0
/gate/source/mybeam/gps/hist/point 3.1102727065340394 2585.0
/gate/source/mybeam/gps/hist/point 3.1537716106039926 2599.0
/gate/source/mybeam/gps/hist/point 3.197270514673946 2520.0
/gate/source/mybeam/gps/hist/point 3.2407694187439 2452.0
/gate/source/mybeam/gps/hist/point 3.2842683228138534 2394.0
/gate/source/mybeam/gps/hist/point 3.327767226883807 2240.0
/gate/source/mybeam/gps/hist/point 3.37126613095376 2247.0
/gate/source/mybeam/gps/hist/point 3.4147650350237138 2016.0
/gate/source/mybeam/gps/hist/point 3.4582639390936674 2011.0
/gate/source/mybeam/gps/hist/point 3.501762843163621 1875.0
/gate/source/mybeam/gps/hist/point 3.5452617472335746 1872.0
/gate/source/mybeam/gps/hist/point 3.588760651303528 1790.0
/gate/source/mybeam/gps/hist/point 3.6322595553734813 1766.0
/gate/source/mybeam/gps/hist/point 3.675758459443435 1639.0
/gate/source/mybeam/gps/hist/point 3.7192573635133885 1514.0
/gate/source/mybeam/gps/hist/point 3.762756267583342 1500.0
/gate/source/mybeam/gps/hist/point 3.8062551716532957 1421.0
/gate/source/mybeam/gps/hist/point 3.849754075723249 1407.0
/gate/source/mybeam/gps/hist/point 3.8932529797932025 1294.0
/gate/source/mybeam/gps/hist/point 3.936751883863156 1221.0
/gate/source/mybeam/gps/hist/point 3.9802507879331097 1214.0
/gate/source/mybeam/gps/hist/point 4.023749692003063 1140.0
/gate/source/mybeam/gps/hist/point 4.067248596073016 1098.0
/gate/source/mybeam/gps/hist/point 4.1107475001429705 1046.0
/gate/source/mybeam/gps/hist/point 4.154246404212923 1027.0
/gate/source/mybeam/gps/hist/point 4.197745308282878 964.0
/gate/source/mybeam/gps/hist/point 4.2412442123528304 874.0
/gate/source/mybeam/gps/hist/point 4.284743116422785 891.0
/gate/source/mybeam/gps/hist/point 4.328242020492738 797.0
/gate/source/mybeam/gps/hist/point 4.371740924562692 813.0
/gate/source/mybeam/gps/hist/point 4.415239828632645 738.0
/gate/source/mybeam/gps/hist/point 4.458738732702598 676.0
/gate/source/mybeam/gps/hist/point 4.502237636772552 674.0
/gate/source/mybeam/gps/hist/point 4.545736540842505 617.0
/gate/source/mybeam/gps/hist/point 4.589235444912459 634.0
/gate/source/mybeam/gps/hist/point 4.632734348982412 635.0
/gate/source/mybeam/gps/hist/point 4.6762332530523665 544.0
/gate/source/mybeam/gps/hist/point 4.719732157122319 539.0
/gate/source/mybeam/gps/hist/point 4.763231061192274 464.0
/gate/source/mybeam/gps/hist/point 4.806729965262226 474.0
/gate/source/mybeam/gps/hist/point 4.850228869332181 419.0
/gate/source/mybeam/gps/hist/point 4.893727773402134 419.0
/gate/source/mybeam/gps/hist/point 4.937226677472086 395.0
/gate/source/mybeam/gps/hist/point 4.980725581542041 381.0
/gate/source/mybeam/gps/hist/point 5.0242244856119935 385.0
/gate/source/mybeam/gps/hist/point 5.067723389681948 356.0
/gate/source/mybeam/gps/hist/point 5.111222293751901 275.0
/gate/source/mybeam/gps/hist/point 5.154721197821855 292.0
/gate/source/mybeam/gps/hist/point 5.198220101891808 260.0
/gate/source/mybeam/gps/hist/point 5.241719005961762 252.0
/gate/source/mybeam/gps/hist/point 5.285217910031715 228.0
/gate/source/mybeam/gps/hist/point 5.328716814101669 212.0
/gate/source/mybeam/gps/hist/point 5.372215718171622 175.0
/gate/source/mybeam/gps/hist/point 5.415714622241575 169.0
/gate/source/mybeam/gps/hist/point 5.45921352631153 145.0
/gate/source/mybeam/gps/hist/point 5.502712430381482 139.0
/gate/source/mybeam/gps/hist/point 5.546211334451437 141.0
/gate/source/mybeam/gps/hist/point 5.5897102385213895 141.0
/gate/source/mybeam/gps/hist/point 5.633209142591344 109.0
/gate/source/mybeam/gps/hist/point 5.676708046661297 98.0
/gate/source/mybeam/gps/hist/point 5.720206950731251 93.0
/gate/source/mybeam/gps/hist/point 5.763705854801204 82.0
/gate/source/mybeam/gps/hist/point 5.8072047588711575 63.0
/gate/source/mybeam/gps/hist/point 5.850703662941111 64.0
/gate/source/mybeam/gps/hist/point 5.894202567011064 52.0
/gate/source/mybeam/gps/hist/point 5.937701471081018 44.0
/gate/source/mybeam/gps/hist/point 5.981200375150971 51.0
/gate/source/mybeam/gps/hist/point 6.0246992792209255 37.0
/gate/source/mybeam/gps/hist/point 6.068198183290878 34.0
/gate/source/mybeam/gps/hist/point 6.111697087360833 26.0
/gate/source/mybeam/gps/hist/point 6.155195991430785 22.0
/gate/source/mybeam/gps/hist/point 6.19869489550074 13.0
/gate/source/mybeam/gps/hist/point 6.242193799570693 9.0
/gate/source/mybeam/gps/hist/point 6.285692703640645 15.0
/gate/source/mybeam/gps/hist/point 6.3291916077106 4.0
/gate/source/mybeam/gps/hist/point 6.372690511780553 5.0
/gate/source/mybeam/gps/hist/point 6.416189415850507 0.0
/gate/source/mybeam/gps/hist/point 6.45968831992046 0.0
/gate/source/mybeam/gps/hist/point 6.503187223990414 1.0
/gate/source/mybeam/gps/hist/inter Log

#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed {seed}
#1234567890
/gate/application/noGlobalOutput

#/tracking/verbose 2

/gate/application/setTotalNumberOfPrimaries {primaries}
#1000
/gate/application/start
