# INPUTS
# pathOutputDose
# id
# seed 
# primaries
# peakzlength_um
# peakztrans_mm
# peakzlength2_um
# peakztrans2_mm
# peakzlength3_um
# peakztrans3_mm
# peakzlength4_um
# peakztrans4_mm
# peak_material

# Gate /home/as17540/linac/mac/Main_PhS2_Elec_Sensor_0.5xSeaLevel.mac -a '[id,$PBS_ARRAY_INDEX] [peakzlength_um,10] [peakztrans_mm,-5.495] [peakzlength2_um,30] [peakztrans2_mm,-5.485] [peakzlength3_um,50] [peakztrans3_mm,-5.475] [peakzlength4_um,70] [peakztrans4_mm,-5.465] [peak_material,Copper] [seed,$RANDOM$RANDOM$RANDOM] [primaries,10279100] [pathOutputDose,/work/as17540/PhaseSpaces/PhS3_Sensor_10x10_Elec/]'

#=====================================================
# VISUALISATION
#=====================================================

#/control/execute mac/visu.mac

# =====================================================
# GEOMETRY
# =====================================================

/gate/geometry/setMaterialDatabase /home/as17540/linac/data/GateMaterials_0.539xSeaLevel.db

# WORLD
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    0.3 m
/gate/world/geometry/setYLength    0.3 m
/gate/world/geometry/setZLength    1 m
/gate/world/vis/setVisible 1

/gate/world/daughters/name                   PhS_Plane_Two
/gate/world/daughters/insert                 box
/gate/PhS_Plane_Two/setMaterial              Vacuum
/gate/PhS_Plane_Two/geometry/setXLength      22 cm
/gate/PhS_Plane_Two/geometry/setYLength      22 cm
/gate/PhS_Plane_Two/geometry/setZLength      1 nm
/gate/PhS_Plane_Two/placement/setTranslation 0.0 0.0 471 mm #(-529)
/gate/PhS_Plane_Two/vis/setColor             cyan
/gate/PhS_Plane_Two/vis/setVisible           1

/gate/world/daughters/name                   Kill_BackPlane
/gate/world/daughters/insert                 box
/gate/Kill_BackPlane/setMaterial                   Air	
/gate/Kill_BackPlane/geometry/setXLength           30 cm
/gate/Kill_BackPlane/geometry/setYLength           30 cm
/gate/Kill_BackPlane/geometry/setZLength           1 nm
/gate/Kill_BackPlane/placement/setTranslation      0.0 0.0 480 mm
/gate/Kill_BackPlane/vis/setColor                  red
/gate/Kill_BackPlane/vis/setVisible                1

/gate/world/daughters/name                   Kill_FrontPlane
/gate/world/daughters/insert                 box
/gate/Kill_FrontPlane/setMaterial                   Air	
/gate/Kill_FrontPlane/geometry/setXLength           30 cm
/gate/Kill_FrontPlane/geometry/setYLength           30 cm
/gate/Kill_FrontPlane/geometry/setZLength           1 nm
/gate/Kill_FrontPlane/placement/setTranslation      0.0 0.0 445 mm
/gate/Kill_FrontPlane/vis/setColor                  red
/gate/Kill_FrontPlane/vis/setVisible                1

/gate/world/daughters/name         epi
/gate/world/daughters/insert       box
/gate/epi/setMaterial                  Silicon
/gate/epi/geometry/setXLength          180.0 mm
/gate/epi/geometry/setYLength          180.0 mm
/gate/epi/geometry/setZLength          0.01 mm
/gate/epi/placement/setTranslation     0 0 449.995 mm
/gate/epi/vis/setVisible               1
/gate/epi/vis/setColor                 yellow
/gate/epi/vis/forceSolid

/gate/world/daughters/name         bulk
/gate/world/daughters/insert       box
/gate/bulk/setMaterial                  Silicon
/gate/bulk/geometry/setXLength          180.0 mm
/gate/bulk/geometry/setYLength          180.0 mm
/gate/bulk/geometry/setZLength          0.6 mm
/gate/bulk/placement/setTranslation     0 0 449.69 mm
/gate/bulk/vis/setVisible               1
/gate/bulk/vis/setColor                 red

/gate/world/daughters/name         peak_air_box 
/gate/world/daughters/insert       box 
/gate/peak_air_box/setMaterial                  Air 
/gate/peak_air_box/geometry/setXLength          200.0 mm 
/gate/peak_air_box/geometry/setYLength          200.0 mm 
/gate/peak_air_box/geometry/setZLength          11 mm 
/gate/peak_air_box/placement/setTranslation     0 0 455.5 mm
/gate/peak_air_box/vis/setVisible               1 
/gate/peak_air_box/vis/setColor                 green
/gate/peak_air_box/vis/forceWireframe

/gate/peak_air_box/daughters/name         peakLayer1 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer1/setMaterial                  {peak_material} 
/gate/peakLayer1/geometry/setXLength          10.0 mm 
/gate/peakLayer1/geometry/setYLength          10.0 mm 
/gate/peakLayer1/geometry/setZLength          {peakzlength_um} um 
/gate/peakLayer1/placement/setTranslation     -5 5 {peakztrans_mm} mm
/gate/peakLayer1/vis/setVisible               1 
/gate/peakLayer1/vis/setColor                 grey
/gate/peakLayer1/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer2 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer2/setMaterial                  {peak_material} 
/gate/peakLayer2/geometry/setXLength          10.0 mm 
/gate/peakLayer2/geometry/setYLength          10.0 mm 
/gate/peakLayer2/geometry/setZLength          {peakzlength2_um} um 
/gate/peakLayer2/placement/setTranslation     5 5 {peakztrans2_mm} mm
/gate/peakLayer2/vis/setVisible               1 
/gate/peakLayer2/vis/setColor                 red
/gate/peakLayer2/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer3 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer3/setMaterial                  {peak_material} 
/gate/peakLayer3/geometry/setXLength          10.0 mm 
/gate/peakLayer3/geometry/setYLength          10.0 mm 
/gate/peakLayer3/geometry/setZLength          {peakzlength3_um} um 
/gate/peakLayer3/placement/setTranslation     -5 -5 {peakztrans3_mm} mm
/gate/peakLayer3/vis/setVisible               1 
/gate/peakLayer3/vis/setColor                 red
/gate/peakLayer3/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer4 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer4/setMaterial                  {peak_material} 
/gate/peakLayer4/geometry/setXLength          10.0 mm 
/gate/peakLayer4/geometry/setYLength          10.0 mm 
/gate/peakLayer4/geometry/setZLength          {peakzlength4_um} um 
/gate/peakLayer4/placement/setTranslation     5 -5 {peakztrans4_mm} mm
/gate/peakLayer4/vis/setVisible               1 
/gate/peakLayer4/vis/setColor                 red
/gate/peakLayer4/vis/forceSolid

# =====================================================
# PHYSICS
# =====================================================

/gate/physics/addPhysicsList emstandard_opt4

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      epi 0.0001 mm 
/gate/physics/Electron/SetCutInRegion   epi 0.0001 mm
/gate/physics/Positron/SetCutInRegion   epi 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      bulk 0.0001 mm
/gate/physics/Electron/SetCutInRegion   bulk 0.0001 mm
/gate/physics/Positron/SetCutInRegion   bulk 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer1 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer1 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer1 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer2 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer2 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer2 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer3 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer3 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer3 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer4 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer4 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer4 0.0001 mm

#=====================================================
# DETECTORS
#=====================================================

## 
## Dose output electron
## 
/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  {pathOutputDose}/Epi-{peakzlength_um}-{peakzlength2_um}-{peakzlength3_um}-{peakzlength4_um}_peakum-{peak_material}-0.539xSeaLevel-{id}.root
/gate/actor/doseDistribution/attachTo              epi
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setSize               50 50 0.010 mm
/gate/actor/doseDistribution/setResolution         1000 1000 1	 #for 60 micron pixel x4
/gate/actor/doseDistribution/enableNumberOfHits    true
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep false
/gate/actor/doseDistribution/enableSquaredEdep     true
/gate/actor/doseDistribution/enableDose            false
/gate/actor/doseDistribution/enableUncertaintyDose false


/gate/actor/addActor   KillActor                         Kill_BP 
/gate/actor/Kill_BP/attachTo                             Kill_BackPlane 

/gate/actor/addActor   KillActor                         Kill_FP 
/gate/actor/Kill_FP/attachTo                             Kill_FrontPlane 

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize
# /process/em/setBiasingFactor compt 100 True

# /process/em/setSecBiasing compt peakLayer1 100 1000 MeV
# /particle/process/dump

#=====================================================
# BEAMS
#=====================================================

# Read from Phase Space files. Here we indicate the type of particle
# (gamma) because this information is not stored in the PhS to gain
# space. Moreover, we set 'useRandomSymmetry' to generate more
# particle than the number of particle in the PhS, using a Z axis
# symmetry.

#/gate/source/addSource                         beam_g phaseSpace
#/gate/source/beam_g/addPhaseSpaceFile          {inputPhaseSpaceFile}
#{inputParticleType}
#/gate/source/beam_g/attachTo                   PhS_Plane_Two
#/gate/source/beam_g/useRandomSymmetry          true

/gate/source/addSource mybeam gps 
/gate/source/mybeam/gps/particle e- 
/gate/source/mybeam/gps/pos/centre 0 0 471 mm 
/gate/source/mybeam/gps/direction 0 0 -1 
/gate/source/mybeam/gps/type Plane 
/gate/source/mybeam/gps/shape Square 
/gate/source/mybeam/gps/halfx 2 cm 
/gate/source/mybeam/gps/halfy 2 cm 
/gate/source/mybeam/gps/ene/type Arb 
/gate/source/mybeam/gps/hist/type arb 
/gate/source/mybeam/gps/hist/point 0.021749719130869684 15125.0
/gate/source/mybeam/gps/hist/point 0.0650483177521528 19990.0
/gate/source/mybeam/gps/hist/point 0.10834691637343592 23680.0
/gate/source/mybeam/gps/hist/point 0.15164551499471904 25524.0
/gate/source/mybeam/gps/hist/point 0.19494411361600214 25920.0
/gate/source/mybeam/gps/hist/point 0.23824271223728527 24999.0
/gate/source/mybeam/gps/hist/point 0.28154131085856837 24602.0
/gate/source/mybeam/gps/hist/point 0.32483990947985153 23252.0
/gate/source/mybeam/gps/hist/point 0.3681385081011346 21934.0
/gate/source/mybeam/gps/hist/point 0.41143710672241773 21305.0
/gate/source/mybeam/gps/hist/point 0.45473570534370084 19892.0
/gate/source/mybeam/gps/hist/point 0.498034303964984 19067.0
/gate/source/mybeam/gps/hist/point 0.5413329025862671 18196.0
/gate/source/mybeam/gps/hist/point 0.5846315012075503 17405.0
/gate/source/mybeam/gps/hist/point 0.6279300998288333 16922.0
/gate/source/mybeam/gps/hist/point 0.6712286984501163 16326.0
/gate/source/mybeam/gps/hist/point 0.7145272970713996 15510.0
/gate/source/mybeam/gps/hist/point 0.7578258956926827 15012.0
/gate/source/mybeam/gps/hist/point 0.8011244943139657 14395.0
/gate/source/mybeam/gps/hist/point 0.8444230929352489 13953.0
/gate/source/mybeam/gps/hist/point 0.887721691556532 13323.0
/gate/source/mybeam/gps/hist/point 0.9310202901778151 12694.0
/gate/source/mybeam/gps/hist/point 0.9743188887990982 12315.0
/gate/source/mybeam/gps/hist/point 1.0176174874203814 12031.0
/gate/source/mybeam/gps/hist/point 1.0609160860416647 11705.0
/gate/source/mybeam/gps/hist/point 1.1042146846629475 11305.0
/gate/source/mybeam/gps/hist/point 1.1475132832842307 10883.0
/gate/source/mybeam/gps/hist/point 1.1908118819055138 10507.0
/gate/source/mybeam/gps/hist/point 1.2341104805267968 10315.0
/gate/source/mybeam/gps/hist/point 1.27740907914808 9665.0
/gate/source/mybeam/gps/hist/point 1.3207076777693632 9652.0
/gate/source/mybeam/gps/hist/point 1.3640062763906462 9208.0
/gate/source/mybeam/gps/hist/point 1.4073048750119295 8934.0
/gate/source/mybeam/gps/hist/point 1.4506034736332125 8344.0
/gate/source/mybeam/gps/hist/point 1.4939020722544956 8460.0
/gate/source/mybeam/gps/hist/point 1.5372006708757788 8252.0
/gate/source/mybeam/gps/hist/point 1.5804992694970619 7928.0
/gate/source/mybeam/gps/hist/point 1.623797868118345 7490.0
/gate/source/mybeam/gps/hist/point 1.6670964667396282 7377.0
/gate/source/mybeam/gps/hist/point 1.710395065360911 7142.0
/gate/source/mybeam/gps/hist/point 1.7536936639821943 6904.0
/gate/source/mybeam/gps/hist/point 1.7969922626034776 6755.0
/gate/source/mybeam/gps/hist/point 1.8402908612247604 6841.0
/gate/source/mybeam/gps/hist/point 1.8835894598460436 6312.0
/gate/source/mybeam/gps/hist/point 1.926888058467327 6219.0
/gate/source/mybeam/gps/hist/point 1.9701866570886097 6059.0
/gate/source/mybeam/gps/hist/point 2.013485255709893 5577.0
/gate/source/mybeam/gps/hist/point 2.0567838543311763 5552.0
/gate/source/mybeam/gps/hist/point 2.100082452952459 5278.0
/gate/source/mybeam/gps/hist/point 2.1433810515737424 5126.0
/gate/source/mybeam/gps/hist/point 2.1866796501950256 5118.0
/gate/source/mybeam/gps/hist/point 2.2299782488163085 4894.0
/gate/source/mybeam/gps/hist/point 2.2732768474375917 4671.0
/gate/source/mybeam/gps/hist/point 2.3165754460588746 4683.0
/gate/source/mybeam/gps/hist/point 2.359874044680158 4418.0
/gate/source/mybeam/gps/hist/point 2.403172643301441 4345.0
/gate/source/mybeam/gps/hist/point 2.4464712419227244 4147.0
/gate/source/mybeam/gps/hist/point 2.489769840544007 4085.0
/gate/source/mybeam/gps/hist/point 2.5330684391652905 3970.0
/gate/source/mybeam/gps/hist/point 2.5763670377865733 3781.0
/gate/source/mybeam/gps/hist/point 2.6196656364078565 3659.0
/gate/source/mybeam/gps/hist/point 2.66296423502914 3616.0
/gate/source/mybeam/gps/hist/point 2.706262833650423 3419.0
/gate/source/mybeam/gps/hist/point 2.749561432271706 3304.0
/gate/source/mybeam/gps/hist/point 2.792860030892989 3231.0
/gate/source/mybeam/gps/hist/point 2.836158629514272 3169.0
/gate/source/mybeam/gps/hist/point 2.8794572281355553 3022.0
/gate/source/mybeam/gps/hist/point 2.9227558267568385 2911.0
/gate/source/mybeam/gps/hist/point 2.966054425378122 2842.0
/gate/source/mybeam/gps/hist/point 3.0093530239994046 2814.0
/gate/source/mybeam/gps/hist/point 3.052651622620688 2683.0
/gate/source/mybeam/gps/hist/point 3.0959502212419707 2577.0
/gate/source/mybeam/gps/hist/point 3.139248819863254 2408.0
/gate/source/mybeam/gps/hist/point 3.1825474184845373 2363.0
/gate/source/mybeam/gps/hist/point 3.2258460171058205 2258.0
/gate/source/mybeam/gps/hist/point 3.2691446157271034 2182.0
/gate/source/mybeam/gps/hist/point 3.3124432143483866 2156.0
/gate/source/mybeam/gps/hist/point 3.3557418129696694 2006.0
/gate/source/mybeam/gps/hist/point 3.3990404115909527 2024.0
/gate/source/mybeam/gps/hist/point 3.442339010212236 1911.0
/gate/source/mybeam/gps/hist/point 3.485637608833519 1845.0
/gate/source/mybeam/gps/hist/point 3.528936207454802 1791.0
/gate/source/mybeam/gps/hist/point 3.572234806076085 1627.0
/gate/source/mybeam/gps/hist/point 3.615533404697368 1623.0
/gate/source/mybeam/gps/hist/point 3.6588320033186514 1471.0
/gate/source/mybeam/gps/hist/point 3.7021306019399347 1470.0
/gate/source/mybeam/gps/hist/point 3.7454292005612175 1377.0
/gate/source/mybeam/gps/hist/point 3.788727799182501 1412.0
/gate/source/mybeam/gps/hist/point 3.8320263978037836 1277.0
/gate/source/mybeam/gps/hist/point 3.875324996425067 1254.0
/gate/source/mybeam/gps/hist/point 3.91862359504635 1152.0
/gate/source/mybeam/gps/hist/point 3.9619221936676334 1088.0
/gate/source/mybeam/gps/hist/point 4.005220792288917 1091.0
/gate/source/mybeam/gps/hist/point 4.048519390910199 1022.0
/gate/source/mybeam/gps/hist/point 4.091817989531483 944.0
/gate/source/mybeam/gps/hist/point 4.135116588152766 957.0
/gate/source/mybeam/gps/hist/point 4.178415186774049 869.0
/gate/source/mybeam/gps/hist/point 4.221713785395332 817.0
/gate/source/mybeam/gps/hist/point 4.2650123840166145 800.0
/gate/source/mybeam/gps/hist/point 4.308310982637899 781.0
/gate/source/mybeam/gps/hist/point 4.351609581259181 759.0
/gate/source/mybeam/gps/hist/point 4.394908179880464 691.0
/gate/source/mybeam/gps/hist/point 4.438206778501748 684.0
/gate/source/mybeam/gps/hist/point 4.48150537712303 688.0
/gate/source/mybeam/gps/hist/point 4.524803975744314 568.0
/gate/source/mybeam/gps/hist/point 4.5681025743655965 607.0
/gate/source/mybeam/gps/hist/point 4.611401172986881 528.0
/gate/source/mybeam/gps/hist/point 4.654699771608163 464.0
/gate/source/mybeam/gps/hist/point 4.697998370229445 496.0
/gate/source/mybeam/gps/hist/point 4.74129696885073 464.0
/gate/source/mybeam/gps/hist/point 4.784595567472012 444.0
/gate/source/mybeam/gps/hist/point 4.827894166093296 394.0
/gate/source/mybeam/gps/hist/point 4.8711927647145785 395.0
/gate/source/mybeam/gps/hist/point 4.914491363335862 345.0
/gate/source/mybeam/gps/hist/point 4.957789961957145 316.0
/gate/source/mybeam/gps/hist/point 5.001088560578427 311.0
/gate/source/mybeam/gps/hist/point 5.044387159199712 317.0
/gate/source/mybeam/gps/hist/point 5.087685757820994 275.0
/gate/source/mybeam/gps/hist/point 5.130984356442278 269.0
/gate/source/mybeam/gps/hist/point 5.1742829550635605 258.0
/gate/source/mybeam/gps/hist/point 5.217581553684843 222.0
/gate/source/mybeam/gps/hist/point 5.260880152306127 241.0
/gate/source/mybeam/gps/hist/point 5.304178750927409 192.0
/gate/source/mybeam/gps/hist/point 5.347477349548694 166.0
/gate/source/mybeam/gps/hist/point 5.390775948169976 206.0
/gate/source/mybeam/gps/hist/point 5.434074546791259 171.0
/gate/source/mybeam/gps/hist/point 5.4773731454125425 128.0
/gate/source/mybeam/gps/hist/point 5.520671744033825 120.0
/gate/source/mybeam/gps/hist/point 5.563970342655109 114.0
/gate/source/mybeam/gps/hist/point 5.607268941276391 87.0
/gate/source/mybeam/gps/hist/point 5.650567539897675 80.0
/gate/source/mybeam/gps/hist/point 5.693866138518958 92.0
/gate/source/mybeam/gps/hist/point 5.73716473714024 87.0
/gate/source/mybeam/gps/hist/point 5.7804633357615245 67.0
/gate/source/mybeam/gps/hist/point 5.823761934382807 55.0
/gate/source/mybeam/gps/hist/point 5.867060533004091 59.0
/gate/source/mybeam/gps/hist/point 5.910359131625373 47.0
/gate/source/mybeam/gps/hist/point 5.953657730246656 28.0
/gate/source/mybeam/gps/hist/point 5.99695632886794 33.0
/gate/source/mybeam/gps/hist/point 6.040254927489222 17.0
/gate/source/mybeam/gps/hist/point 6.0835535261105065 20.0
/gate/source/mybeam/gps/hist/point 6.126852124731789 18.0
/gate/source/mybeam/gps/hist/point 6.170150723353072 13.0
/gate/source/mybeam/gps/hist/point 6.213449321974355 16.0
/gate/source/mybeam/gps/hist/point 6.256747920595638 11.0
/gate/source/mybeam/gps/hist/point 6.300046519216922 7.0
/gate/source/mybeam/gps/hist/point 6.343345117838204 3.0
/gate/source/mybeam/gps/hist/point 6.3866437164594885 7.0
/gate/source/mybeam/gps/hist/point 6.429942315080771 3.0
/gate/source/mybeam/gps/hist/point 6.473240913702053 1.0
/gate/source/mybeam/gps/hist/inter Log

#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed {seed}
#1234567890
/gate/application/noGlobalOutput

#/tracking/verbose 2

/gate/application/setTotalNumberOfPrimaries {primaries}
#1000
/gate/application/start
