# INPUTS
# pathOutputDose
# id
# seed 
# primaries
# peakzlength_um
# peakztrans_mm
# peakzlength2_um
# peakztrans2_mm
# peakzlength3_um
# peakztrans3_mm
# peakzlength4_um
# peakztrans4_mm
# peak_material

# Gate /home/as17540/linac/mac/Main_PhS2_Elec_Sensor_0.87xSeaLevel.mac -a '[id,$PBS_ARRAY_INDEX] [peakzlength_um,10] [peakztrans_mm,-5.495] [peakzlength2_um,30] [peakztrans2_mm,-5.485] [peakzlength3_um,50] [peakztrans3_mm,-5.475] [peakzlength4_um,70] [peakztrans4_mm,-5.465] [peak_material,Copper] [seed,$RANDOM$RANDOM$RANDOM] [primaries,10783000] [pathOutputDose,/work/as17540/PhaseSpaces/PhS3_Sensor_10x10_Elec/]'

#=====================================================
# VISUALISATION
#=====================================================

#/control/execute mac/visu.mac

# =====================================================
# GEOMETRY
# =====================================================

/gate/geometry/setMaterialDatabase /home/as17540/linac/data/GateMaterials_0.87xSeaLevel.db

# WORLD
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    0.3 m
/gate/world/geometry/setYLength    0.3 m
/gate/world/geometry/setZLength    1 m
/gate/world/vis/setVisible 1

/gate/world/daughters/name                   PhS_Plane_Two
/gate/world/daughters/insert                 box
/gate/PhS_Plane_Two/setMaterial              Vacuum
/gate/PhS_Plane_Two/geometry/setXLength      22 cm
/gate/PhS_Plane_Two/geometry/setYLength      22 cm
/gate/PhS_Plane_Two/geometry/setZLength      1 nm
/gate/PhS_Plane_Two/placement/setTranslation 0.0 0.0 471 mm #(-529)
/gate/PhS_Plane_Two/vis/setColor             cyan
/gate/PhS_Plane_Two/vis/setVisible           1

/gate/world/daughters/name                   Kill_BackPlane
/gate/world/daughters/insert                 box
/gate/Kill_BackPlane/setMaterial                   Air	
/gate/Kill_BackPlane/geometry/setXLength           30 cm
/gate/Kill_BackPlane/geometry/setYLength           30 cm
/gate/Kill_BackPlane/geometry/setZLength           1 nm
/gate/Kill_BackPlane/placement/setTranslation      0.0 0.0 480 mm
/gate/Kill_BackPlane/vis/setColor                  red
/gate/Kill_BackPlane/vis/setVisible                1

/gate/world/daughters/name                   Kill_FrontPlane
/gate/world/daughters/insert                 box
/gate/Kill_FrontPlane/setMaterial                   Air	
/gate/Kill_FrontPlane/geometry/setXLength           30 cm
/gate/Kill_FrontPlane/geometry/setYLength           30 cm
/gate/Kill_FrontPlane/geometry/setZLength           1 nm
/gate/Kill_FrontPlane/placement/setTranslation      0.0 0.0 445 mm
/gate/Kill_FrontPlane/vis/setColor                  red
/gate/Kill_FrontPlane/vis/setVisible                1

/gate/world/daughters/name         epi
/gate/world/daughters/insert       box
/gate/epi/setMaterial                  Silicon
/gate/epi/geometry/setXLength          180.0 mm
/gate/epi/geometry/setYLength          180.0 mm
/gate/epi/geometry/setZLength          0.01 mm
/gate/epi/placement/setTranslation     0 0 449.995 mm
/gate/epi/vis/setVisible               1
/gate/epi/vis/setColor                 yellow
/gate/epi/vis/forceSolid

/gate/world/daughters/name         bulk
/gate/world/daughters/insert       box
/gate/bulk/setMaterial                  Silicon
/gate/bulk/geometry/setXLength          180.0 mm
/gate/bulk/geometry/setYLength          180.0 mm
/gate/bulk/geometry/setZLength          0.6 mm
/gate/bulk/placement/setTranslation     0 0 449.69 mm
/gate/bulk/vis/setVisible               1
/gate/bulk/vis/setColor                 red

/gate/world/daughters/name         peak_air_box 
/gate/world/daughters/insert       box 
/gate/peak_air_box/setMaterial                  Air 
/gate/peak_air_box/geometry/setXLength          200.0 mm 
/gate/peak_air_box/geometry/setYLength          200.0 mm 
/gate/peak_air_box/geometry/setZLength          11 mm 
/gate/peak_air_box/placement/setTranslation     0 0 455.5 mm
/gate/peak_air_box/vis/setVisible               1 
/gate/peak_air_box/vis/setColor                 green
/gate/peak_air_box/vis/forceWireframe

/gate/peak_air_box/daughters/name         peakLayer1 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer1/setMaterial                  {peak_material} 
/gate/peakLayer1/geometry/setXLength          10.0 mm 
/gate/peakLayer1/geometry/setYLength          10.0 mm 
/gate/peakLayer1/geometry/setZLength          {peakzlength_um} um 
/gate/peakLayer1/placement/setTranslation     -5 5 {peakztrans_mm} mm
/gate/peakLayer1/vis/setVisible               1 
/gate/peakLayer1/vis/setColor                 grey
/gate/peakLayer1/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer2 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer2/setMaterial                  {peak_material} 
/gate/peakLayer2/geometry/setXLength          10.0 mm 
/gate/peakLayer2/geometry/setYLength          10.0 mm 
/gate/peakLayer2/geometry/setZLength          {peakzlength2_um} um 
/gate/peakLayer2/placement/setTranslation     5 5 {peakztrans2_mm} mm
/gate/peakLayer2/vis/setVisible               1 
/gate/peakLayer2/vis/setColor                 red
/gate/peakLayer2/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer3 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer3/setMaterial                  {peak_material} 
/gate/peakLayer3/geometry/setXLength          10.0 mm 
/gate/peakLayer3/geometry/setYLength          10.0 mm 
/gate/peakLayer3/geometry/setZLength          {peakzlength3_um} um 
/gate/peakLayer3/placement/setTranslation     -5 -5 {peakztrans3_mm} mm
/gate/peakLayer3/vis/setVisible               1 
/gate/peakLayer3/vis/setColor                 red
/gate/peakLayer3/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer4 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer4/setMaterial                  {peak_material} 
/gate/peakLayer4/geometry/setXLength          10.0 mm 
/gate/peakLayer4/geometry/setYLength          10.0 mm 
/gate/peakLayer4/geometry/setZLength          {peakzlength4_um} um 
/gate/peakLayer4/placement/setTranslation     5 -5 {peakztrans4_mm} mm
/gate/peakLayer4/vis/setVisible               1 
/gate/peakLayer4/vis/setColor                 red
/gate/peakLayer4/vis/forceSolid

# =====================================================
# PHYSICS
# =====================================================

/gate/physics/addPhysicsList emstandard_opt4

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      epi 0.0001 mm 
/gate/physics/Electron/SetCutInRegion   epi 0.0001 mm
/gate/physics/Positron/SetCutInRegion   epi 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      bulk 0.0001 mm
/gate/physics/Electron/SetCutInRegion   bulk 0.0001 mm
/gate/physics/Positron/SetCutInRegion   bulk 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer1 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer1 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer1 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer2 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer2 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer2 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer3 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer3 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer3 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer4 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer4 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer4 0.0001 mm

#=====================================================
# DETECTORS
#=====================================================

## 
## Dose output electron
## 
/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  {pathOutputDose}/Epi-{peakzlength_um}-{peakzlength2_um}-{peakzlength3_um}-{peakzlength4_um}_peakum-{peak_material}-0.87xSeaLevel-{id}.root
/gate/actor/doseDistribution/attachTo              epi
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setSize               50 50 0.010 mm
/gate/actor/doseDistribution/setResolution         1000 1000 1	 #for 60 micron pixel x4
/gate/actor/doseDistribution/enableNumberOfHits    true
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep false
/gate/actor/doseDistribution/enableSquaredEdep     true
/gate/actor/doseDistribution/enableDose            false
/gate/actor/doseDistribution/enableUncertaintyDose false


/gate/actor/addActor   KillActor                         Kill_BP 
/gate/actor/Kill_BP/attachTo                             Kill_BackPlane 

/gate/actor/addActor   KillActor                         Kill_FP 
/gate/actor/Kill_FP/attachTo                             Kill_FrontPlane 

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize
# /process/em/setBiasingFactor compt 100 True

# /process/em/setSecBiasing compt peakLayer1 100 1000 MeV
# /particle/process/dump

#=====================================================
# BEAMS
#=====================================================

# Read from Phase Space files. Here we indicate the type of particle
# (gamma) because this information is not stored in the PhS to gain
# space. Moreover, we set 'useRandomSymmetry' to generate more
# particle than the number of particle in the PhS, using a Z axis
# symmetry.

#/gate/source/addSource                         beam_g phaseSpace
#/gate/source/beam_g/addPhaseSpaceFile          {inputPhaseSpaceFile}
#{inputParticleType}
#/gate/source/beam_g/attachTo                   PhS_Plane_Two
#/gate/source/beam_g/useRandomSymmetry          true

/gate/source/addSource mybeam gps 
/gate/source/mybeam/gps/particle e- 
/gate/source/mybeam/gps/pos/centre 0 0 471 mm 
/gate/source/mybeam/gps/direction 0 0 -1 
/gate/source/mybeam/gps/type Plane 
/gate/source/mybeam/gps/shape Square 
/gate/source/mybeam/gps/halfx 2 cm 
/gate/source/mybeam/gps/halfy 2 cm 
/gate/source/mybeam/gps/ene/type Arb 
/gate/source/mybeam/gps/hist/type arb 
/gate/source/mybeam/gps/hist/point 0.02206812361286817 16049.0
/gate/source/mybeam/gps/hist/point 0.06600283020328788 21500.0
/gate/source/mybeam/gps/hist/point 0.1099375367937076 26030.0
/gate/source/mybeam/gps/hist/point 0.1538722433841273 27821.0
/gate/source/mybeam/gps/hist/point 0.197806949974547 27901.0
/gate/source/mybeam/gps/hist/point 0.2417416565649667 27968.0
/gate/source/mybeam/gps/hist/point 0.28567636315538647 26875.0
/gate/source/mybeam/gps/hist/point 0.3296110697458061 25554.0
/gate/source/mybeam/gps/hist/point 0.3735457763362259 24555.0
/gate/source/mybeam/gps/hist/point 0.4174804829266455 23650.0
/gate/source/mybeam/gps/hist/point 0.4614151895170653 22254.0
/gate/source/mybeam/gps/hist/point 0.5053498961074849 21528.0
/gate/source/mybeam/gps/hist/point 0.5492846026979047 20023.0
/gate/source/mybeam/gps/hist/point 0.5932193092883244 19269.0
/gate/source/mybeam/gps/hist/point 0.6371540158787441 18599.0
/gate/source/mybeam/gps/hist/point 0.6810887224691637 17959.0
/gate/source/mybeam/gps/hist/point 0.7250234290595836 17204.0
/gate/source/mybeam/gps/hist/point 0.7689581356500033 16628.0
/gate/source/mybeam/gps/hist/point 0.8128928422404229 15637.0
/gate/source/mybeam/gps/hist/point 0.8568275488308427 15377.0
/gate/source/mybeam/gps/hist/point 0.9007622554212624 14844.0
/gate/source/mybeam/gps/hist/point 0.9446969620116821 14390.0
/gate/source/mybeam/gps/hist/point 0.9886316686021017 13809.0
/gate/source/mybeam/gps/hist/point 1.0325663751925216 13046.0
/gate/source/mybeam/gps/hist/point 1.0765010817829412 12718.0
/gate/source/mybeam/gps/hist/point 1.1204357883733609 12350.0
/gate/source/mybeam/gps/hist/point 1.1643704949637805 11881.0
/gate/source/mybeam/gps/hist/point 1.2083052015542004 11553.0
/gate/source/mybeam/gps/hist/point 1.25223990814462 11308.0
/gate/source/mybeam/gps/hist/point 1.2961746147350397 10877.0
/gate/source/mybeam/gps/hist/point 1.3401093213254596 10320.0
/gate/source/mybeam/gps/hist/point 1.3840440279158792 10108.0
/gate/source/mybeam/gps/hist/point 1.4279787345062989 9676.0
/gate/source/mybeam/gps/hist/point 1.4719134410967185 9488.0
/gate/source/mybeam/gps/hist/point 1.5158481476871384 9138.0
/gate/source/mybeam/gps/hist/point 1.559782854277558 8773.0
/gate/source/mybeam/gps/hist/point 1.6037175608679777 8465.0
/gate/source/mybeam/gps/hist/point 1.6476522674583975 8309.0
/gate/source/mybeam/gps/hist/point 1.6915869740488172 7914.0
/gate/source/mybeam/gps/hist/point 1.7355216806392368 7790.0
/gate/source/mybeam/gps/hist/point 1.7794563872296565 7505.0
/gate/source/mybeam/gps/hist/point 1.8233910938200764 7146.0
/gate/source/mybeam/gps/hist/point 1.867325800410496 6883.0
/gate/source/mybeam/gps/hist/point 1.9112605070009157 6826.0
/gate/source/mybeam/gps/hist/point 1.9551952135913355 6583.0
/gate/source/mybeam/gps/hist/point 1.9991299201817552 6442.0
/gate/source/mybeam/gps/hist/point 2.043064626772175 6180.0
/gate/source/mybeam/gps/hist/point 2.086999333362595 5994.0
/gate/source/mybeam/gps/hist/point 2.130934039953014 5892.0
/gate/source/mybeam/gps/hist/point 2.174868746543434 5555.0
/gate/source/mybeam/gps/hist/point 2.2188034531338534 5484.0
/gate/source/mybeam/gps/hist/point 2.2627381597242735 5318.0
/gate/source/mybeam/gps/hist/point 2.3066728663146927 5037.0
/gate/source/mybeam/gps/hist/point 2.350607572905113 4798.0
/gate/source/mybeam/gps/hist/point 2.394542279495533 4740.0
/gate/source/mybeam/gps/hist/point 2.438476986085952 4597.0
/gate/source/mybeam/gps/hist/point 2.482411692676372 4471.0
/gate/source/mybeam/gps/hist/point 2.5263463992667914 4308.0
/gate/source/mybeam/gps/hist/point 2.5702811058572115 4137.0
/gate/source/mybeam/gps/hist/point 2.6142158124476307 4042.0
/gate/source/mybeam/gps/hist/point 2.6581505190380508 3934.0
/gate/source/mybeam/gps/hist/point 2.702085225628471 3703.0
/gate/source/mybeam/gps/hist/point 2.74601993221889 3493.0
/gate/source/mybeam/gps/hist/point 2.78995463880931 3553.0
/gate/source/mybeam/gps/hist/point 2.8338893453997294 3312.0
/gate/source/mybeam/gps/hist/point 2.8778240519901495 3312.0
/gate/source/mybeam/gps/hist/point 2.9217587585805687 3286.0
/gate/source/mybeam/gps/hist/point 2.9656934651709888 3079.0
/gate/source/mybeam/gps/hist/point 3.009628171761409 2970.0
/gate/source/mybeam/gps/hist/point 3.053562878351828 2859.0
/gate/source/mybeam/gps/hist/point 3.097497584942248 2698.0
/gate/source/mybeam/gps/hist/point 3.1414322915326673 2654.0
/gate/source/mybeam/gps/hist/point 3.1853669981230874 2545.0
/gate/source/mybeam/gps/hist/point 3.2293017047135066 2496.0
/gate/source/mybeam/gps/hist/point 3.2732364113039267 2407.0
/gate/source/mybeam/gps/hist/point 3.317171117894347 2355.0
/gate/source/mybeam/gps/hist/point 3.361105824484766 2245.0
/gate/source/mybeam/gps/hist/point 3.405040531075186 2208.0
/gate/source/mybeam/gps/hist/point 3.4489752376656053 2016.0
/gate/source/mybeam/gps/hist/point 3.4929099442560254 1918.0
/gate/source/mybeam/gps/hist/point 3.5368446508464446 1891.0
/gate/source/mybeam/gps/hist/point 3.5807793574368647 1807.0
/gate/source/mybeam/gps/hist/point 3.624714064027285 1783.0
/gate/source/mybeam/gps/hist/point 3.668648770617704 1686.0
/gate/source/mybeam/gps/hist/point 3.712583477208124 1602.0
/gate/source/mybeam/gps/hist/point 3.7565181837985433 1542.0
/gate/source/mybeam/gps/hist/point 3.8004528903889634 1532.0
/gate/source/mybeam/gps/hist/point 3.8443875969793826 1389.0
/gate/source/mybeam/gps/hist/point 3.8883223035698027 1296.0
/gate/source/mybeam/gps/hist/point 3.9322570101602228 1343.0
/gate/source/mybeam/gps/hist/point 3.976191716750642 1197.0
/gate/source/mybeam/gps/hist/point 4.020126423341061 1187.0
/gate/source/mybeam/gps/hist/point 4.064061129931481 1126.0
/gate/source/mybeam/gps/hist/point 4.107995836521901 1072.0
/gate/source/mybeam/gps/hist/point 4.1519305431123215 1091.0
/gate/source/mybeam/gps/hist/point 4.195865249702741 935.0
/gate/source/mybeam/gps/hist/point 4.23979995629316 951.0
/gate/source/mybeam/gps/hist/point 4.28373466288358 901.0
/gate/source/mybeam/gps/hist/point 4.327669369474 803.0
/gate/source/mybeam/gps/hist/point 4.371604076064419 799.0
/gate/source/mybeam/gps/hist/point 4.415538782654839 841.0
/gate/source/mybeam/gps/hist/point 4.4594734892452585 714.0
/gate/source/mybeam/gps/hist/point 4.503408195835679 734.0
/gate/source/mybeam/gps/hist/point 4.547342902426099 675.0
/gate/source/mybeam/gps/hist/point 4.591277609016518 640.0
/gate/source/mybeam/gps/hist/point 4.635212315606937 577.0
/gate/source/mybeam/gps/hist/point 4.679147022197357 547.0
/gate/source/mybeam/gps/hist/point 4.723081728787777 514.0
/gate/source/mybeam/gps/hist/point 4.767016435378197 523.0
/gate/source/mybeam/gps/hist/point 4.810951141968617 457.0
/gate/source/mybeam/gps/hist/point 4.854885848559036 414.0
/gate/source/mybeam/gps/hist/point 4.898820555149456 436.0
/gate/source/mybeam/gps/hist/point 4.942755261739876 406.0
/gate/source/mybeam/gps/hist/point 4.986689968330295 397.0
/gate/source/mybeam/gps/hist/point 5.030624674920715 341.0
/gate/source/mybeam/gps/hist/point 5.0745593815111345 320.0
/gate/source/mybeam/gps/hist/point 5.118494088101555 294.0
/gate/source/mybeam/gps/hist/point 5.162428794691975 315.0
/gate/source/mybeam/gps/hist/point 5.206363501282394 262.0
/gate/source/mybeam/gps/hist/point 5.250298207872813 262.0
/gate/source/mybeam/gps/hist/point 5.294232914463233 212.0
/gate/source/mybeam/gps/hist/point 5.338167621053653 213.0
/gate/source/mybeam/gps/hist/point 5.382102327644073 183.0
/gate/source/mybeam/gps/hist/point 5.426037034234493 197.0
/gate/source/mybeam/gps/hist/point 5.469971740824912 184.0
/gate/source/mybeam/gps/hist/point 5.513906447415332 156.0
/gate/source/mybeam/gps/hist/point 5.557841154005752 129.0
/gate/source/mybeam/gps/hist/point 5.601775860596171 121.0
/gate/source/mybeam/gps/hist/point 5.645710567186591 118.0
/gate/source/mybeam/gps/hist/point 5.6896452737770105 97.0
/gate/source/mybeam/gps/hist/point 5.7335799803674306 89.0
/gate/source/mybeam/gps/hist/point 5.777514686957851 107.0
/gate/source/mybeam/gps/hist/point 5.82144939354827 76.0
/gate/source/mybeam/gps/hist/point 5.865384100138689 66.0
/gate/source/mybeam/gps/hist/point 5.909318806729109 71.0
/gate/source/mybeam/gps/hist/point 5.953253513319529 51.0
/gate/source/mybeam/gps/hist/point 5.997188219909949 56.0
/gate/source/mybeam/gps/hist/point 6.0411229265003685 39.0
/gate/source/mybeam/gps/hist/point 6.085057633090788 28.0
/gate/source/mybeam/gps/hist/point 6.128992339681208 27.0
/gate/source/mybeam/gps/hist/point 6.172927046271628 23.0
/gate/source/mybeam/gps/hist/point 6.216861752862047 12.0
/gate/source/mybeam/gps/hist/point 6.260796459452467 9.0
/gate/source/mybeam/gps/hist/point 6.304731166042886 5.0
/gate/source/mybeam/gps/hist/point 6.3486658726333065 8.0
/gate/source/mybeam/gps/hist/point 6.392600579223727 7.0
/gate/source/mybeam/gps/hist/point 6.436535285814146 1.0
/gate/source/mybeam/gps/hist/point 6.480469992404565 1.0
/gate/source/mybeam/gps/hist/point 6.524404698994985 2.0
/gate/source/mybeam/gps/hist/point 6.568339405585405 1.0
/gate/source/mybeam/gps/hist/inter Log

#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed {seed}
#1234567890
/gate/application/noGlobalOutput

#/tracking/verbose 2

/gate/application/setTotalNumberOfPrimaries {primaries}
#1000
/gate/application/start
