
# INPUTS
# pathOutputDose
# id
# seed 
# primaries
# peakzlength_um
# peakztrans_mm
# peakzlength2_um
# peakztrans2_mm
# peakzlength3_um
# peakztrans3_mm
# peakzlength4_um
# peakztrans4_mm
# peak_material
# density

# Gate /home/as17540/linac/mac/Main_PhS2_Elec_Sensor.mac -a '[id,$jobid] [density,Everest] [peakzlength_um,10] [peakztrans_mm,-5.495] [peakzlength2_um,30] [peakztrans2_mm,-5.485] [peakzlength3_um,50] [peakztrans3_mm,-5.475] [peakzlength4_um,70] [peakztrans4_mm,-5.465] [peak_material,Copper] [seed,1234567] [primaries,1000000] [pathOutputDose,/work/as17540/PhaseSpaces/PhS3_Sensor_10x10_Elec/]'

#=====================================================
# VISUALISATION
#=====================================================

#/control/execute mac/visu.mac

# =====================================================
# GEOMETRY
# =====================================================

/gate/geometry/setMaterialDatabase /home/as17540/linac/data/GateMaterials_Everest.db

# WORLD
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    0.3 m
/gate/world/geometry/setYLength    0.3 m
/gate/world/geometry/setZLength    1 m
/gate/world/vis/setVisible 1

/gate/world/daughters/name                   PhS_Plane_Two
/gate/world/daughters/insert                 box
/gate/PhS_Plane_Two/setMaterial              Vacuum
/gate/PhS_Plane_Two/geometry/setXLength      22 cm
/gate/PhS_Plane_Two/geometry/setYLength      22 cm
/gate/PhS_Plane_Two/geometry/setZLength      1 nm
/gate/PhS_Plane_Two/placement/setTranslation 0.0 0.0 471 mm #(-529)
/gate/PhS_Plane_Two/vis/setColor             cyan
/gate/PhS_Plane_Two/vis/setVisible           1

/gate/world/daughters/name                   Kill_BackPlane
/gate/world/daughters/insert                 box
/gate/Kill_BackPlane/setMaterial                   Air	
/gate/Kill_BackPlane/geometry/setXLength           30 cm
/gate/Kill_BackPlane/geometry/setYLength           30 cm
/gate/Kill_BackPlane/geometry/setZLength           1 nm
/gate/Kill_BackPlane/placement/setTranslation      0.0 0.0 480 mm
/gate/Kill_BackPlane/vis/setColor                  red
/gate/Kill_BackPlane/vis/setVisible                1

/gate/world/daughters/name                   Kill_FrontPlane
/gate/world/daughters/insert                 box
/gate/Kill_FrontPlane/setMaterial                   Air	
/gate/Kill_FrontPlane/geometry/setXLength           30 cm
/gate/Kill_FrontPlane/geometry/setYLength           30 cm
/gate/Kill_FrontPlane/geometry/setZLength           1 nm
/gate/Kill_FrontPlane/placement/setTranslation      0.0 0.0 445 mm
/gate/Kill_FrontPlane/vis/setColor                  red
/gate/Kill_FrontPlane/vis/setVisible                1

/gate/world/daughters/name         epi
/gate/world/daughters/insert       box
/gate/epi/setMaterial                  Silicon
/gate/epi/geometry/setXLength          180.0 mm
/gate/epi/geometry/setYLength          180.0 mm
/gate/epi/geometry/setZLength          0.01 mm
/gate/epi/placement/setTranslation     0 0 449.995 mm
/gate/epi/vis/setVisible               1
/gate/epi/vis/setColor                 yellow
/gate/epi/vis/forceSolid

/gate/world/daughters/name         bulk
/gate/world/daughters/insert       box
/gate/bulk/setMaterial                  Silicon
/gate/bulk/geometry/setXLength          180.0 mm
/gate/bulk/geometry/setYLength          180.0 mm
/gate/bulk/geometry/setZLength          0.6 mm
/gate/bulk/placement/setTranslation     0 0 449.69 mm
/gate/bulk/vis/setVisible               1
/gate/bulk/vis/setColor                 red

/gate/world/daughters/name         peak_air_box 
/gate/world/daughters/insert       box 
/gate/peak_air_box/setMaterial                  Air 
/gate/peak_air_box/geometry/setXLength          200.0 mm 
/gate/peak_air_box/geometry/setYLength          200.0 mm 
/gate/peak_air_box/geometry/setZLength          11 mm 
/gate/peak_air_box/placement/setTranslation     0 0 455.5 mm
/gate/peak_air_box/vis/setVisible               1 
/gate/peak_air_box/vis/setColor                 green
/gate/peak_air_box/vis/forceWireframe

/gate/peak_air_box/daughters/name         peakLayer1 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer1/setMaterial                  {peak_material} 
/gate/peakLayer1/geometry/setXLength          10.0 mm 
/gate/peakLayer1/geometry/setYLength          10.0 mm 
/gate/peakLayer1/geometry/setZLength          {peakzlength_um} um 
/gate/peakLayer1/placement/setTranslation     -5 5 {peakztrans_mm} mm
/gate/peakLayer1/vis/setVisible               1 
/gate/peakLayer1/vis/setColor                 grey
/gate/peakLayer1/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer2 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer2/setMaterial                  {peak_material} 
/gate/peakLayer2/geometry/setXLength          10.0 mm 
/gate/peakLayer2/geometry/setYLength          10.0 mm 
/gate/peakLayer2/geometry/setZLength          {peakzlength2_um} um 
/gate/peakLayer2/placement/setTranslation     5 5 {peakztrans2_mm} mm
/gate/peakLayer2/vis/setVisible               1 
/gate/peakLayer2/vis/setColor                 red
/gate/peakLayer2/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer3 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer3/setMaterial                  {peak_material} 
/gate/peakLayer3/geometry/setXLength          10.0 mm 
/gate/peakLayer3/geometry/setYLength          10.0 mm 
/gate/peakLayer3/geometry/setZLength          {peakzlength3_um} um 
/gate/peakLayer3/placement/setTranslation     -5 -5 {peakztrans3_mm} mm
/gate/peakLayer3/vis/setVisible               1 
/gate/peakLayer3/vis/setColor                 red
/gate/peakLayer3/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer4 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer4/setMaterial                  {peak_material} 
/gate/peakLayer4/geometry/setXLength          10.0 mm 
/gate/peakLayer4/geometry/setYLength          10.0 mm 
/gate/peakLayer4/geometry/setZLength          {peakzlength4_um} um 
/gate/peakLayer4/placement/setTranslation     5 -5 {peakztrans4_mm} mm
/gate/peakLayer4/vis/setVisible               1 
/gate/peakLayer4/vis/setColor                 red
/gate/peakLayer4/vis/forceSolid

# =====================================================
# PHYSICS
# =====================================================

/gate/physics/addPhysicsList emstandard_opt4

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      epi 0.0001 mm 
/gate/physics/Electron/SetCutInRegion   epi 0.0001 mm
/gate/physics/Positron/SetCutInRegion   epi 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      bulk 0.0001 mm
/gate/physics/Electron/SetCutInRegion   bulk 0.0001 mm
/gate/physics/Positron/SetCutInRegion   bulk 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer1 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer1 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer1 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer2 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer2 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer2 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer3 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer3 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer3 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer4 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer4 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer4 0.0001 mm

#=====================================================
# DETECTORS
#=====================================================

## 
## Dose output electron
## 
/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  {pathOutputDose}/Epi-{peakzlength_um}-{peakzlength2_um}-{peakzlength3_um}-{peakzlength4_um}_peakum-{peak_material}-{density}.root
/gate/actor/doseDistribution/attachTo              epi
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setSize               50 50 0.010 mm
/gate/actor/doseDistribution/setResolution         1000 1000 1	 #for 60 micron pixel x4
/gate/actor/doseDistribution/enableNumberOfHits    true
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep false
/gate/actor/doseDistribution/enableSquaredEdep     true
/gate/actor/doseDistribution/enableDose            false
/gate/actor/doseDistribution/enableUncertaintyDose false


/gate/actor/addActor   KillActor                         Kill_BP 
/gate/actor/Kill_BP/attachTo                             Kill_BackPlane 

/gate/actor/addActor   KillActor                         Kill_FP 
/gate/actor/Kill_FP/attachTo                             Kill_FrontPlane 

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize
# /process/em/setBiasingFactor compt 100 True

# /process/em/setSecBiasing compt peakLayer1 100 1000 MeV
# /particle/process/dump

#=====================================================
# BEAMS
#=====================================================

# Read from Phase Space files. Here we indicate the type of particle
# (gamma) because this information is not stored in the PhS to gain
# space. Moreover, we set 'useRandomSymmetry' to generate more
# particle than the number of particle in the PhS, using a Z axis
# symmetry.

#/gate/source/addSource                         beam_g phaseSpace
#/gate/source/beam_g/addPhaseSpaceFile          {inputPhaseSpaceFile}
#{inputParticleType}
#/gate/source/beam_g/attachTo                   PhS_Plane_Two
#/gate/source/beam_g/useRandomSymmetry          true

/gate/source/addSource mybeam gps 
/gate/source/mybeam/gps/particle e- 
/gate/source/mybeam/gps/pos/centre 0 0 471 mm 
/gate/source/mybeam/gps/direction 0 0 -1 
/gate/source/mybeam/gps/type Plane 
/gate/source/mybeam/gps/shape Square 
/gate/source/mybeam/gps/halfx 2 cm 
/gate/source/mybeam/gps/halfy 2 cm 
/gate/source/mybeam/gps/ene/type Arb 
/gate/source/mybeam/gps/hist/type arb 
/gate/source/mybeam/gps/hist/point 0.02179617825335299 14931.0
/gate/source/mybeam/gps/hist/point 0.06518525016501371 19657.0
/gate/source/mybeam/gps/hist/point 0.10857432207667443 23525.0
/gate/source/mybeam/gps/hist/point 0.15196339398833514 24856.0
/gate/source/mybeam/gps/hist/point 0.1953524658999959 25044.0
/gate/source/mybeam/gps/hist/point 0.23874153781165658 24329.0
/gate/source/mybeam/gps/hist/point 0.28213060972331727 23309.0
/gate/source/mybeam/gps/hist/point 0.325519681634978 22589.0
/gate/source/mybeam/gps/hist/point 0.36890875354663877 21406.0
/gate/source/mybeam/gps/hist/point 0.4122978254582995 20431.0
/gate/source/mybeam/gps/hist/point 0.45568689736996015 19387.0
/gate/source/mybeam/gps/hist/point 0.4990759692816209 18645.0
/gate/source/mybeam/gps/hist/point 0.5424650411932816 17558.0
/gate/source/mybeam/gps/hist/point 0.5858541131049424 16964.0
/gate/source/mybeam/gps/hist/point 0.629243185016603 16330.0
/gate/source/mybeam/gps/hist/point 0.6726322569282638 15786.0
/gate/source/mybeam/gps/hist/point 0.7160213288399245 15006.0
/gate/source/mybeam/gps/hist/point 0.7594104007515853 14583.0
/gate/source/mybeam/gps/hist/point 0.8027994726632459 13822.0
/gate/source/mybeam/gps/hist/point 0.8461885445749067 13455.0
/gate/source/mybeam/gps/hist/point 0.8895776164865674 13170.0
/gate/source/mybeam/gps/hist/point 0.9329666883982282 12387.0
/gate/source/mybeam/gps/hist/point 0.9763557603098888 11932.0
/gate/source/mybeam/gps/hist/point 1.0197448322215497 11709.0
/gate/source/mybeam/gps/hist/point 1.0631339041332102 11294.0
/gate/source/mybeam/gps/hist/point 1.1065229760448712 10982.0
/gate/source/mybeam/gps/hist/point 1.1499120479565317 10532.0
/gate/source/mybeam/gps/hist/point 1.1933011198681924 10281.0
/gate/source/mybeam/gps/hist/point 1.2366901917798532 10112.0
/gate/source/mybeam/gps/hist/point 1.2800792636915137 9656.0
/gate/source/mybeam/gps/hist/point 1.3234683356031747 9367.0
/gate/source/mybeam/gps/hist/point 1.3668574075148352 8967.0
/gate/source/mybeam/gps/hist/point 1.4102464794264962 8653.0
/gate/source/mybeam/gps/hist/point 1.4536355513381567 8505.0
/gate/source/mybeam/gps/hist/point 1.4970246232498177 8197.0
/gate/source/mybeam/gps/hist/point 1.5404136951614782 7951.0
/gate/source/mybeam/gps/hist/point 1.583802767073139 7629.0
/gate/source/mybeam/gps/hist/point 1.6271918389847997 7386.0
/gate/source/mybeam/gps/hist/point 1.6705809108964602 7036.0
/gate/source/mybeam/gps/hist/point 1.7139699828081212 7053.0
/gate/source/mybeam/gps/hist/point 1.7573590547197817 6773.0
/gate/source/mybeam/gps/hist/point 1.8007481266314427 6643.0
/gate/source/mybeam/gps/hist/point 1.8441371985431032 6388.0
/gate/source/mybeam/gps/hist/point 1.887526270454764 6195.0
/gate/source/mybeam/gps/hist/point 1.9309153423664247 5998.0
/gate/source/mybeam/gps/hist/point 1.9743044142780852 5701.0
/gate/source/mybeam/gps/hist/point 2.017693486189746 5580.0
/gate/source/mybeam/gps/hist/point 2.0610825581014067 5531.0
/gate/source/mybeam/gps/hist/point 2.1044716300130677 5368.0
/gate/source/mybeam/gps/hist/point 2.147860701924728 4966.0
/gate/source/mybeam/gps/hist/point 2.1912497738363887 4894.0
/gate/source/mybeam/gps/hist/point 2.2346388457480497 4673.0
/gate/source/mybeam/gps/hist/point 2.2780279176597107 4614.0
/gate/source/mybeam/gps/hist/point 2.321416989571371 4466.0
/gate/source/mybeam/gps/hist/point 2.3648060614830317 4426.0
/gate/source/mybeam/gps/hist/point 2.4081951333946927 4202.0
/gate/source/mybeam/gps/hist/point 2.4515842053063532 4157.0
/gate/source/mybeam/gps/hist/point 2.4949732772180138 3913.0
/gate/source/mybeam/gps/hist/point 2.5383623491296747 3840.0
/gate/source/mybeam/gps/hist/point 2.5817514210413357 3722.0
/gate/source/mybeam/gps/hist/point 2.6251404929529962 3605.0
/gate/source/mybeam/gps/hist/point 2.6685295648646568 3461.0
/gate/source/mybeam/gps/hist/point 2.7119186367763177 3324.0
/gate/source/mybeam/gps/hist/point 2.7553077086879787 3361.0
/gate/source/mybeam/gps/hist/point 2.798696780599639 3262.0
/gate/source/mybeam/gps/hist/point 2.8420858525112997 3042.0
/gate/source/mybeam/gps/hist/point 2.8854749244229607 2865.0
/gate/source/mybeam/gps/hist/point 2.9288639963346212 2873.0
/gate/source/mybeam/gps/hist/point 2.9722530682462818 2774.0
/gate/source/mybeam/gps/hist/point 3.0156421401579427 2563.0
/gate/source/mybeam/gps/hist/point 3.0590312120696037 2513.0
/gate/source/mybeam/gps/hist/point 3.1024202839812642 2440.0
/gate/source/mybeam/gps/hist/point 3.1458093558929248 2492.0
/gate/source/mybeam/gps/hist/point 3.1891984278045857 2279.0
/gate/source/mybeam/gps/hist/point 3.2325874997162463 2148.0
/gate/source/mybeam/gps/hist/point 3.275976571627907 2169.0
/gate/source/mybeam/gps/hist/point 3.3193656435395678 2062.0
/gate/source/mybeam/gps/hist/point 3.3627547154512287 2031.0
/gate/source/mybeam/gps/hist/point 3.4061437873628893 1919.0
/gate/source/mybeam/gps/hist/point 3.44953285927455 1866.0
/gate/source/mybeam/gps/hist/point 3.4929219311862107 1735.0
/gate/source/mybeam/gps/hist/point 3.5363110030978713 1713.0
/gate/source/mybeam/gps/hist/point 3.579700075009532 1578.0
/gate/source/mybeam/gps/hist/point 3.6230891469211928 1559.0
/gate/source/mybeam/gps/hist/point 3.6664782188328537 1580.0
/gate/source/mybeam/gps/hist/point 3.7098672907445143 1417.0
/gate/source/mybeam/gps/hist/point 3.753256362656175 1368.0
/gate/source/mybeam/gps/hist/point 3.7966454345678358 1297.0
/gate/source/mybeam/gps/hist/point 3.8400345064794963 1237.0
/gate/source/mybeam/gps/hist/point 3.883423578391157 1189.0
/gate/source/mybeam/gps/hist/point 3.926812650302818 1147.0
/gate/source/mybeam/gps/hist/point 3.9702017222144788 1080.0
/gate/source/mybeam/gps/hist/point 4.01359079412614 1082.0
/gate/source/mybeam/gps/hist/point 4.0569798660378 1038.0
/gate/source/mybeam/gps/hist/point 4.100368937949461 964.0
/gate/source/mybeam/gps/hist/point 4.143758009861122 918.0
/gate/source/mybeam/gps/hist/point 4.187147081772782 889.0
/gate/source/mybeam/gps/hist/point 4.230536153684443 828.0
/gate/source/mybeam/gps/hist/point 4.273925225596104 805.0
/gate/source/mybeam/gps/hist/point 4.317314297507764 773.0
/gate/source/mybeam/gps/hist/point 4.360703369419426 716.0
/gate/source/mybeam/gps/hist/point 4.404092441331086 726.0
/gate/source/mybeam/gps/hist/point 4.447481513242746 683.0
/gate/source/mybeam/gps/hist/point 4.490870585154408 623.0
/gate/source/mybeam/gps/hist/point 4.534259657066068 549.0
/gate/source/mybeam/gps/hist/point 4.577648728977728 543.0
/gate/source/mybeam/gps/hist/point 4.62103780088939 521.0
/gate/source/mybeam/gps/hist/point 4.66442687280105 467.0
/gate/source/mybeam/gps/hist/point 4.707815944712711 460.0
/gate/source/mybeam/gps/hist/point 4.751205016624372 435.0
/gate/source/mybeam/gps/hist/point 4.794594088536032 429.0
/gate/source/mybeam/gps/hist/point 4.837983160447693 374.0
/gate/source/mybeam/gps/hist/point 4.881372232359354 366.0
/gate/source/mybeam/gps/hist/point 4.924761304271014 361.0
/gate/source/mybeam/gps/hist/point 4.968150376182676 301.0
/gate/source/mybeam/gps/hist/point 5.011539448094336 308.0
/gate/source/mybeam/gps/hist/point 5.054928520005996 275.0
/gate/source/mybeam/gps/hist/point 5.098317591917658 264.0
/gate/source/mybeam/gps/hist/point 5.141706663829318 266.0
/gate/source/mybeam/gps/hist/point 5.185095735740979 235.0
/gate/source/mybeam/gps/hist/point 5.22848480765264 192.0
/gate/source/mybeam/gps/hist/point 5.2718738795643 183.0
/gate/source/mybeam/gps/hist/point 5.315262951475961 196.0
/gate/source/mybeam/gps/hist/point 5.358652023387622 157.0
/gate/source/mybeam/gps/hist/point 5.402041095299282 157.0
/gate/source/mybeam/gps/hist/point 5.445430167210944 158.0
/gate/source/mybeam/gps/hist/point 5.488819239122604 127.0
/gate/source/mybeam/gps/hist/point 5.532208311034264 131.0
/gate/source/mybeam/gps/hist/point 5.575597382945926 108.0
/gate/source/mybeam/gps/hist/point 5.618986454857586 118.0
/gate/source/mybeam/gps/hist/point 5.662375526769246 81.0
/gate/source/mybeam/gps/hist/point 5.705764598680908 88.0
/gate/source/mybeam/gps/hist/point 5.749153670592568 69.0
/gate/source/mybeam/gps/hist/point 5.792542742504229 67.0
/gate/source/mybeam/gps/hist/point 5.83593181441589 48.0
/gate/source/mybeam/gps/hist/point 5.87932088632755 41.0
/gate/source/mybeam/gps/hist/point 5.922709958239211 36.0
/gate/source/mybeam/gps/hist/point 5.966099030150872 34.0
/gate/source/mybeam/gps/hist/point 6.009488102062532 28.0
/gate/source/mybeam/gps/hist/point 6.052877173974194 27.0
/gate/source/mybeam/gps/hist/point 6.096266245885854 27.0
/gate/source/mybeam/gps/hist/point 6.139655317797514 15.0
/gate/source/mybeam/gps/hist/point 6.183044389709176 12.0
/gate/source/mybeam/gps/hist/point 6.226433461620836 11.0
/gate/source/mybeam/gps/hist/point 6.269822533532497 7.0
/gate/source/mybeam/gps/hist/point 6.313211605444158 4.0
/gate/source/mybeam/gps/hist/point 6.356600677355818 1.0
/gate/source/mybeam/gps/hist/point 6.399989749267479 2.0
/gate/source/mybeam/gps/hist/point 6.44337882117914 2.0
/gate/source/mybeam/gps/hist/point 6.4867678930908 1.0
/gate/source/mybeam/gps/hist/inter Log

#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed {seed}
#1234567890
/gate/application/noGlobalOutput

#/tracking/verbose 2

/gate/application/setTotalNumberOfPrimaries {primaries}
#1000
/gate/application/start
