# INPUTS
# pathOutputDose
# id
# seed 
# primaries
# peakzlength_um
# peakztrans_mm
# peakzlength2_um
# peakztrans2_mm
# peakzlength3_um
# peakztrans3_mm
# peakzlength4_um
# peakztrans4_mm
# peak_material

# Gate /home/as17540/linac/mac/Main_PhS2_Elec_Sensor_1.2xSeaLevel_0.mac -a '[id,$PBS_ARRAY_INDEX] [peakzlength2_um,30] [peakztrans2_mm,-5.485] [peakzlength3_um,50] [peakztrans3_mm,-5.475] [peakzlength4_um,70] [peakztrans4_mm,-5.465] [peak_material,Copper] [seed,$RANDOM$RANDOM$RANDOM] [primaries,12063400] [pathOutputDose,/work/as17540/PhaseSpaces/PhS3_Sensor_10x10_Elec/]'

#=====================================================
# VISUALISATION
#=====================================================

#/control/execute mac/visu.mac

# =====================================================
# GEOMETRY
# =====================================================

/gate/geometry/setMaterialDatabase /home/as17540/linac/data/GateMaterials_1.2xSeaLevel.db

# WORLD
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    0.3 m
/gate/world/geometry/setYLength    0.3 m
/gate/world/geometry/setZLength    1 m
/gate/world/vis/setVisible 1

/gate/world/daughters/name                   PhS_Plane_Two
/gate/world/daughters/insert                 box
/gate/PhS_Plane_Two/setMaterial              Vacuum
/gate/PhS_Plane_Two/geometry/setXLength      22 cm
/gate/PhS_Plane_Two/geometry/setYLength      22 cm
/gate/PhS_Plane_Two/geometry/setZLength      1 nm
/gate/PhS_Plane_Two/placement/setTranslation 0.0 0.0 471 mm #(-529)
/gate/PhS_Plane_Two/vis/setColor             cyan
/gate/PhS_Plane_Two/vis/setVisible           1

/gate/world/daughters/name                   Kill_BackPlane
/gate/world/daughters/insert                 box
/gate/Kill_BackPlane/setMaterial                   Air	
/gate/Kill_BackPlane/geometry/setXLength           30 cm
/gate/Kill_BackPlane/geometry/setYLength           30 cm
/gate/Kill_BackPlane/geometry/setZLength           1 nm
/gate/Kill_BackPlane/placement/setTranslation      0.0 0.0 480 mm
/gate/Kill_BackPlane/vis/setColor                  red
/gate/Kill_BackPlane/vis/setVisible                1

/gate/world/daughters/name                   Kill_FrontPlane
/gate/world/daughters/insert                 box
/gate/Kill_FrontPlane/setMaterial                   Air	
/gate/Kill_FrontPlane/geometry/setXLength           30 cm
/gate/Kill_FrontPlane/geometry/setYLength           30 cm
/gate/Kill_FrontPlane/geometry/setZLength           1 nm
/gate/Kill_FrontPlane/placement/setTranslation      0.0 0.0 445 mm
/gate/Kill_FrontPlane/vis/setColor                  red
/gate/Kill_FrontPlane/vis/setVisible                1

/gate/world/daughters/name         epi
/gate/world/daughters/insert       box
/gate/epi/setMaterial                  Silicon
/gate/epi/geometry/setXLength          180.0 mm
/gate/epi/geometry/setYLength          180.0 mm
/gate/epi/geometry/setZLength          0.01 mm
/gate/epi/placement/setTranslation     0 0 449.995 mm
/gate/epi/vis/setVisible               1
/gate/epi/vis/setColor                 yellow
/gate/epi/vis/forceSolid

/gate/world/daughters/name         bulk
/gate/world/daughters/insert       box
/gate/bulk/setMaterial                  Silicon
/gate/bulk/geometry/setXLength          180.0 mm
/gate/bulk/geometry/setYLength          180.0 mm
/gate/bulk/geometry/setZLength          0.6 mm
/gate/bulk/placement/setTranslation     0 0 449.69 mm
/gate/bulk/vis/setVisible               1
/gate/bulk/vis/setColor                 red

/gate/world/daughters/name         peak_air_box 
/gate/world/daughters/insert       box 
/gate/peak_air_box/setMaterial                  Air 
/gate/peak_air_box/geometry/setXLength          200.0 mm 
/gate/peak_air_box/geometry/setYLength          200.0 mm 
/gate/peak_air_box/geometry/setZLength          11 mm 
/gate/peak_air_box/placement/setTranslation     0 0 455.5 mm
/gate/peak_air_box/vis/setVisible               1 
/gate/peak_air_box/vis/setColor                 green
/gate/peak_air_box/vis/forceWireframe

#/gate/peak_air_box/daughters/name         peakLayer1 
#/gate/peak_air_box/daughters/insert       box 
#/gate/peakLayer1/setMaterial                  {peak_material} 
#/gate/peakLayer1/geometry/setXLength          10.0 mm 
#/gate/peakLayer1/geometry/setYLength          10.0 mm 
#/gate/peakLayer1/geometry/setZLength          {peakzlength_um} um 
#/gate/peakLayer1/placement/setTranslation     -5 5 {peakztrans_mm} mm
#/gate/peakLayer1/vis/setVisible               1 
#/gate/peakLayer1/vis/setColor                 grey
#/gate/peakLayer1/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer2 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer2/setMaterial                  {peak_material} 
/gate/peakLayer2/geometry/setXLength          10.0 mm 
/gate/peakLayer2/geometry/setYLength          10.0 mm 
/gate/peakLayer2/geometry/setZLength          {peakzlength2_um} um 
/gate/peakLayer2/placement/setTranslation     5 5 {peakztrans2_mm} mm
/gate/peakLayer2/vis/setVisible               1 
/gate/peakLayer2/vis/setColor                 red
/gate/peakLayer2/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer3 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer3/setMaterial                  {peak_material} 
/gate/peakLayer3/geometry/setXLength          10.0 mm 
/gate/peakLayer3/geometry/setYLength          10.0 mm 
/gate/peakLayer3/geometry/setZLength          {peakzlength3_um} um 
/gate/peakLayer3/placement/setTranslation     -5 -5 {peakztrans3_mm} mm
/gate/peakLayer3/vis/setVisible               1 
/gate/peakLayer3/vis/setColor                 red
/gate/peakLayer3/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer4 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer4/setMaterial                  {peak_material} 
/gate/peakLayer4/geometry/setXLength          10.0 mm 
/gate/peakLayer4/geometry/setYLength          10.0 mm 
/gate/peakLayer4/geometry/setZLength          {peakzlength4_um} um 
/gate/peakLayer4/placement/setTranslation     5 -5 {peakztrans4_mm} mm
/gate/peakLayer4/vis/setVisible               1 
/gate/peakLayer4/vis/setColor                 red
/gate/peakLayer4/vis/forceSolid

# =====================================================
# PHYSICS
# =====================================================

/gate/physics/addPhysicsList emstandard_opt4

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      epi 0.0001 mm 
/gate/physics/Electron/SetCutInRegion   epi 0.0001 mm
/gate/physics/Positron/SetCutInRegion   epi 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      bulk 0.0001 mm
/gate/physics/Electron/SetCutInRegion   bulk 0.0001 mm
/gate/physics/Positron/SetCutInRegion   bulk 0.0001 mm

#/gate/physics/Gamma/SetCutInRegion      peakLayer1 0.0001 mm #0.0001
#/gate/physics/Electron/SetCutInRegion   peakLayer1 0.0001 mm
#/gate/physics/Positron/SetCutInRegion   peakLayer1 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer2 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer2 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer2 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer3 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer3 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer3 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer4 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer4 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer4 0.0001 mm

#=====================================================
# DETECTORS
#=====================================================

## 
## Dose output electron
## 
/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  {pathOutputDose}/Epi-00-{peakzlength2_um}-{peakzlength3_um}-{peakzlength4_um}_peakum-{peak_material}-1.2xSeaLevel-{id}.root
/gate/actor/doseDistribution/attachTo              epi
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setSize               50 50 0.010 mm
/gate/actor/doseDistribution/setResolution         1000 1000 1	 #for 60 micron pixel x4
/gate/actor/doseDistribution/enableNumberOfHits    true
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep false
/gate/actor/doseDistribution/enableSquaredEdep     true
/gate/actor/doseDistribution/enableDose            false
/gate/actor/doseDistribution/enableUncertaintyDose false


/gate/actor/addActor   KillActor                         Kill_BP 
/gate/actor/Kill_BP/attachTo                             Kill_BackPlane 

/gate/actor/addActor   KillActor                         Kill_FP 
/gate/actor/Kill_FP/attachTo                             Kill_FrontPlane 

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize
# /process/em/setBiasingFactor compt 100 True

# /process/em/setSecBiasing compt peakLayer1 100 1000 MeV
# /particle/process/dump

#=====================================================
# BEAMS
#=====================================================

# Read from Phase Space files. Here we indicate the type of particle
# (gamma) because this information is not stored in the PhS to gain
# space. Moreover, we set 'useRandomSymmetry' to generate more
# particle than the number of particle in the PhS, using a Z axis
# symmetry.

#/gate/source/addSource                         beam_g phaseSpace
#/gate/source/beam_g/addPhaseSpaceFile          {inputPhaseSpaceFile}
#{inputParticleType}
#/gate/source/beam_g/attachTo                   PhS_Plane_Two
#/gate/source/beam_g/useRandomSymmetry          true

/gate/source/addSource mybeam gps 
/gate/source/mybeam/gps/particle e- 
/gate/source/mybeam/gps/pos/centre 0 0 471 mm 
/gate/source/mybeam/gps/direction 0 0 -1 
/gate/source/mybeam/gps/type Plane 
/gate/source/mybeam/gps/shape Square 
/gate/source/mybeam/gps/halfx 2 cm 
/gate/source/mybeam/gps/halfy 2 cm 
/gate/source/mybeam/gps/ene/type Arb 
/gate/source/mybeam/gps/hist/type arb 
/gate/source/mybeam/gps/hist/point 0.021632034494978143 16247.0
/gate/source/mybeam/gps/hist/point 0.0646938278178277 21798.0
/gate/source/mybeam/gps/hist/point 0.10775562114067726 26870.0
/gate/source/mybeam/gps/hist/point 0.1508174144635268 29263.0
/gate/source/mybeam/gps/hist/point 0.19387920778637635 29618.0
/gate/source/mybeam/gps/hist/point 0.23694100110922592 29263.0
/gate/source/mybeam/gps/hist/point 0.2800027944320755 28557.0
/gate/source/mybeam/gps/hist/point 0.323064587754925 27287.0
/gate/source/mybeam/gps/hist/point 0.36612638107777457 26678.0
/gate/source/mybeam/gps/hist/point 0.4091881744006241 25319.0
/gate/source/mybeam/gps/hist/point 0.4522499677234737 23441.0
/gate/source/mybeam/gps/hist/point 0.49531176104632324 22736.0
/gate/source/mybeam/gps/hist/point 0.5383735543691728 21610.0
/gate/source/mybeam/gps/hist/point 0.5814353476920224 20718.0
/gate/source/mybeam/gps/hist/point 0.6244971410148719 20336.0
/gate/source/mybeam/gps/hist/point 0.6675589343377215 19321.0
/gate/source/mybeam/gps/hist/point 0.7106207276605709 18527.0
/gate/source/mybeam/gps/hist/point 0.7536825209834206 17811.0
/gate/source/mybeam/gps/hist/point 0.79674431430627 17516.0
/gate/source/mybeam/gps/hist/point 0.8398061076291197 16565.0
/gate/source/mybeam/gps/hist/point 0.8828679009519692 15702.0
/gate/source/mybeam/gps/hist/point 0.9259296942748187 15043.0
/gate/source/mybeam/gps/hist/point 0.9689914875976684 14617.0
/gate/source/mybeam/gps/hist/point 1.0120532809205178 14242.0
/gate/source/mybeam/gps/hist/point 1.0551150742433675 13907.0
/gate/source/mybeam/gps/hist/point 1.0981768675662171 13451.0
/gate/source/mybeam/gps/hist/point 1.1412386608890666 12892.0
/gate/source/mybeam/gps/hist/point 1.184300454211916 12506.0
/gate/source/mybeam/gps/hist/point 1.2273622475347656 12198.0
/gate/source/mybeam/gps/hist/point 1.2704240408576153 11570.0
/gate/source/mybeam/gps/hist/point 1.3134858341804647 11169.0
/gate/source/mybeam/gps/hist/point 1.3565476275033141 10794.0
/gate/source/mybeam/gps/hist/point 1.399609420826164 10406.0
/gate/source/mybeam/gps/hist/point 1.4426712141490134 10130.0
/gate/source/mybeam/gps/hist/point 1.4857330074718629 9869.0
/gate/source/mybeam/gps/hist/point 1.5287948007947125 9567.0
/gate/source/mybeam/gps/hist/point 1.5718565941175622 9303.0
/gate/source/mybeam/gps/hist/point 1.6149183874404116 8772.0
/gate/source/mybeam/gps/hist/point 1.657980180763261 8607.0
/gate/source/mybeam/gps/hist/point 1.7010419740861107 8381.0
/gate/source/mybeam/gps/hist/point 1.7441037674089603 8089.0
/gate/source/mybeam/gps/hist/point 1.7871655607318098 7953.0
/gate/source/mybeam/gps/hist/point 1.8302273540546594 7582.0
/gate/source/mybeam/gps/hist/point 1.873289147377509 7382.0
/gate/source/mybeam/gps/hist/point 1.9163509407003585 7157.0
/gate/source/mybeam/gps/hist/point 1.959412734023208 6982.0
/gate/source/mybeam/gps/hist/point 2.002474527346058 6815.0
/gate/source/mybeam/gps/hist/point 2.0455363206689072 6543.0
/gate/source/mybeam/gps/hist/point 2.0885981139917567 6170.0
/gate/source/mybeam/gps/hist/point 2.1316599073146065 6327.0
/gate/source/mybeam/gps/hist/point 2.1747217006374555 5959.0
/gate/source/mybeam/gps/hist/point 2.2177834939603054 5477.0
/gate/source/mybeam/gps/hist/point 2.2608452872831553 5588.0
/gate/source/mybeam/gps/hist/point 2.3039070806060042 5390.0
/gate/source/mybeam/gps/hist/point 2.346968873928854 5167.0
/gate/source/mybeam/gps/hist/point 2.3900306672517035 5083.0
/gate/source/mybeam/gps/hist/point 2.433092460574553 4875.0
/gate/source/mybeam/gps/hist/point 2.476154253897403 4715.0
/gate/source/mybeam/gps/hist/point 2.5192160472202523 4558.0
/gate/source/mybeam/gps/hist/point 2.5622778405431017 4394.0
/gate/source/mybeam/gps/hist/point 2.6053396338659516 4244.0
/gate/source/mybeam/gps/hist/point 2.6484014271888006 4067.0
/gate/source/mybeam/gps/hist/point 2.6914632205116504 4116.0
/gate/source/mybeam/gps/hist/point 2.7345250138345003 3882.0
/gate/source/mybeam/gps/hist/point 2.7775868071573493 3836.0
/gate/source/mybeam/gps/hist/point 2.820648600480199 3560.0
/gate/source/mybeam/gps/hist/point 2.863710393803049 3535.0
/gate/source/mybeam/gps/hist/point 2.906772187125898 3378.0
/gate/source/mybeam/gps/hist/point 2.949833980448748 3258.0
/gate/source/mybeam/gps/hist/point 2.9928957737715973 3108.0
/gate/source/mybeam/gps/hist/point 3.0359575670944468 3108.0
/gate/source/mybeam/gps/hist/point 3.0790193604172966 2929.0
/gate/source/mybeam/gps/hist/point 3.122081153740146 2843.0
/gate/source/mybeam/gps/hist/point 3.1651429470629955 2698.0
/gate/source/mybeam/gps/hist/point 3.2082047403858454 2705.0
/gate/source/mybeam/gps/hist/point 3.2512665337086943 2575.0
/gate/source/mybeam/gps/hist/point 3.294328327031544 2558.0
/gate/source/mybeam/gps/hist/point 3.337390120354394 2395.0
/gate/source/mybeam/gps/hist/point 3.380451913677243 2287.0
/gate/source/mybeam/gps/hist/point 3.423513707000093 2260.0
/gate/source/mybeam/gps/hist/point 3.4665755003229424 2074.0
/gate/source/mybeam/gps/hist/point 3.509637293645792 2004.0
/gate/source/mybeam/gps/hist/point 3.5526990869686417 1932.0
/gate/source/mybeam/gps/hist/point 3.595760880291491 1928.0
/gate/source/mybeam/gps/hist/point 3.6388226736143405 1844.0
/gate/source/mybeam/gps/hist/point 3.6818844669371904 1791.0
/gate/source/mybeam/gps/hist/point 3.7249462602600394 1670.0
/gate/source/mybeam/gps/hist/point 3.7680080535828893 1630.0
/gate/source/mybeam/gps/hist/point 3.811069846905739 1579.0
/gate/source/mybeam/gps/hist/point 3.854131640228588 1426.0
/gate/source/mybeam/gps/hist/point 3.897193433551438 1400.0
/gate/source/mybeam/gps/hist/point 3.940255226874288 1330.0
/gate/source/mybeam/gps/hist/point 3.9833170201971373 1306.0
/gate/source/mybeam/gps/hist/point 4.026378813519987 1200.0
/gate/source/mybeam/gps/hist/point 4.069440606842836 1216.0
/gate/source/mybeam/gps/hist/point 4.1125024001656865 1183.0
/gate/source/mybeam/gps/hist/point 4.1555641934885355 1091.0
/gate/source/mybeam/gps/hist/point 4.198625986811384 1037.0
/gate/source/mybeam/gps/hist/point 4.241687780134234 956.0
/gate/source/mybeam/gps/hist/point 4.284749573457084 928.0
/gate/source/mybeam/gps/hist/point 4.327811366779933 862.0
/gate/source/mybeam/gps/hist/point 4.370873160102783 870.0
/gate/source/mybeam/gps/hist/point 4.413934953425633 789.0
/gate/source/mybeam/gps/hist/point 4.456996746748482 779.0
/gate/source/mybeam/gps/hist/point 4.500058540071332 782.0
/gate/source/mybeam/gps/hist/point 4.543120333394182 730.0
/gate/source/mybeam/gps/hist/point 4.586182126717031 656.0
/gate/source/mybeam/gps/hist/point 4.6292439200398805 616.0
/gate/source/mybeam/gps/hist/point 4.67230571336273 616.0
/gate/source/mybeam/gps/hist/point 4.715367506685579 576.0
/gate/source/mybeam/gps/hist/point 4.758429300008428 509.0
/gate/source/mybeam/gps/hist/point 4.801491093331279 527.0
/gate/source/mybeam/gps/hist/point 4.844552886654128 471.0
/gate/source/mybeam/gps/hist/point 4.887614679976977 454.0
/gate/source/mybeam/gps/hist/point 4.930676473299828 457.0
/gate/source/mybeam/gps/hist/point 4.973738266622677 425.0
/gate/source/mybeam/gps/hist/point 5.016800059945526 401.0
/gate/source/mybeam/gps/hist/point 5.059861853268377 331.0
/gate/source/mybeam/gps/hist/point 5.1029236465912255 339.0
/gate/source/mybeam/gps/hist/point 5.1459854399140745 354.0
/gate/source/mybeam/gps/hist/point 5.189047233236925 278.0
/gate/source/mybeam/gps/hist/point 5.232109026559774 289.0
/gate/source/mybeam/gps/hist/point 5.275170819882623 241.0
/gate/source/mybeam/gps/hist/point 5.318232613205473 261.0
/gate/source/mybeam/gps/hist/point 5.361294406528323 247.0
/gate/source/mybeam/gps/hist/point 5.404356199851172 226.0
/gate/source/mybeam/gps/hist/point 5.447417993174022 182.0
/gate/source/mybeam/gps/hist/point 5.490479786496872 183.0
/gate/source/mybeam/gps/hist/point 5.533541579819721 165.0
/gate/source/mybeam/gps/hist/point 5.576603373142571 141.0
/gate/source/mybeam/gps/hist/point 5.6196651664654205 132.0
/gate/source/mybeam/gps/hist/point 5.6627269597882695 137.0
/gate/source/mybeam/gps/hist/point 5.705788753111119 127.0
/gate/source/mybeam/gps/hist/point 5.748850546433969 111.0
/gate/source/mybeam/gps/hist/point 5.791912339756818 98.0
/gate/source/mybeam/gps/hist/point 5.834974133079667 79.0
/gate/source/mybeam/gps/hist/point 5.878035926402518 82.0
/gate/source/mybeam/gps/hist/point 5.921097719725367 54.0
/gate/source/mybeam/gps/hist/point 5.964159513048216 51.0
/gate/source/mybeam/gps/hist/point 6.007221306371067 60.0
/gate/source/mybeam/gps/hist/point 6.050283099693916 34.0
/gate/source/mybeam/gps/hist/point 6.093344893016765 38.0
/gate/source/mybeam/gps/hist/point 6.136406686339615 18.0
/gate/source/mybeam/gps/hist/point 6.179468479662464 24.0
/gate/source/mybeam/gps/hist/point 6.222530272985313 14.0
/gate/source/mybeam/gps/hist/point 6.265592066308164 16.0
/gate/source/mybeam/gps/hist/point 6.308653859631013 7.0
/gate/source/mybeam/gps/hist/point 6.351715652953862 10.0
/gate/source/mybeam/gps/hist/point 6.394777446276712 4.0
/gate/source/mybeam/gps/hist/point 6.437839239599562 2.0
/gate/source/mybeam/gps/hist/inter Log

#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed {seed}
#1234567890
/gate/application/noGlobalOutput

#/tracking/verbose 2

/gate/application/setTotalNumberOfPrimaries {primaries}
#1000
/gate/application/start
