# INPUTS
# pathOutputDose
# id
# seed 
# primaries
# peakzlength_um
# peakztrans_mm
# peakzlength2_um
# peakztrans2_mm
# peakzlength3_um
# peakztrans3_mm
# peakzlength4_um
# peakztrans4_mm
# peak_material

# Gate /home/as17540/linac/mac/Main_PhS2_Elec_Sensor_1.3xSeaLevel_0.mac -a '[id,$PBS_ARRAY_INDEX] [peakzlength2_um,30] [peakztrans2_mm,-5.485] [peakzlength3_um,50] [peakztrans3_mm,-5.475] [peakzlength4_um,70] [peakztrans4_mm,-5.465] [peak_material,Copper] [seed,$RANDOM$RANDOM$RANDOM] [primaries,12063400] [pathOutputDose,/work/as17540/PhaseSpaces/PhS3_Sensor_10x10_Elec/]'

#=====================================================
# VISUALISATION
#=====================================================

#/control/execute mac/visu.mac

# =====================================================
# GEOMETRY
# =====================================================

/gate/geometry/setMaterialDatabase /home/as17540/linac/data/GateMaterials_1.3xSeaLevel.db

# WORLD
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    0.3 m
/gate/world/geometry/setYLength    0.3 m
/gate/world/geometry/setZLength    1 m
/gate/world/vis/setVisible 1

/gate/world/daughters/name                   PhS_Plane_Two
/gate/world/daughters/insert                 box
/gate/PhS_Plane_Two/setMaterial              Vacuum
/gate/PhS_Plane_Two/geometry/setXLength      22 cm
/gate/PhS_Plane_Two/geometry/setYLength      22 cm
/gate/PhS_Plane_Two/geometry/setZLength      1 nm
/gate/PhS_Plane_Two/placement/setTranslation 0.0 0.0 471 mm #(-529)
/gate/PhS_Plane_Two/vis/setColor             cyan
/gate/PhS_Plane_Two/vis/setVisible           1

/gate/world/daughters/name                   Kill_BackPlane
/gate/world/daughters/insert                 box
/gate/Kill_BackPlane/setMaterial                   Air	
/gate/Kill_BackPlane/geometry/setXLength           30 cm
/gate/Kill_BackPlane/geometry/setYLength           30 cm
/gate/Kill_BackPlane/geometry/setZLength           1 nm
/gate/Kill_BackPlane/placement/setTranslation      0.0 0.0 480 mm
/gate/Kill_BackPlane/vis/setColor                  red
/gate/Kill_BackPlane/vis/setVisible                1

/gate/world/daughters/name                   Kill_FrontPlane
/gate/world/daughters/insert                 box
/gate/Kill_FrontPlane/setMaterial                   Air	
/gate/Kill_FrontPlane/geometry/setXLength           30 cm
/gate/Kill_FrontPlane/geometry/setYLength           30 cm
/gate/Kill_FrontPlane/geometry/setZLength           1 nm
/gate/Kill_FrontPlane/placement/setTranslation      0.0 0.0 445 mm
/gate/Kill_FrontPlane/vis/setColor                  red
/gate/Kill_FrontPlane/vis/setVisible                1

/gate/world/daughters/name         epi
/gate/world/daughters/insert       box
/gate/epi/setMaterial                  Silicon
/gate/epi/geometry/setXLength          180.0 mm
/gate/epi/geometry/setYLength          180.0 mm
/gate/epi/geometry/setZLength          0.01 mm
/gate/epi/placement/setTranslation     0 0 449.995 mm
/gate/epi/vis/setVisible               1
/gate/epi/vis/setColor                 yellow
/gate/epi/vis/forceSolid

/gate/world/daughters/name         bulk
/gate/world/daughters/insert       box
/gate/bulk/setMaterial                  Silicon
/gate/bulk/geometry/setXLength          180.0 mm
/gate/bulk/geometry/setYLength          180.0 mm
/gate/bulk/geometry/setZLength          0.6 mm
/gate/bulk/placement/setTranslation     0 0 449.69 mm
/gate/bulk/vis/setVisible               1
/gate/bulk/vis/setColor                 red

/gate/world/daughters/name         peak_air_box 
/gate/world/daughters/insert       box 
/gate/peak_air_box/setMaterial                  Air 
/gate/peak_air_box/geometry/setXLength          200.0 mm 
/gate/peak_air_box/geometry/setYLength          200.0 mm 
/gate/peak_air_box/geometry/setZLength          11 mm 
/gate/peak_air_box/placement/setTranslation     0 0 455.5 mm
/gate/peak_air_box/vis/setVisible               1 
/gate/peak_air_box/vis/setColor                 green
/gate/peak_air_box/vis/forceWireframe

#/gate/peak_air_box/daughters/name         peakLayer1 
#/gate/peak_air_box/daughters/insert       box 
#/gate/peakLayer1/setMaterial                  {peak_material} 
#/gate/peakLayer1/geometry/setXLength          10.0 mm 
#/gate/peakLayer1/geometry/setYLength          10.0 mm 
#/gate/peakLayer1/geometry/setZLength          {peakzlength_um} um 
#/gate/peakLayer1/placement/setTranslation     -5 5 {peakztrans_mm} mm
#/gate/peakLayer1/vis/setVisible               1 
#/gate/peakLayer1/vis/setColor                 grey
#/gate/peakLayer1/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer2 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer2/setMaterial                  {peak_material} 
/gate/peakLayer2/geometry/setXLength          10.0 mm 
/gate/peakLayer2/geometry/setYLength          10.0 mm 
/gate/peakLayer2/geometry/setZLength          {peakzlength2_um} um 
/gate/peakLayer2/placement/setTranslation     5 5 {peakztrans2_mm} mm
/gate/peakLayer2/vis/setVisible               1 
/gate/peakLayer2/vis/setColor                 red
/gate/peakLayer2/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer3 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer3/setMaterial                  {peak_material} 
/gate/peakLayer3/geometry/setXLength          10.0 mm 
/gate/peakLayer3/geometry/setYLength          10.0 mm 
/gate/peakLayer3/geometry/setZLength          {peakzlength3_um} um 
/gate/peakLayer3/placement/setTranslation     -5 -5 {peakztrans3_mm} mm
/gate/peakLayer3/vis/setVisible               1 
/gate/peakLayer3/vis/setColor                 red
/gate/peakLayer3/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer4 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer4/setMaterial                  {peak_material} 
/gate/peakLayer4/geometry/setXLength          10.0 mm 
/gate/peakLayer4/geometry/setYLength          10.0 mm 
/gate/peakLayer4/geometry/setZLength          {peakzlength4_um} um 
/gate/peakLayer4/placement/setTranslation     5 -5 {peakztrans4_mm} mm
/gate/peakLayer4/vis/setVisible               1 
/gate/peakLayer4/vis/setColor                 red
/gate/peakLayer4/vis/forceSolid

# =====================================================
# PHYSICS
# =====================================================

/gate/physics/addPhysicsList emstandard_opt4

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      epi 0.0001 mm 
/gate/physics/Electron/SetCutInRegion   epi 0.0001 mm
/gate/physics/Positron/SetCutInRegion   epi 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      bulk 0.0001 mm
/gate/physics/Electron/SetCutInRegion   bulk 0.0001 mm
/gate/physics/Positron/SetCutInRegion   bulk 0.0001 mm

#/gate/physics/Gamma/SetCutInRegion      peakLayer1 0.0001 mm #0.0001
#/gate/physics/Electron/SetCutInRegion   peakLayer1 0.0001 mm
#/gate/physics/Positron/SetCutInRegion   peakLayer1 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer2 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer2 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer2 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer3 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer3 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer3 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer4 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer4 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer4 0.0001 mm

#=====================================================
# DETECTORS
#=====================================================

## 
## Dose output electron
## 
/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  {pathOutputDose}/Epi-00-{peakzlength2_um}-{peakzlength3_um}-{peakzlength4_um}_peakum-{peak_material}-1.3xSeaLevel-{id}.root
/gate/actor/doseDistribution/attachTo              epi
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setSize               50 50 0.010 mm
/gate/actor/doseDistribution/setResolution         1000 1000 1	 #for 60 micron pixel x4
/gate/actor/doseDistribution/enableNumberOfHits    true
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep false
/gate/actor/doseDistribution/enableSquaredEdep     true
/gate/actor/doseDistribution/enableDose            false
/gate/actor/doseDistribution/enableUncertaintyDose false


/gate/actor/addActor   KillActor                         Kill_BP 
/gate/actor/Kill_BP/attachTo                             Kill_BackPlane 

/gate/actor/addActor   KillActor                         Kill_FP 
/gate/actor/Kill_FP/attachTo                             Kill_FrontPlane 

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize
# /process/em/setBiasingFactor compt 100 True

# /process/em/setSecBiasing compt peakLayer1 100 1000 MeV
# /particle/process/dump

#=====================================================
# BEAMS
#=====================================================

# Read from Phase Space files. Here we indicate the type of particle
# (gamma) because this information is not stored in the PhS to gain
# space. Moreover, we set 'useRandomSymmetry' to generate more
# particle than the number of particle in the PhS, using a Z axis
# symmetry.

#/gate/source/addSource                         beam_g phaseSpace
#/gate/source/beam_g/addPhaseSpaceFile          {inputPhaseSpaceFile}
#{inputParticleType}
#/gate/source/beam_g/attachTo                   PhS_Plane_Two
#/gate/source/beam_g/useRandomSymmetry          true

/gate/source/addSource mybeam gps 
/gate/source/mybeam/gps/particle e- 
/gate/source/mybeam/gps/pos/centre 0 0 471 mm 
/gate/source/mybeam/gps/direction 0 0 -1 
/gate/source/mybeam/gps/type Plane 
/gate/source/mybeam/gps/shape Square 
/gate/source/mybeam/gps/halfx 2 cm 
/gate/source/mybeam/gps/halfy 2 cm 
/gate/source/mybeam/gps/ene/type Arb 
/gate/source/mybeam/gps/hist/type arb 
/gate/source/mybeam/gps/hist/point 0.021793879137549085 16378.0
/gate/source/mybeam/gps/hist/point 0.06516855924768607 22448.0
/gate/source/mybeam/gps/hist/point 0.10854323935782305 27718.0
/gate/source/mybeam/gps/hist/point 0.15191791946796002 29904.0
/gate/source/mybeam/gps/hist/point 0.19529259957809703 30456.0
/gate/source/mybeam/gps/hist/point 0.23866727968823398 30019.0
/gate/source/mybeam/gps/hist/point 0.282041959798371 29167.0
/gate/source/mybeam/gps/hist/point 0.32541663990850794 28258.0
/gate/source/mybeam/gps/hist/point 0.36879132001864495 26903.0
/gate/source/mybeam/gps/hist/point 0.4121660001287819 25766.0
/gate/source/mybeam/gps/hist/point 0.4555406802389189 24701.0
/gate/source/mybeam/gps/hist/point 0.49891536034905587 23640.0
/gate/source/mybeam/gps/hist/point 0.5422900404591928 22439.0
/gate/source/mybeam/gps/hist/point 0.5856647205693298 21333.0
/gate/source/mybeam/gps/hist/point 0.6290394006794668 20766.0
/gate/source/mybeam/gps/hist/point 0.6724140807896037 19866.0
/gate/source/mybeam/gps/hist/point 0.7157887608997409 19055.0
/gate/source/mybeam/gps/hist/point 0.7591634410098778 18188.0
/gate/source/mybeam/gps/hist/point 0.8025381211200148 17826.0
/gate/source/mybeam/gps/hist/point 0.8459128012301518 17009.0
/gate/source/mybeam/gps/hist/point 0.8892874813402887 16397.0
/gate/source/mybeam/gps/hist/point 0.9326621614504257 15674.0
/gate/source/mybeam/gps/hist/point 0.9760368415605627 15114.0
/gate/source/mybeam/gps/hist/point 1.0194115216706996 14614.0
/gate/source/mybeam/gps/hist/point 1.0627862017808365 13971.0
/gate/source/mybeam/gps/hist/point 1.1061608818909736 13919.0
/gate/source/mybeam/gps/hist/point 1.1495355620011107 13240.0
/gate/source/mybeam/gps/hist/point 1.1929102421112474 12731.0
/gate/source/mybeam/gps/hist/point 1.2362849222213845 12326.0
/gate/source/mybeam/gps/hist/point 1.2796596023315217 12047.0
/gate/source/mybeam/gps/hist/point 1.3230342824416585 11486.0
/gate/source/mybeam/gps/hist/point 1.3664089625517954 10974.0
/gate/source/mybeam/gps/hist/point 1.4097836426619326 10829.0
/gate/source/mybeam/gps/hist/point 1.4531583227720695 10536.0
/gate/source/mybeam/gps/hist/point 1.4965330028822064 10009.0
/gate/source/mybeam/gps/hist/point 1.5399076829923435 9627.0
/gate/source/mybeam/gps/hist/point 1.5832823631024806 9260.0
/gate/source/mybeam/gps/hist/point 1.6266570432126173 9030.0
/gate/source/mybeam/gps/hist/point 1.6700317233227544 8833.0
/gate/source/mybeam/gps/hist/point 1.7134064034328915 8466.0
/gate/source/mybeam/gps/hist/point 1.7567810835430282 8232.0
/gate/source/mybeam/gps/hist/point 1.8001557636531653 7924.0
/gate/source/mybeam/gps/hist/point 1.8435304437633024 7734.0
/gate/source/mybeam/gps/hist/point 1.8869051238734391 7459.0
/gate/source/mybeam/gps/hist/point 1.9302798039835762 7377.0
/gate/source/mybeam/gps/hist/point 1.9736544840937134 7159.0
/gate/source/mybeam/gps/hist/point 2.01702916420385 6823.0
/gate/source/mybeam/gps/hist/point 2.060403844313987 6564.0
/gate/source/mybeam/gps/hist/point 2.1037785244241243 6345.0
/gate/source/mybeam/gps/hist/point 2.147153204534261 6030.0
/gate/source/mybeam/gps/hist/point 2.190527884644398 6081.0
/gate/source/mybeam/gps/hist/point 2.233902564754535 5803.0
/gate/source/mybeam/gps/hist/point 2.2772772448646723 5651.0
/gate/source/mybeam/gps/hist/point 2.320651924974809 5360.0
/gate/source/mybeam/gps/hist/point 2.364026605084946 5175.0
/gate/source/mybeam/gps/hist/point 2.407401285195083 4949.0
/gate/source/mybeam/gps/hist/point 2.45077596530522 5037.0
/gate/source/mybeam/gps/hist/point 2.494150645415357 4727.0
/gate/source/mybeam/gps/hist/point 2.537525325525494 4653.0
/gate/source/mybeam/gps/hist/point 2.5809000056356313 4500.0
/gate/source/mybeam/gps/hist/point 2.624274685745768 4275.0
/gate/source/mybeam/gps/hist/point 2.667649365855905 4149.0
/gate/source/mybeam/gps/hist/point 2.7110240459660417 4082.0
/gate/source/mybeam/gps/hist/point 2.754398726076179 3880.0
/gate/source/mybeam/gps/hist/point 2.797773406186316 3861.0
/gate/source/mybeam/gps/hist/point 2.841148086296453 3736.0
/gate/source/mybeam/gps/hist/point 2.8845227664065898 3549.0
/gate/source/mybeam/gps/hist/point 2.927897446516727 3367.0
/gate/source/mybeam/gps/hist/point 2.9712721266268636 3352.0
/gate/source/mybeam/gps/hist/point 3.0146468067370007 3223.0
/gate/source/mybeam/gps/hist/point 3.058021486847138 3049.0
/gate/source/mybeam/gps/hist/point 3.101396166957275 3029.0
/gate/source/mybeam/gps/hist/point 3.144770847067412 2838.0
/gate/source/mybeam/gps/hist/point 3.1881455271775487 2779.0
/gate/source/mybeam/gps/hist/point 3.231520207287686 2709.0
/gate/source/mybeam/gps/hist/point 3.2748948873978225 2523.0
/gate/source/mybeam/gps/hist/point 3.3182695675079596 2414.0
/gate/source/mybeam/gps/hist/point 3.3616442476180968 2335.0
/gate/source/mybeam/gps/hist/point 3.405018927728234 2255.0
/gate/source/mybeam/gps/hist/point 3.4483936078383706 2230.0
/gate/source/mybeam/gps/hist/point 3.4917682879485077 2123.0
/gate/source/mybeam/gps/hist/point 3.5351429680586444 2069.0
/gate/source/mybeam/gps/hist/point 3.5785176481687815 1956.0
/gate/source/mybeam/gps/hist/point 3.6218923282789186 1889.0
/gate/source/mybeam/gps/hist/point 3.6652670083890557 1759.0
/gate/source/mybeam/gps/hist/point 3.7086416884991924 1731.0
/gate/source/mybeam/gps/hist/point 3.7520163686093295 1708.0
/gate/source/mybeam/gps/hist/point 3.795391048719466 1612.0
/gate/source/mybeam/gps/hist/point 3.8387657288296033 1563.0
/gate/source/mybeam/gps/hist/point 3.8821404089397404 1466.0
/gate/source/mybeam/gps/hist/point 3.9255150890498776 1422.0
/gate/source/mybeam/gps/hist/point 3.9688897691600147 1409.0
/gate/source/mybeam/gps/hist/point 4.012264449270151 1299.0
/gate/source/mybeam/gps/hist/point 4.055639129380288 1299.0
/gate/source/mybeam/gps/hist/point 4.099013809490425 1206.0
/gate/source/mybeam/gps/hist/point 4.142388489600562 1171.0
/gate/source/mybeam/gps/hist/point 4.185763169710699 1089.0
/gate/source/mybeam/gps/hist/point 4.2291378498208365 1050.0
/gate/source/mybeam/gps/hist/point 4.272512529930974 1020.0
/gate/source/mybeam/gps/hist/point 4.31588721004111 924.0
/gate/source/mybeam/gps/hist/point 4.359261890151247 923.0
/gate/source/mybeam/gps/hist/point 4.402636570261384 922.0
/gate/source/mybeam/gps/hist/point 4.446011250371521 836.0
/gate/source/mybeam/gps/hist/point 4.489385930481658 837.0
/gate/source/mybeam/gps/hist/point 4.5327606105917955 740.0
/gate/source/mybeam/gps/hist/point 4.576135290701933 708.0
/gate/source/mybeam/gps/hist/point 4.619509970812069 696.0
/gate/source/mybeam/gps/hist/point 4.662884650922206 628.0
/gate/source/mybeam/gps/hist/point 4.706259331032343 619.0
/gate/source/mybeam/gps/hist/point 4.74963401114248 569.0
/gate/source/mybeam/gps/hist/point 4.793008691252617 551.0
/gate/source/mybeam/gps/hist/point 4.8363833713627535 496.0
/gate/source/mybeam/gps/hist/point 4.879758051472891 477.0
/gate/source/mybeam/gps/hist/point 4.923132731583028 480.0
/gate/source/mybeam/gps/hist/point 4.966507411693165 431.0
/gate/source/mybeam/gps/hist/point 5.009882091803302 383.0
/gate/source/mybeam/gps/hist/point 5.053256771913439 384.0
/gate/source/mybeam/gps/hist/point 5.096631452023576 342.0
/gate/source/mybeam/gps/hist/point 5.140006132133713 322.0
/gate/source/mybeam/gps/hist/point 5.18338081224385 331.0
/gate/source/mybeam/gps/hist/point 5.226755492353987 315.0
/gate/source/mybeam/gps/hist/point 5.270130172464124 279.0
/gate/source/mybeam/gps/hist/point 5.313504852574261 252.0
/gate/source/mybeam/gps/hist/point 5.356879532684398 254.0
/gate/source/mybeam/gps/hist/point 5.400254212794534 222.0
/gate/source/mybeam/gps/hist/point 5.4436288929046714 231.0
/gate/source/mybeam/gps/hist/point 5.487003573014809 195.0
/gate/source/mybeam/gps/hist/point 5.530378253124946 196.0
/gate/source/mybeam/gps/hist/point 5.573752933235083 181.0
/gate/source/mybeam/gps/hist/point 5.61712761334522 157.0
/gate/source/mybeam/gps/hist/point 5.660502293455357 126.0
/gate/source/mybeam/gps/hist/point 5.703876973565494 124.0
/gate/source/mybeam/gps/hist/point 5.74725165367563 104.0
/gate/source/mybeam/gps/hist/point 5.7906263337857675 98.0
/gate/source/mybeam/gps/hist/point 5.834001013895905 85.0
/gate/source/mybeam/gps/hist/point 5.877375694006042 86.0
/gate/source/mybeam/gps/hist/point 5.920750374116179 71.0
/gate/source/mybeam/gps/hist/point 5.964125054226315 61.0
/gate/source/mybeam/gps/hist/point 6.007499734336452 44.0
/gate/source/mybeam/gps/hist/point 6.050874414446589 43.0
/gate/source/mybeam/gps/hist/point 6.0942490945567265 35.0
/gate/source/mybeam/gps/hist/point 6.137623774666864 26.0
/gate/source/mybeam/gps/hist/point 6.180998454777001 20.0
/gate/source/mybeam/gps/hist/point 6.224373134887138 22.0
/gate/source/mybeam/gps/hist/point 6.267747814997275 16.0
/gate/source/mybeam/gps/hist/point 6.311122495107411 9.0
/gate/source/mybeam/gps/hist/point 6.354497175217548 11.0
/gate/source/mybeam/gps/hist/point 6.397871855327685 3.0
/gate/source/mybeam/gps/hist/point 6.4412465354378226 1.0
/gate/source/mybeam/gps/hist/point 6.484621215547959 1.0
/gate/source/mybeam/gps/hist/inter Log

#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed {seed}
#1234567890
/gate/application/noGlobalOutput

#/tracking/verbose 2

/gate/application/setTotalNumberOfPrimaries {primaries}
#1000
/gate/application/start
