# INPUTS
# pathOutputDose
# id
# seed 
# primaries
# peakzlength2_um
# peakztrans2_mm
# peakzlength3_um
# peakztrans3_mm
# peakzlength4_um
# peakztrans4_mm
# peak_material

# Gate /home/as17540/linac/mac/Main_PhS2_Elec_Sensor_0.85xSeaLevel_0.mac -a '[id,$PBS_ARRAY_INDEX] [peakzlength2_um,30] [peakztrans2_mm,-5.485] [peakzlength3_um,50] [peakztrans3_mm,-5.475] [peakzlength4_um,70] [peakztrans4_mm,-5.465] [peak_material,Copper] [seed,$RANDOM$RANDOM$RANDOM] [primaries,10783000] [pathOutputDose,/work/as17540/PhaseSpaces/PhS3_Sensor_10x10_Elec/]'

#=====================================================
# VISUALISATION
#=====================================================

#/control/execute mac/visu.mac

# =====================================================
# GEOMETRY
# =====================================================

/gate/geometry/setMaterialDatabase /home/as17540/linac/data/GateMaterials_0.85xSeaLevel.db

# WORLD
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    0.3 m
/gate/world/geometry/setYLength    0.3 m
/gate/world/geometry/setZLength    1 m
/gate/world/vis/setVisible 1

/gate/world/daughters/name                   PhS_Plane_Two
/gate/world/daughters/insert                 box
/gate/PhS_Plane_Two/setMaterial              Vacuum
/gate/PhS_Plane_Two/geometry/setXLength      22 cm
/gate/PhS_Plane_Two/geometry/setYLength      22 cm
/gate/PhS_Plane_Two/geometry/setZLength      1 nm
/gate/PhS_Plane_Two/placement/setTranslation 0.0 0.0 471 mm #(-529)
/gate/PhS_Plane_Two/vis/setColor             cyan
/gate/PhS_Plane_Two/vis/setVisible           1

/gate/world/daughters/name                   Kill_BackPlane
/gate/world/daughters/insert                 box
/gate/Kill_BackPlane/setMaterial                   Air	
/gate/Kill_BackPlane/geometry/setXLength           30 cm
/gate/Kill_BackPlane/geometry/setYLength           30 cm
/gate/Kill_BackPlane/geometry/setZLength           1 nm
/gate/Kill_BackPlane/placement/setTranslation      0.0 0.0 480 mm
/gate/Kill_BackPlane/vis/setColor                  red
/gate/Kill_BackPlane/vis/setVisible                1

/gate/world/daughters/name                   Kill_FrontPlane
/gate/world/daughters/insert                 box
/gate/Kill_FrontPlane/setMaterial                   Air	
/gate/Kill_FrontPlane/geometry/setXLength           30 cm
/gate/Kill_FrontPlane/geometry/setYLength           30 cm
/gate/Kill_FrontPlane/geometry/setZLength           1 nm
/gate/Kill_FrontPlane/placement/setTranslation      0.0 0.0 445 mm
/gate/Kill_FrontPlane/vis/setColor                  red
/gate/Kill_FrontPlane/vis/setVisible                1

/gate/world/daughters/name         epi
/gate/world/daughters/insert       box
/gate/epi/setMaterial                  Silicon
/gate/epi/geometry/setXLength          180.0 mm
/gate/epi/geometry/setYLength          180.0 mm
/gate/epi/geometry/setZLength          0.01 mm
/gate/epi/placement/setTranslation     0 0 449.995 mm
/gate/epi/vis/setVisible               1
/gate/epi/vis/setColor                 yellow
/gate/epi/vis/forceSolid

/gate/world/daughters/name         bulk
/gate/world/daughters/insert       box
/gate/bulk/setMaterial                  Silicon
/gate/bulk/geometry/setXLength          180.0 mm
/gate/bulk/geometry/setYLength          180.0 mm
/gate/bulk/geometry/setZLength          0.6 mm
/gate/bulk/placement/setTranslation     0 0 449.69 mm
/gate/bulk/vis/setVisible               1
/gate/bulk/vis/setColor                 red

/gate/world/daughters/name         peak_air_box 
/gate/world/daughters/insert       box 
/gate/peak_air_box/setMaterial                  Air 
/gate/peak_air_box/geometry/setXLength          200.0 mm 
/gate/peak_air_box/geometry/setYLength          200.0 mm 
/gate/peak_air_box/geometry/setZLength          11 mm 
/gate/peak_air_box/placement/setTranslation     0 0 455.5 mm
/gate/peak_air_box/vis/setVisible               1 
/gate/peak_air_box/vis/setColor                 green
/gate/peak_air_box/vis/forceWireframe

#/gate/peak_air_box/daughters/name         peakLayer1 
#/gate/peak_air_box/daughters/insert       box 
#/gate/peakLayer1/setMaterial                  {peak_material} 
#/gate/peakLayer1/geometry/setXLength          10.0 mm 
#/gate/peakLayer1/geometry/setYLength          10.0 mm 
#/gate/peakLayer1/geometry/setZLength          {peakzlength_um} um 
#/gate/peakLayer1/placement/setTranslation     -5 5 {peakztrans_mm} mm
#/gate/peakLayer1/vis/setVisible               1 
#/gate/peakLayer1/vis/setColor                 grey
#/gate/peakLayer1/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer2 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer2/setMaterial                  {peak_material} 
/gate/peakLayer2/geometry/setXLength          10.0 mm 
/gate/peakLayer2/geometry/setYLength          10.0 mm 
/gate/peakLayer2/geometry/setZLength          {peakzlength2_um} um 
/gate/peakLayer2/placement/setTranslation     5 5 {peakztrans2_mm} mm
/gate/peakLayer2/vis/setVisible               1 
/gate/peakLayer2/vis/setColor                 red
/gate/peakLayer2/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer3 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer3/setMaterial                  {peak_material} 
/gate/peakLayer3/geometry/setXLength          10.0 mm 
/gate/peakLayer3/geometry/setYLength          10.0 mm 
/gate/peakLayer3/geometry/setZLength          {peakzlength3_um} um 
/gate/peakLayer3/placement/setTranslation     -5 -5 {peakztrans3_mm} mm
/gate/peakLayer3/vis/setVisible               1 
/gate/peakLayer3/vis/setColor                 red
/gate/peakLayer3/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer4 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer4/setMaterial                  {peak_material} 
/gate/peakLayer4/geometry/setXLength          10.0 mm 
/gate/peakLayer4/geometry/setYLength          10.0 mm 
/gate/peakLayer4/geometry/setZLength          {peakzlength4_um} um 
/gate/peakLayer4/placement/setTranslation     5 -5 {peakztrans4_mm} mm
/gate/peakLayer4/vis/setVisible               1 
/gate/peakLayer4/vis/setColor                 red
/gate/peakLayer4/vis/forceSolid

# =====================================================
# PHYSICS
# =====================================================

/gate/physics/addPhysicsList emstandard_opt4

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      epi 0.0001 mm 
/gate/physics/Electron/SetCutInRegion   epi 0.0001 mm
/gate/physics/Positron/SetCutInRegion   epi 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      bulk 0.0001 mm
/gate/physics/Electron/SetCutInRegion   bulk 0.0001 mm
/gate/physics/Positron/SetCutInRegion   bulk 0.0001 mm

#/gate/physics/Gamma/SetCutInRegion      peakLayer1 0.0001 mm #0.0001
#/gate/physics/Electron/SetCutInRegion   peakLayer1 0.0001 mm
#/gate/physics/Positron/SetCutInRegion   peakLayer1 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer2 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer2 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer2 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer3 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer3 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer3 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer4 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer4 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer4 0.0001 mm

#=====================================================
# DETECTORS
#=====================================================

## 
## Dose output electron
## 
/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  {pathOutputDose}/Epi-00-{peakzlength2_um}-{peakzlength3_um}-{peakzlength4_um}_peakum-{peak_material}-0.85xSeaLevel-{id}.root
/gate/actor/doseDistribution/attachTo              epi
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setSize               50 50 0.010 mm
/gate/actor/doseDistribution/setResolution         1000 1000 1	 #for 60 micron pixel x4
/gate/actor/doseDistribution/enableNumberOfHits    true
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep false
/gate/actor/doseDistribution/enableSquaredEdep     true
/gate/actor/doseDistribution/enableDose            false
/gate/actor/doseDistribution/enableUncertaintyDose false


/gate/actor/addActor   KillActor                         Kill_BP 
/gate/actor/Kill_BP/attachTo                             Kill_BackPlane 

/gate/actor/addActor   KillActor                         Kill_FP 
/gate/actor/Kill_FP/attachTo                             Kill_FrontPlane 

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize
# /process/em/setBiasingFactor compt 100 True

# /process/em/setSecBiasing compt peakLayer1 100 1000 MeV
# /particle/process/dump

#=====================================================
# BEAMS
#=====================================================

# Read from Phase Space files. Here we indicate the type of particle
# (gamma) because this information is not stored in the PhS to gain
# space. Moreover, we set 'useRandomSymmetry' to generate more
# particle than the number of particle in the PhS, using a Z axis
# symmetry.

#/gate/source/addSource                         beam_g phaseSpace
#/gate/source/beam_g/addPhaseSpaceFile          {inputPhaseSpaceFile}
#{inputParticleType}
#/gate/source/beam_g/attachTo                   PhS_Plane_Two
#/gate/source/beam_g/useRandomSymmetry          true

/gate/source/addSource mybeam gps 
/gate/source/mybeam/gps/particle e- 
/gate/source/mybeam/gps/pos/centre 0 0 471 mm 
/gate/source/mybeam/gps/direction 0 0 -1 
/gate/source/mybeam/gps/type Plane 
/gate/source/mybeam/gps/shape Square 
/gate/source/mybeam/gps/halfx 2 cm 
/gate/source/mybeam/gps/halfy 2 cm 
/gate/source/mybeam/gps/ene/type Arb 
/gate/source/mybeam/gps/hist/type arb 
/gate/source/mybeam/gps/hist/point 0.021882585478330534 15895.0
/gate/source/mybeam/gps/hist/point 0.06544705305866955 21034.0
/gate/source/mybeam/gps/hist/point 0.10901152063900857 25372.0
/gate/source/mybeam/gps/hist/point 0.1525759882193476 27705.0
/gate/source/mybeam/gps/hist/point 0.19614045579968659 28052.0
/gate/source/mybeam/gps/hist/point 0.2397049233800256 27267.0
/gate/source/mybeam/gps/hist/point 0.28326939096036463 26452.0
/gate/source/mybeam/gps/hist/point 0.3268338585407037 25757.0
/gate/source/mybeam/gps/hist/point 0.3703983261210426 24411.0
/gate/source/mybeam/gps/hist/point 0.41396279370138167 23285.0
/gate/source/mybeam/gps/hist/point 0.4575272612817207 21913.0
/gate/source/mybeam/gps/hist/point 0.5010917288620597 20917.0
/gate/source/mybeam/gps/hist/point 0.5446561964423987 20263.0
/gate/source/mybeam/gps/hist/point 0.5882206640227378 18910.0
/gate/source/mybeam/gps/hist/point 0.6317851316030767 18580.0
/gate/source/mybeam/gps/hist/point 0.6753495991834157 17644.0
/gate/source/mybeam/gps/hist/point 0.7189140667637548 17033.0
/gate/source/mybeam/gps/hist/point 0.7624785343440939 16449.0
/gate/source/mybeam/gps/hist/point 0.8060430019244328 15816.0
/gate/source/mybeam/gps/hist/point 0.8496074695047718 15054.0
/gate/source/mybeam/gps/hist/point 0.8931719370851108 14512.0
/gate/source/mybeam/gps/hist/point 0.9367364046654498 14218.0
/gate/source/mybeam/gps/hist/point 0.9803008722457889 13508.0
/gate/source/mybeam/gps/hist/point 1.023865339826128 13181.0
/gate/source/mybeam/gps/hist/point 1.0674298074064668 12983.0
/gate/source/mybeam/gps/hist/point 1.110994274986806 12165.0
/gate/source/mybeam/gps/hist/point 1.1545587425671449 11724.0
/gate/source/mybeam/gps/hist/point 1.1981232101474841 11418.0
/gate/source/mybeam/gps/hist/point 1.241687677727823 11055.0
/gate/source/mybeam/gps/hist/point 1.2852521453081618 10675.0
/gate/source/mybeam/gps/hist/point 1.328816612888501 10427.0
/gate/source/mybeam/gps/hist/point 1.3723810804688399 10119.0
/gate/source/mybeam/gps/hist/point 1.4159455480491792 9683.0
/gate/source/mybeam/gps/hist/point 1.459510015629518 9401.0
/gate/source/mybeam/gps/hist/point 1.5030744832098573 9055.0
/gate/source/mybeam/gps/hist/point 1.546638950790196 8678.0
/gate/source/mybeam/gps/hist/point 1.590203418370535 8467.0
/gate/source/mybeam/gps/hist/point 1.6337678859508742 8317.0
/gate/source/mybeam/gps/hist/point 1.677332353531213 8051.0
/gate/source/mybeam/gps/hist/point 1.7208968211115523 7738.0
/gate/source/mybeam/gps/hist/point 1.7644612886918911 7318.0
/gate/source/mybeam/gps/hist/point 1.8080257562722302 7089.0
/gate/source/mybeam/gps/hist/point 1.8515902238525692 6939.0
/gate/source/mybeam/gps/hist/point 1.895154691432908 6867.0
/gate/source/mybeam/gps/hist/point 1.9387191590132473 6627.0
/gate/source/mybeam/gps/hist/point 1.9822836265935861 6253.0
/gate/source/mybeam/gps/hist/point 2.0258480941739254 6202.0
/gate/source/mybeam/gps/hist/point 2.0694125617542642 6002.0
/gate/source/mybeam/gps/hist/point 2.112977029334603 5813.0
/gate/source/mybeam/gps/hist/point 2.1565414969149423 5706.0
/gate/source/mybeam/gps/hist/point 2.2001059644952816 5327.0
/gate/source/mybeam/gps/hist/point 2.2436704320756204 5309.0
/gate/source/mybeam/gps/hist/point 2.2872348996559593 5122.0
/gate/source/mybeam/gps/hist/point 2.330799367236298 4934.0
/gate/source/mybeam/gps/hist/point 2.3743638348166374 4763.0
/gate/source/mybeam/gps/hist/point 2.4179283023969766 4537.0
/gate/source/mybeam/gps/hist/point 2.4614927699773155 4493.0
/gate/source/mybeam/gps/hist/point 2.5050572375576543 4363.0
/gate/source/mybeam/gps/hist/point 2.548621705137993 4080.0
/gate/source/mybeam/gps/hist/point 2.5921861727183324 3968.0
/gate/source/mybeam/gps/hist/point 2.6357506402986717 3903.0
/gate/source/mybeam/gps/hist/point 2.6793151078790105 3845.0
/gate/source/mybeam/gps/hist/point 2.7228795754593493 3636.0
/gate/source/mybeam/gps/hist/point 2.7664440430396886 3547.0
/gate/source/mybeam/gps/hist/point 2.8100085106200274 3495.0
/gate/source/mybeam/gps/hist/point 2.8535729782003667 3294.0
/gate/source/mybeam/gps/hist/point 2.8971374457807055 3201.0
/gate/source/mybeam/gps/hist/point 2.9407019133610444 3123.0
/gate/source/mybeam/gps/hist/point 2.9842663809413836 3058.0
/gate/source/mybeam/gps/hist/point 3.027830848521723 2880.0
/gate/source/mybeam/gps/hist/point 3.0713953161020617 2886.0
/gate/source/mybeam/gps/hist/point 3.1149597836824006 2685.0
/gate/source/mybeam/gps/hist/point 3.1585242512627394 2590.0
/gate/source/mybeam/gps/hist/point 3.2020887188430787 2540.0
/gate/source/mybeam/gps/hist/point 3.245653186423418 2423.0
/gate/source/mybeam/gps/hist/point 3.2892176540037568 2330.0
/gate/source/mybeam/gps/hist/point 3.3327821215840956 2228.0
/gate/source/mybeam/gps/hist/point 3.3763465891644344 2206.0
/gate/source/mybeam/gps/hist/point 3.4199110567447737 2113.0
/gate/source/mybeam/gps/hist/point 3.463475524325113 2036.0
/gate/source/mybeam/gps/hist/point 3.507039991905452 1945.0
/gate/source/mybeam/gps/hist/point 3.5506044594857906 1812.0
/gate/source/mybeam/gps/hist/point 3.59416892706613 1779.0
/gate/source/mybeam/gps/hist/point 3.6377333946464687 1641.0
/gate/source/mybeam/gps/hist/point 3.681297862226808 1605.0
/gate/source/mybeam/gps/hist/point 3.724862329807147 1552.0
/gate/source/mybeam/gps/hist/point 3.7684267973874856 1470.0
/gate/source/mybeam/gps/hist/point 3.811991264967825 1474.0
/gate/source/mybeam/gps/hist/point 3.855555732548164 1460.0
/gate/source/mybeam/gps/hist/point 3.899120200128503 1387.0
/gate/source/mybeam/gps/hist/point 3.942684667708842 1315.0
/gate/source/mybeam/gps/hist/point 3.9862491352891807 1158.0
/gate/source/mybeam/gps/hist/point 4.02981360286952 1193.0
/gate/source/mybeam/gps/hist/point 4.073378070449859 1052.0
/gate/source/mybeam/gps/hist/point 4.116942538030198 1082.0
/gate/source/mybeam/gps/hist/point 4.160507005610537 1091.0
/gate/source/mybeam/gps/hist/point 4.204071473190876 987.0
/gate/source/mybeam/gps/hist/point 4.2476359407712145 933.0
/gate/source/mybeam/gps/hist/point 4.291200408351554 886.0
/gate/source/mybeam/gps/hist/point 4.334764875931893 867.0
/gate/source/mybeam/gps/hist/point 4.378329343512232 824.0
/gate/source/mybeam/gps/hist/point 4.421893811092572 717.0
/gate/source/mybeam/gps/hist/point 4.4654582786729105 723.0
/gate/source/mybeam/gps/hist/point 4.509022746253249 700.0
/gate/source/mybeam/gps/hist/point 4.552587213833588 662.0
/gate/source/mybeam/gps/hist/point 4.596151681413927 623.0
/gate/source/mybeam/gps/hist/point 4.639716148994266 577.0
/gate/source/mybeam/gps/hist/point 4.6832806165746055 565.0
/gate/source/mybeam/gps/hist/point 4.726845084154944 524.0
/gate/source/mybeam/gps/hist/point 4.770409551735283 455.0
/gate/source/mybeam/gps/hist/point 4.813974019315622 454.0
/gate/source/mybeam/gps/hist/point 4.857538486895962 485.0
/gate/source/mybeam/gps/hist/point 4.9011029544763005 437.0
/gate/source/mybeam/gps/hist/point 4.944667422056639 413.0
/gate/source/mybeam/gps/hist/point 4.988231889636978 383.0
/gate/source/mybeam/gps/hist/point 5.031796357217317 368.0
/gate/source/mybeam/gps/hist/point 5.075360824797656 311.0
/gate/source/mybeam/gps/hist/point 5.1189252923779955 313.0
/gate/source/mybeam/gps/hist/point 5.162489759958334 283.0
/gate/source/mybeam/gps/hist/point 5.206054227538673 282.0
/gate/source/mybeam/gps/hist/point 5.249618695119013 261.0
/gate/source/mybeam/gps/hist/point 5.293183162699352 219.0
/gate/source/mybeam/gps/hist/point 5.336747630279691 214.0
/gate/source/mybeam/gps/hist/point 5.380312097860029 195.0
/gate/source/mybeam/gps/hist/point 5.423876565440368 173.0
/gate/source/mybeam/gps/hist/point 5.467441033020707 146.0
/gate/source/mybeam/gps/hist/point 5.511005500601047 149.0
/gate/source/mybeam/gps/hist/point 5.554569968181386 140.0
/gate/source/mybeam/gps/hist/point 5.598134435761724 143.0
/gate/source/mybeam/gps/hist/point 5.641698903342063 130.0
/gate/source/mybeam/gps/hist/point 5.685263370922403 102.0
/gate/source/mybeam/gps/hist/point 5.728827838502742 85.0
/gate/source/mybeam/gps/hist/point 5.772392306083081 87.0
/gate/source/mybeam/gps/hist/point 5.8159567736634195 81.0
/gate/source/mybeam/gps/hist/point 5.859521241243758 67.0
/gate/source/mybeam/gps/hist/point 5.903085708824097 61.0
/gate/source/mybeam/gps/hist/point 5.946650176404437 45.0
/gate/source/mybeam/gps/hist/point 5.990214643984776 42.0
/gate/source/mybeam/gps/hist/point 6.0337791115651145 34.0
/gate/source/mybeam/gps/hist/point 6.077343579145454 20.0
/gate/source/mybeam/gps/hist/point 6.120908046725793 25.0
/gate/source/mybeam/gps/hist/point 6.164472514306132 12.0
/gate/source/mybeam/gps/hist/point 6.208036981886471 10.0
/gate/source/mybeam/gps/hist/point 6.2516014494668095 10.0
/gate/source/mybeam/gps/hist/point 6.295165917047148 6.0
/gate/source/mybeam/gps/hist/point 6.338730384627488 5.0
/gate/source/mybeam/gps/hist/point 6.382294852207827 1.0
/gate/source/mybeam/gps/hist/point 6.425859319788166 0.0
/gate/source/mybeam/gps/hist/point 6.4694237873685045 2.0
/gate/source/mybeam/gps/hist/point 6.512988254948844 3.0
/gate/source/mybeam/gps/hist/inter Log

#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed {seed}
#1234567890
/gate/application/noGlobalOutput

#/tracking/verbose 2

/gate/application/setTotalNumberOfPrimaries {primaries}
#1000
/gate/application/start
