# INPUTS
# pathOutputDose
# id
# seed 
# primaries
# peakzlength_um
# peakztrans_mm
# peakzlength2_um
# peakztrans2_mm
# peakzlength3_um
# peakztrans3_mm
# peakzlength4_um
# peakztrans4_mm
# peak_material

# Gate /home/as17540/linac/mac/Main_PhS2_Elec_Sensor_5.5xSeaLevel.mac -a '[id,$PBS_ARRAY_INDEX] [peakzlength_um,10] [peakztrans_mm,-5.495] [peakzlength2_um,30] [peakztrans2_mm,-5.485] [peakzlength3_um,50] [peakztrans3_mm,-5.475] [peakzlength4_um,70] [peakztrans4_mm,-5.465] [peak_material,Copper] [seed,$RANDOM$RANDOM$RANDOM] [primaries,20712300] [pathOutputDose,/work/as17540/PhaseSpaces/PhS3_Sensor_10x10_Elec/]'

#=====================================================
# VISUALISATION
#=====================================================

#/control/execute mac/visu.mac

# =====================================================
# GEOMETRY
# =====================================================

/gate/geometry/setMaterialDatabase /home/as17540/linac/data/GateMaterials_5.5xSeaLevel.db

# WORLD
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    0.3 m
/gate/world/geometry/setYLength    0.3 m
/gate/world/geometry/setZLength    1 m
/gate/world/vis/setVisible 1

/gate/world/daughters/name                   PhS_Plane_Two
/gate/world/daughters/insert                 box
/gate/PhS_Plane_Two/setMaterial              Vacuum
/gate/PhS_Plane_Two/geometry/setXLength      22 cm
/gate/PhS_Plane_Two/geometry/setYLength      22 cm
/gate/PhS_Plane_Two/geometry/setZLength      1 nm
/gate/PhS_Plane_Two/placement/setTranslation 0.0 0.0 471 mm #(-529)
/gate/PhS_Plane_Two/vis/setColor             cyan
/gate/PhS_Plane_Two/vis/setVisible           1

/gate/world/daughters/name                   Kill_BackPlane
/gate/world/daughters/insert                 box
/gate/Kill_BackPlane/setMaterial                   Air	
/gate/Kill_BackPlane/geometry/setXLength           30 cm
/gate/Kill_BackPlane/geometry/setYLength           30 cm
/gate/Kill_BackPlane/geometry/setZLength           1 nm
/gate/Kill_BackPlane/placement/setTranslation      0.0 0.0 480 mm
/gate/Kill_BackPlane/vis/setColor                  red
/gate/Kill_BackPlane/vis/setVisible                1

/gate/world/daughters/name                   Kill_FrontPlane
/gate/world/daughters/insert                 box
/gate/Kill_FrontPlane/setMaterial                   Air	
/gate/Kill_FrontPlane/geometry/setXLength           30 cm
/gate/Kill_FrontPlane/geometry/setYLength           30 cm
/gate/Kill_FrontPlane/geometry/setZLength           1 nm
/gate/Kill_FrontPlane/placement/setTranslation      0.0 0.0 445 mm
/gate/Kill_FrontPlane/vis/setColor                  red
/gate/Kill_FrontPlane/vis/setVisible                1

/gate/world/daughters/name         epi
/gate/world/daughters/insert       box
/gate/epi/setMaterial                  Silicon
/gate/epi/geometry/setXLength          180.0 mm
/gate/epi/geometry/setYLength          180.0 mm
/gate/epi/geometry/setZLength          0.01 mm
/gate/epi/placement/setTranslation     0 0 449.995 mm
/gate/epi/vis/setVisible               1
/gate/epi/vis/setColor                 yellow
/gate/epi/vis/forceSolid

/gate/world/daughters/name         bulk
/gate/world/daughters/insert       box
/gate/bulk/setMaterial                  Silicon
/gate/bulk/geometry/setXLength          180.0 mm
/gate/bulk/geometry/setYLength          180.0 mm
/gate/bulk/geometry/setZLength          0.6 mm
/gate/bulk/placement/setTranslation     0 0 449.69 mm
/gate/bulk/vis/setVisible               1
/gate/bulk/vis/setColor                 red

/gate/world/daughters/name         peak_air_box 
/gate/world/daughters/insert       box 
/gate/peak_air_box/setMaterial                  Air 
/gate/peak_air_box/geometry/setXLength          200.0 mm 
/gate/peak_air_box/geometry/setYLength          200.0 mm 
/gate/peak_air_box/geometry/setZLength          11 mm 
/gate/peak_air_box/placement/setTranslation     0 0 455.5 mm
/gate/peak_air_box/vis/setVisible               1 
/gate/peak_air_box/vis/setColor                 green
/gate/peak_air_box/vis/forceWireframe

/gate/peak_air_box/daughters/name         peakLayer1 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer1/setMaterial                  {peak_material} 
/gate/peakLayer1/geometry/setXLength          10.0 mm 
/gate/peakLayer1/geometry/setYLength          10.0 mm 
/gate/peakLayer1/geometry/setZLength          {peakzlength_um} um 
/gate/peakLayer1/placement/setTranslation     -5 5 {peakztrans_mm} mm
/gate/peakLayer1/vis/setVisible               1 
/gate/peakLayer1/vis/setColor                 grey
/gate/peakLayer1/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer2 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer2/setMaterial                  {peak_material} 
/gate/peakLayer2/geometry/setXLength          10.0 mm 
/gate/peakLayer2/geometry/setYLength          10.0 mm 
/gate/peakLayer2/geometry/setZLength          {peakzlength2_um} um 
/gate/peakLayer2/placement/setTranslation     5 5 {peakztrans2_mm} mm
/gate/peakLayer2/vis/setVisible               1 
/gate/peakLayer2/vis/setColor                 red
/gate/peakLayer2/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer3 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer3/setMaterial                  {peak_material} 
/gate/peakLayer3/geometry/setXLength          10.0 mm 
/gate/peakLayer3/geometry/setYLength          10.0 mm 
/gate/peakLayer3/geometry/setZLength          {peakzlength3_um} um 
/gate/peakLayer3/placement/setTranslation     -5 -5 {peakztrans3_mm} mm
/gate/peakLayer3/vis/setVisible               1 
/gate/peakLayer3/vis/setColor                 red
/gate/peakLayer3/vis/forceSolid

/gate/peak_air_box/daughters/name         peakLayer4 
/gate/peak_air_box/daughters/insert       box 
/gate/peakLayer4/setMaterial                  {peak_material} 
/gate/peakLayer4/geometry/setXLength          10.0 mm 
/gate/peakLayer4/geometry/setYLength          10.0 mm 
/gate/peakLayer4/geometry/setZLength          {peakzlength4_um} um 
/gate/peakLayer4/placement/setTranslation     5 -5 {peakztrans4_mm} mm
/gate/peakLayer4/vis/setVisible               1 
/gate/peakLayer4/vis/setColor                 red
/gate/peakLayer4/vis/forceSolid

# =====================================================
# PHYSICS
# =====================================================

/gate/physics/addPhysicsList emstandard_opt4

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      epi 0.0001 mm 
/gate/physics/Electron/SetCutInRegion   epi 0.0001 mm
/gate/physics/Positron/SetCutInRegion   epi 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      bulk 0.0001 mm
/gate/physics/Electron/SetCutInRegion   bulk 0.0001 mm
/gate/physics/Positron/SetCutInRegion   bulk 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer1 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer1 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer1 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer2 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer2 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer2 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer3 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer3 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer3 0.0001 mm

/gate/physics/Gamma/SetCutInRegion      peakLayer4 0.0001 mm #0.0001
/gate/physics/Electron/SetCutInRegion   peakLayer4 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer4 0.0001 mm

#=====================================================
# DETECTORS
#=====================================================

## 
## Dose output electron
## 
/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  {pathOutputDose}/Epi-{peakzlength_um}-{peakzlength2_um}-{peakzlength3_um}-{peakzlength4_um}_peakum-{peak_material}-5.5xSeaLevel-{id}.root
/gate/actor/doseDistribution/attachTo              epi
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setSize               50 50 0.010 mm
/gate/actor/doseDistribution/setResolution         1000 1000 1	 #for 60 micron pixel x4
/gate/actor/doseDistribution/enableNumberOfHits    true
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep false
/gate/actor/doseDistribution/enableSquaredEdep     true
/gate/actor/doseDistribution/enableDose            false
/gate/actor/doseDistribution/enableUncertaintyDose false


/gate/actor/addActor   KillActor                         Kill_BP 
/gate/actor/Kill_BP/attachTo                             Kill_BackPlane 

/gate/actor/addActor   KillActor                         Kill_FP 
/gate/actor/Kill_FP/attachTo                             Kill_FrontPlane 

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize
# /process/em/setBiasingFactor compt 100 True

# /process/em/setSecBiasing compt peakLayer1 100 1000 MeV
# /particle/process/dump

#=====================================================
# BEAMS
#=====================================================

# Read from Phase Space files. Here we indicate the type of particle
# (gamma) because this information is not stored in the PhS to gain
# space. Moreover, we set 'useRandomSymmetry' to generate more
# particle than the number of particle in the PhS, using a Z axis
# symmetry.

#/gate/source/addSource                         beam_g phaseSpace
#/gate/source/beam_g/addPhaseSpaceFile          {inputPhaseSpaceFile}
#{inputParticleType}
#/gate/source/beam_g/attachTo                   PhS_Plane_Two
#/gate/source/beam_g/useRandomSymmetry          true

/gate/source/addSource mybeam gps 
/gate/source/mybeam/gps/particle e- 
/gate/source/mybeam/gps/pos/centre 0 0 471 mm 
/gate/source/mybeam/gps/direction 0 0 -1 
/gate/source/mybeam/gps/type Plane 
/gate/source/mybeam/gps/shape Square 
/gate/source/mybeam/gps/halfx 2 cm 
/gate/source/mybeam/gps/halfy 2 cm 
/gate/source/mybeam/gps/ene/type Arb 
/gate/source/mybeam/gps/hist/type arb 
/gate/source/mybeam/gps/hist/point 0.021996527498655875 21751.0
/gate/source/mybeam/gps/hist/point 0.06559952175521175 29940.0
/gate/source/mybeam/gps/hist/point 0.10920251601176763 38125.0
/gate/source/mybeam/gps/hist/point 0.1528055102683235 42531.0
/gate/source/mybeam/gps/hist/point 0.1964085045248794 45034.0
/gate/source/mybeam/gps/hist/point 0.24001149878143527 45489.0
/gate/source/mybeam/gps/hist/point 0.28361449303799113 45701.0
/gate/source/mybeam/gps/hist/point 0.327217487294547 44508.0
/gate/source/mybeam/gps/hist/point 0.3708204815511029 43590.0
/gate/source/mybeam/gps/hist/point 0.4144234758076588 42352.0
/gate/source/mybeam/gps/hist/point 0.4580264700642147 40976.0
/gate/source/mybeam/gps/hist/point 0.5016294643207705 39563.0
/gate/source/mybeam/gps/hist/point 0.5452324585773264 38032.0
/gate/source/mybeam/gps/hist/point 0.5888354528338823 37041.0
/gate/source/mybeam/gps/hist/point 0.6324384470904382 36001.0
/gate/source/mybeam/gps/hist/point 0.6760414413469941 34765.0
/gate/source/mybeam/gps/hist/point 0.71964443560355 33234.0
/gate/source/mybeam/gps/hist/point 0.7632474298601059 32089.0
/gate/source/mybeam/gps/hist/point 0.8068504241166617 31271.0
/gate/source/mybeam/gps/hist/point 0.8504534183732176 30072.0
/gate/source/mybeam/gps/hist/point 0.8940564126297734 28915.0
/gate/source/mybeam/gps/hist/point 0.9376594068863293 27692.0
/gate/source/mybeam/gps/hist/point 0.9812624011428852 26917.0
/gate/source/mybeam/gps/hist/point 1.024865395399441 25778.0
/gate/source/mybeam/gps/hist/point 1.068468389655997 25174.0
/gate/source/mybeam/gps/hist/point 1.1120713839125527 24366.0
/gate/source/mybeam/gps/hist/point 1.1556743781691088 23477.0
/gate/source/mybeam/gps/hist/point 1.1992773724256645 22595.0
/gate/source/mybeam/gps/hist/point 1.2428803666822206 21879.0
/gate/source/mybeam/gps/hist/point 1.2864833609387762 20835.0
/gate/source/mybeam/gps/hist/point 1.3300863551953324 20319.0
/gate/source/mybeam/gps/hist/point 1.373689349451888 19602.0
/gate/source/mybeam/gps/hist/point 1.4172923437084441 19232.0
/gate/source/mybeam/gps/hist/point 1.4608953379649998 18255.0
/gate/source/mybeam/gps/hist/point 1.504498332221556 17832.0
/gate/source/mybeam/gps/hist/point 1.5481013264781116 17351.0
/gate/source/mybeam/gps/hist/point 1.5917043207346677 16523.0
/gate/source/mybeam/gps/hist/point 1.6353073149912234 16234.0
/gate/source/mybeam/gps/hist/point 1.6789103092477795 15589.0
/gate/source/mybeam/gps/hist/point 1.7225133035043352 14814.0
/gate/source/mybeam/gps/hist/point 1.766116297760891 14349.0
/gate/source/mybeam/gps/hist/point 1.809719292017447 14056.0
/gate/source/mybeam/gps/hist/point 1.8533222862740026 13575.0
/gate/source/mybeam/gps/hist/point 1.8969252805305588 13037.0
/gate/source/mybeam/gps/hist/point 1.9405282747871144 12541.0
/gate/source/mybeam/gps/hist/point 1.9841312690436705 12269.0
/gate/source/mybeam/gps/hist/point 2.0277342633002267 11927.0
/gate/source/mybeam/gps/hist/point 2.071337257556782 11402.0
/gate/source/mybeam/gps/hist/point 2.114940251813338 11192.0
/gate/source/mybeam/gps/hist/point 2.158543246069894 10789.0
/gate/source/mybeam/gps/hist/point 2.20214624032645 10389.0
/gate/source/mybeam/gps/hist/point 2.2457492345830055 9801.0
/gate/source/mybeam/gps/hist/point 2.2893522288395616 9766.0
/gate/source/mybeam/gps/hist/point 2.3329552230961177 9501.0
/gate/source/mybeam/gps/hist/point 2.3765582173526734 9025.0
/gate/source/mybeam/gps/hist/point 2.420161211609229 8751.0
/gate/source/mybeam/gps/hist/point 2.463764205865785 8554.0
/gate/source/mybeam/gps/hist/point 2.5073672001223413 8141.0
/gate/source/mybeam/gps/hist/point 2.550970194378897 8029.0
/gate/source/mybeam/gps/hist/point 2.5945731886354526 7654.0
/gate/source/mybeam/gps/hist/point 2.6381761828920087 7545.0
/gate/source/mybeam/gps/hist/point 2.681779177148565 7248.0
/gate/source/mybeam/gps/hist/point 2.7253821714051205 6945.0
/gate/source/mybeam/gps/hist/point 2.768985165661676 6737.0
/gate/source/mybeam/gps/hist/point 2.8125881599182323 6483.0
/gate/source/mybeam/gps/hist/point 2.856191154174788 6315.0
/gate/source/mybeam/gps/hist/point 2.8997941484313436 6048.0
/gate/source/mybeam/gps/hist/point 2.9433971426878998 5865.0
/gate/source/mybeam/gps/hist/point 2.987000136944456 5688.0
/gate/source/mybeam/gps/hist/point 3.0306031312010115 5637.0
/gate/source/mybeam/gps/hist/point 3.074206125457567 5285.0
/gate/source/mybeam/gps/hist/point 3.1178091197141233 5215.0
/gate/source/mybeam/gps/hist/point 3.1614121139706794 5043.0
/gate/source/mybeam/gps/hist/point 3.205015108227235 4889.0
/gate/source/mybeam/gps/hist/point 3.248618102483791 4568.0
/gate/source/mybeam/gps/hist/point 3.292221096740347 4423.0
/gate/source/mybeam/gps/hist/point 3.335824090996903 4375.0
/gate/source/mybeam/gps/hist/point 3.3794270852534587 4152.0
/gate/source/mybeam/gps/hist/point 3.4230300795100144 4020.0
/gate/source/mybeam/gps/hist/point 3.4666330737665705 4016.0
/gate/source/mybeam/gps/hist/point 3.5102360680231266 3824.0
/gate/source/mybeam/gps/hist/point 3.553839062279682 3584.0
/gate/source/mybeam/gps/hist/point 3.597442056536238 3455.0
/gate/source/mybeam/gps/hist/point 3.641045050792794 3335.0
/gate/source/mybeam/gps/hist/point 3.6846480450493497 3331.0
/gate/source/mybeam/gps/hist/point 3.7282510393059054 3143.0
/gate/source/mybeam/gps/hist/point 3.7718540335624615 3127.0
/gate/source/mybeam/gps/hist/point 3.8154570278190176 2945.0
/gate/source/mybeam/gps/hist/point 3.8590600220755733 2806.0
/gate/source/mybeam/gps/hist/point 3.902663016332129 2719.0
/gate/source/mybeam/gps/hist/point 3.946266010588685 2504.0
/gate/source/mybeam/gps/hist/point 3.989869004845241 2498.0
/gate/source/mybeam/gps/hist/point 4.033471999101797 2508.0
/gate/source/mybeam/gps/hist/point 4.0770749933583526 2358.0
/gate/source/mybeam/gps/hist/point 4.120677987614909 2178.0
/gate/source/mybeam/gps/hist/point 4.164280981871464 2030.0
/gate/source/mybeam/gps/hist/point 4.20788397612802 2049.0
/gate/source/mybeam/gps/hist/point 4.251486970384576 2012.0
/gate/source/mybeam/gps/hist/point 4.295089964641132 1876.0
/gate/source/mybeam/gps/hist/point 4.338692958897688 1746.0
/gate/source/mybeam/gps/hist/point 4.382295953154244 1762.0
/gate/source/mybeam/gps/hist/point 4.4258989474108 1615.0
/gate/source/mybeam/gps/hist/point 4.469501941667356 1550.0
/gate/source/mybeam/gps/hist/point 4.513104935923911 1462.0
/gate/source/mybeam/gps/hist/point 4.556707930180467 1448.0
/gate/source/mybeam/gps/hist/point 4.600310924437023 1395.0
/gate/source/mybeam/gps/hist/point 4.643913918693579 1298.0
/gate/source/mybeam/gps/hist/point 4.6875169129501355 1206.0
/gate/source/mybeam/gps/hist/point 4.731119907206691 1172.0
/gate/source/mybeam/gps/hist/point 4.774722901463247 1141.0
/gate/source/mybeam/gps/hist/point 4.818325895719803 1066.0
/gate/source/mybeam/gps/hist/point 4.861928889976358 1114.0
/gate/source/mybeam/gps/hist/point 4.905531884232914 983.0
/gate/source/mybeam/gps/hist/point 4.94913487848947 934.0
/gate/source/mybeam/gps/hist/point 4.9927378727460265 851.0
/gate/source/mybeam/gps/hist/point 5.036340867002582 843.0
/gate/source/mybeam/gps/hist/point 5.079943861259138 767.0
/gate/source/mybeam/gps/hist/point 5.123546855515694 740.0
/gate/source/mybeam/gps/hist/point 5.167149849772249 727.0
/gate/source/mybeam/gps/hist/point 5.210752844028805 665.0
/gate/source/mybeam/gps/hist/point 5.2543558382853615 612.0
/gate/source/mybeam/gps/hist/point 5.297958832541918 582.0
/gate/source/mybeam/gps/hist/point 5.341561826798474 577.0
/gate/source/mybeam/gps/hist/point 5.385164821055029 489.0
/gate/source/mybeam/gps/hist/point 5.428767815311585 448.0
/gate/source/mybeam/gps/hist/point 5.472370809568141 420.0
/gate/source/mybeam/gps/hist/point 5.515973803824696 420.0
/gate/source/mybeam/gps/hist/point 5.5595767980812525 361.0
/gate/source/mybeam/gps/hist/point 5.603179792337809 348.0
/gate/source/mybeam/gps/hist/point 5.646782786594365 330.0
/gate/source/mybeam/gps/hist/point 5.69038578085092 263.0
/gate/source/mybeam/gps/hist/point 5.733988775107476 248.0
/gate/source/mybeam/gps/hist/point 5.777591769364032 236.0
/gate/source/mybeam/gps/hist/point 5.821194763620587 194.0
/gate/source/mybeam/gps/hist/point 5.8647977578771435 179.0
/gate/source/mybeam/gps/hist/point 5.9084007521337 162.0
/gate/source/mybeam/gps/hist/point 5.952003746390256 133.0
/gate/source/mybeam/gps/hist/point 5.995606740646812 113.0
/gate/source/mybeam/gps/hist/point 6.039209734903367 102.0
/gate/source/mybeam/gps/hist/point 6.082812729159923 83.0
/gate/source/mybeam/gps/hist/point 6.126415723416479 61.0
/gate/source/mybeam/gps/hist/point 6.170018717673035 54.0
/gate/source/mybeam/gps/hist/point 6.213621711929591 21.0
/gate/source/mybeam/gps/hist/point 6.257224706186147 24.0
/gate/source/mybeam/gps/hist/point 6.300827700442703 12.0
/gate/source/mybeam/gps/hist/point 6.344430694699258 7.0
/gate/source/mybeam/gps/hist/point 6.388033688955814 5.0
/gate/source/mybeam/gps/hist/point 6.43163668321237 3.0
/gate/source/mybeam/gps/hist/point 6.475239677468926 2.0
/gate/source/mybeam/gps/hist/point 6.518842671725482 1.0
/gate/source/mybeam/gps/hist/inter Log

#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed {seed}
#1234567890
/gate/application/noGlobalOutput

#/tracking/verbose 2

/gate/application/setTotalNumberOfPrimaries {primaries}
#1000
/gate/application/start
